### ISSUE TITLE
Add Alt field to InsertImage option from toolbar

### ISSUE THREAD

**Issue by kushul** [mdx-editor/editor#100]
Is there the possibility to add a field for Alt text here? I will not let the user to have access to the source code
<img width="572" alt="Screenshot 2023-09-28 at 14 51 02" src="https://github.com/mdx-editor/editor/assets/40826382/c92108ef-c542-4a75-a65a-08bae09f6393">

**Comment by petyosi** [comment]
No, not at the moment. This dialog needs more work, including the option to upload images. Happy to accept a PR for that.

**Comment by petyosi** [comment]
It is available in v1.2.1.

**Comment by kushul** [comment]
Very nice editor. Thank you @petyosi 🙏🏻
