### ISSUE TITLE
Table controls are visible in the `readOnly` mode

### ISSUE THREAD

**Issue by dzikoysk** [mdx-editor/editor#101]
I'm using a toggle option to switch between editable mode. In general, it works fine - I've hidden the toolbar via the CSS property, but for a table it seems to be a bigger issue. In the `readOnly` mode, controls are partly hidden, cells are still selectable, but fortunately - I can't change their value. A comparison:

`readOnly={false}`:
![obraz](https://github.com/mdx-editor/editor/assets/4235722/5cef990f-ac4e-47f6-be18-6456d4df74f7)

`readOnly={true}`
![obraz](https://github.com/mdx-editor/editor/assets/4235722/aef34c6a-fac6-41e8-a606-22a5397043b7)

I'd expect that table component in enabled `readOnly` mode has:
* [x] Immutable cell state
* [ ] Immutable number of columns & rows
* [ ] Cells that cannot be selected (no highlighted border)
* [ ] Due to the lack of controls, the table component should fill full width

**Comment by petyosi** [comment]
That makes sense. Readonly needs more work for each more advanced editor. Open to help here, it's not complicated, just a matter of integrating the flag across the table ui.

**Comment by gabrii** [comment]
Also affected by this. Is there any reasonable workaround or something that could be passed to the `tablePlugin()` to accomplish the desired effect? Thanks!
