### ISSUE TITLE
How to integrate with excalidraw or mermaid

### ISSUE THREAD

**Issue by ReadabilityOne** [mdx-editor/editor#104]
Thanks for creating such a great markdown editor, I'm trying to integrate into my own side-project and it works out-of-the-box.

One use case for my side project is to integrate with excalidraw or tldraw in the markdown editor, similar to the lexcialjs playground example: https://github.com/facebook/lexical/tree/main/packages/lexical-playground/src/nodes/ExcalidrawNode.

One idea to embed an excalidraw diagram into this markdown editor is to use Markdown Directive like:

```
:::excalidraw[An-awesome-excalidraw-diagram](#id)
excalidraw content...(serialized AppState and excalidraw elements)
:::
```

I'm not sure if it's possible to use mdx-editor's `Directives` (https://mdxeditor.dev/editor/docs/custom-directive-editors) to implement such diagram feature, would you help provide some guidances?

If this is feasible, then we can open the door to many custom integrations with other tools like mermaidjs(https://mermaid.js.org/) for UML diagrams, tldraw(https://www.tldraw.com/) to hand draw.

Thanks in advance for help & guidances ;)

**Comment by petyosi** [comment]
Yes, that's exactly the idea behind the custom editors. I am not sure if you want to use directives or code blocks for that purpose. My guess is that code blocks should work better - given the chance that the excalidraw content might have something that can be parsed incorrectly as a markdown syntax. I might be wrong though. 

If you want to use the code block approach, take a look at this [very simple example that integrates a textarea as a code editor](https://github.com/mdx-editor/editor/blob/main/src/examples/basics.tsx#L195). You can use it as a base, and replace the textarea with an editor of your choice. 

Hope this makes sense. I'm closing this issue, but feel free to keep the conversation going, happy to help further.

**Comment by ReadabilityOne** [comment]
Thank you for the suggestion, I have used the custom code block to integrate with mermaid so far, will explore approach to integrate with excalidraw.

I can contribute back those changes as PRs if you're willing to add the diagramming tool into the mdx-editor.

**Comment by petyosi** [comment]
That's awesome. There's one thing that I need to do before accepting sizeable PRs - make the docs in https://mdxeditor.dev/ part of this repository so that the PR can include the necessary documentation - #58 . 

In the meantime, can you put the editor in a fork of this repo? I want to take a look.

**Comment by shaipetel** [comment]
> Thank you for the suggestion, I have used the custom code block to integrate with mermaid so far, will explore approach to integrate with excalidraw.
> 
> I can contribute back those changes as PRs if you're willing to add the diagramming tool into the mdx-editor.

Any chance you can share your mermaid integration? I need to do the same.

**Comment by petyosi** [comment]
Here's an example of a mermaid integration using a code editor: https://github.com/mdx-editor/editor/commit/0b49d74425f638b3afece2c96c457e5194ce88bd#diff-f67e140f11018a1de383b5a17b6b6377f158024ae7dfe44c83c83ffe2be477f9
