### ISSUE TITLE
Saving link dialog submits main form

### ISSUE THREAD

**Issue by makkeu** [mdx-editor/editor#105]
Link dialog is implemented as a form with submit button and submit handler. This causes issues if the editor is inside another form. Saving link dialog also submits the main form, which is not what I want.

I wonder if it should be made using type="button" and onClick handler or do you have any other suggestions to prevent this?

**Comment by petyosi** [comment]
Are you on the latest version? I did a few tweaks to move the dialogs to another container so that I can avoid form nesting. I might be missing something around the virtual react events, though. It would help me if you can reproduce the problem in a sandbox, so that I can find what's to be tweaked.

**Comment by makkeu** [comment]
Yes, version 1.1.2. Here is a minimal sandbox which shows the issue: https://codesandbox.io/s/relaxed-snyder-h5jwjm?file=/src/App.js

I have tested this on latest Safari, not sure if other browsers behave differently on this.

If you edit the existing link (or add a new link), it also submits the main form. It has nothing to do with react events (I think), more like basic html feature where button with `type="submit"` submits the form. Nested forms aren't supported.  I see at least two possible fixes: change link dialog save/cancel buttons to type="button" and use onClick handlers, or render dialog popup in a portal outside the actual application?

Btw, is the title field supposed to work, it seems to do nothing (and not stored in the state). And when editing existing link, it gives an error if left empty (also reproducible in the sandbox above).
```undefined is not an object (evaluating 'state.title.trim')```

**Comment by petyosi** [comment]
Thanks, I think this is the react events being smart; I'm already taking the form out of the app, see the form at the top and at the bottom of the screenshot. 

Nevertheless it's a valid issue. I will look for a way to intercept this in a better way, this is a high priority problem. P.S. The title field needs some love, I'm fighting the downshift integration there. 

<img width="679" alt="image" src="https://github.com/mdx-editor/editor/assets/13347/e3999dc1-8c44-46e0-ae0c-45f3983951f6">

**Comment by petyosi** [comment]
This is actually fixed in 1.2.1. I also changed the way the title is handled, so it should work as expected. Give [it a try](https://codesandbox.io/s/laughing-pine-ry5qjf?file=/package.json).

**Comment by makkeu** [comment]
I can confirm, that this fixes the issue. Thanks 👍🏻 

There is still a small issue with title, editing link won't refill the existing title. But that's unrelated to this issue. And small improvement suggestion also: If adding a link using toolbar, and there is no text selected, it adds a link to the whole row (or do nothing, if there is no text). Would it be more intuitive that adding link without text selection adds a new link with given url (or title) as a text? Some other editors work that way and it feels "more natural".

**Comment by petyosi** [comment]
Thanks for the confirmation. The title handling is weird, I will look into it. 

The link behavior enhancement makes sense. I'm swamped with work right now, so I'm quite happy to accept a PR on the matters. [Here's the place where](https://github.com/mdx-editor/editor/blob/main/src/plugins/link-dialog/index.ts#L172-L200) the magic happens - it needs some Lexical API work.

**Comment by makkeu** [comment]
New version caused another form submit issue. Inserted image has toggle edit dialog button, which doesn't have type property. So it defaults to submit and pressing that button causes main form to be submitted.
