### ISSUE TITLE
There is not clickable area after table or custom editor in _contentEditable_npm11_339 class

### ISSUE THREAD

**Issue by elifciftci** [mdx-editor/editor#106]
Hello. Thanks for creating this library.
I have problem about clickable area. I can add other component that I create with jsx but I can not add text because there is not clickable area inside _contentEditable_npm11_339 class after table or custom editor I create. I have to use directional keys on the keyboard and it is not fast way. I would be grateful if you could help me with this.

I will try to explain my problem simple way.

 - I add my table with mxdEditor. It is not custom component.
 -   After adding table I wanted to add text with BlockTypeSelect. (It also provides by mdxEditor.)
 -   Problem is here: I lost cursor focus. I have to go bottom of table. I can't click bottom of table to add anything, because height of editor area is short. It finish with element we add. You can click top of table because you are inside editor.

I hope this introduction will be understandable to explain my problem.

![](https://user-images.githubusercontent.com/118991944/271937822-27448cd5-8bad-49de-bc5b-70060e21ed61.png)

![](https://user-images.githubusercontent.com/118991944/271938868-92a7f518-3f2a-4585-9f5a-7818ea4d39a6.png)

![](https://user-images.githubusercontent.com/118991944/271938989-a8a16026-a1cf-42fc-95bc-ce5c606917dd.png)

![](https://user-images.githubusercontent.com/118991944/271939221-4d8eee68-d724-437e-8245-366ab0d2290f.png)

![](https://user-images.githubusercontent.com/118991944/271939699-c3711b76-1bd6-43b9-b83a-1ab2d57961de.png)

**Comment by petyosi** [comment]
That's a valid problem. I am still thinking on how to handle it. Same problem in #78 .

**Comment by elifciftci** [comment]
Thank you for responding. I will follow that issue.
