### ISSUE TITLE
OnChange not trigger in Source Code Mode

### ISSUE THREAD

**Issue by agscripter** [mdx-editor/editor#108]
Hello team,

When I switch to the Source Code editor view and I update the code. It does not trigger the **onChange** event.
It only triggers once I switch back to the Rich Text view mode.

Am I missing a configuration? Is it a bug? Or is it a feature request? 
Thank you!

Regards,
Agner.

**Comment by petyosi** [comment]
Thanks for pointing this out. That's a bug/enhancement I guess, you're correct in your expectations. I'll take a look.

**Comment by adaboese** [comment]
Is there a workaround to make this work?

**Comment by adaboese** [comment]
@petyosi any chance on getting this fixed? I am trying to use it to build a content editor for https://aimd.app

**Comment by adaboese** [comment]
I think I can figure out how to fix this. The problem is that when value changes, the editor goes back to non-MergeView.

**Comment by adaboese** [comment]
I needed to somehow workaround this, so I've disabled the MergeView in MDXEditor and added a second editor and use tab to switch between them.

<img width="864" alt="Screenshot 2023-11-21 at 4 40 32 PM" src="https://github.com/mdx-editor/editor/assets/149027443/a2e358c0-4183-4924-b0bf-3e616ad41848">
