### ISSUE TITLE
Feature Requests: slash command, floating toolbar, drag&drop etc

### ISSUE THREAD

**Issue by ReadabilityOne** [mdx-editor/editor#109]
I saw lexicaljs playground has features like:

- slash (/) command to invoke a drop down that contains the shortcut commands.
- floating toolbar when selecting some text.
- Drag and drop a block node.

I'm wondering if we can introduce those convenient features into MDX-Editor, I can contribute if you would give some guidances :)

**Comment by petyosi** [comment]
These are all cool optional features to introduce, and I've considered all of them for future integration. I draw a lot of inspiration (and use the playground code) as a starting point, but usually end up changing a lot of it. 

If you need any of those for your own use, I would be very grateful if you can develop them in a fork of the editor - I would love to pick them up eventually. 

Here's what I can describe as a general guideline/difference between MDXEditor and the playground:

- The playground uses React components for logical plugins. The MDXEditor codebase uses a stream-based state management - I find it hard to manage complex state with react hooks. 
- Most of the UI primitives (popups, dropdowns, etc) in MDXEditor use the [Radix components](https://radix-ui.com/). 
- The icons are taken from Google's Material design system, with some modifications where necessary. 
- I've developed a simple CSS variables based styling mechanism. 

Hope this helps - let me know if you need any further clarifications. I'm going to close this issue but feel free to follow up.
