### ISSUE TITLE
Optimize bundle size

### ISSUE THREAD

**Issue by petyosi** [mdx-editor/editor#11]
Continuing the discussion from #10:

- [ ] Improve lazy loading of components that pull large external dependencies (CodeMirror, Sandpack)
- [ ] Make JSX handling optional (use dynamic import), a property like `disableMdx`, this would avoid Acorn
- [ ] Work around the `@lexical/code` reference, this will eliminate prism. 
- [ ] See if markdown rendering in the TableEditor can be avoided, this will shave off the hast family of dependencies

**Comment by aaronhuggins** [comment]
@petyosi The new plugin architecture is incredible and I cannot thank you enough! I'm able to get the minified bundled editor for my project down to below 1 MB before gzip.

I had also been looking for a way to get a custom code editor into the mix, and again, you absolutely killed it with your new codeblock plugin.

Big thanks, and you're on my list to donate when I have work again!
