### ISSUE TITLE
modify markdown at the place of cursor

### ISSUE THREAD

**Issue by armannaj** [mdx-editor/editor#110]
Currently I'm using the following code to add certain markdown items to the current markdown

```
ref?.current?.setMarkdown(`${currentMarkdown} <new markdown>`);
```

However, this needs to be added where the cursor is, how can I achieve that? 

`ref.current` doesn't seem to have any function for that.

**Comment by petyosi** [comment]
Without knowing much about the specifics, I would recommend that you use the Lexical API instead. In there, you have a finer grained API capabilities, access to the selection, etc.

**Comment by armannaj** [comment]
That's okay, how do i access the Lexical editorstate object?

ref.current only contains 3 functions.

**Comment by petyosi** [comment]
Check the source code of some of the more basic plugins - for example, the link dialog. There's an internal state management system that gives you access to the current editor (could be the main, or one of the nested ones), and the selection.

**Comment by ungureanustefan** [comment]
@armannaj Hi, have you found a way to do that?

**Comment by lukasbach** [comment]
My way for getting a reference to the lexical editor, was to add a mdxeditor plugin, in its postInit function you get a reference to a realm, running `realm.getValue(rootEditor$)` yields the reference to the lexical editor
