### ISSUE TITLE
How to handle line breaks

### ISSUE THREAD

**Issue by jwbackhouse** [mdx-editor/editor#112]
I suspect there's a way to do this using the existing APIs, but afraid I can't work out how.

I'm trying to adapt the default behaviour so that
a) paragraphs are not separated by an empty line by default
b) the user is able to add >=1 empty lines if they choose

The default behaviour at the moment is that paragraphs are separated by an empty line, and multiple line breaks get collapsed into a single line break.

I've managed to achieve a) by manually editing the string in the `onChange` to strip empty lines:
```js
string.replace(/\n(?!\n)/g, '')
```

But even though multiple line breaks are left intact, the editor is then collapsing them itself. I've tried playing around with `toMarkdownOptions.join` but this seems to apply too late, after this 'collapse' has happened.

[Here's a sandbox](https://codesandbox.io/s/catch-all-plugin-forked-dnv76r?file=/src/App.tsx) that hopefully explains the issue: the additional line breaks are ignored, and whilst the user can add them in manually in the editor, as soon as the editor updates (by clicking the button) the additional line breaks disappear.

Can you point me in the right direction? Thanks

**Comment by petyosi** [comment]
As far as I understand your requirements, this feels "against" the markdown idea. There are several workarounds mentioned in this [stackoverflow thread](https://stackoverflow.com/questions/20543454/create-two-blank-lines-in-markdown), but integrating them in the editor is something I have not thought about. Of course, everything is possible, but hacking the Enter keypress is far from a road I've explored. 

You can certainly remove the spacing of the paragraphs with CSS, but you probably need b) as well. 

Of course, I don't know the context of your requirements, but this seems like a "proxy" to another kind of issue to me.lll

**Comment by jwbackhouse** [comment]
Thanks for the reply - I got things working using `&nbsp;\n` 👍🏼

**Comment by Prominence** [comment]
> Thanks for the reply - I got things working using `&nbsp;\n` 👍🏼

Can you, please, describe more detailed what have you done to make it work? It seems, that I have the same requirements...

**Comment by danieldai** [comment]
line1
line2





line3
line4

**Comment by MilanMeurrens** [comment]
This is specifically for the React MDX-Editor package. We also needed to preserve multiple blank lines which isn't really what Markdown is made for.

Here's the setup:

```typescript
interface Props {
    value: string;
    onChange: (value: string) => void;
    placeholder?: string;
}

const CustomMDXEditor = ({ value, onChange, placeholder }: Props) => {
    return (
        <MDXEditor
            plugins={plugins}
            placeholder={placeholder}
            markdown={value}
            onChange={onChange}
        />
    );
};

export default CustomMDXEditor;
```

Then in the component using it, before saving the Markdown as a string to your database, do this:

```typescript
const processed = data.description.replace(/\n{2,}/g, (match) => {
    return '\n\n' + '<br />\n'.repeat((match.length - 1) / 2);
});
```

**! Don't do this on every change, this will mess it up.**

For every sequence of 2 or more newlines:

- Always keep the first two newlines (\\n\\n)
- For every additional newline, add a \<br /\>\\n
- Not really sure why, but I had to divide by two, otherwise it would always double the blank lines...

This seems to make it work as expected for our application. Maybe there are still some edge cases.

**Comment by BelgianNoise** [comment]
@MilanMeurrens great solution :)

The regex only seems to work on UNIX based OS-s , i updated your regex to `(\r\n|\n){2,}` . Now the bimbiws peeps can enjoy this too.

This still leaves one issue, the markdown it produces does not correctly load back into the editor.
Lines with a <br/> are not seen as `paragraph` and you are not able to type on those lines (only after reloading the markdown in the editor).
Will update this comment if I find a colution

**Comment by arthur-joppart-lemon** [comment]
> * Not really sure why, but I had to divide by two, otherwise it would always double the blank lines...

match returns `|n|n`, the length is 4, and we dont wanna put `4-1` breaks. we only wanna put `(4-1)/2`, and It seems like `repeat()` automatically floors the numbers.
