### ISSUE TITLE
Can we support react component in toolbar dropdown button

### ISSUE THREAD

**Issue by ReadabilityOne** [mdx-editor/editor#113]
Hey dear maintainers,

The current item in toolbar dropdown only contains value and label, the label will be rendered as String, can we make it compatible with React components so that we can have fancier dropdown items with icons?

**Comment by ReadabilityOne** [comment]
I'm talking about this component https://mdxeditor.dev/editor/api/editor.buttonordropdownbutton and it accepts items like { value: T; label: string; }[] as described in doc https://mdxeditor.dev/editor/api/editor.buttonordropdownbuttonprops

**Comment by petyosi** [comment]
As much as I want this library to be a collaborative effort, right now the only maintainer is me :). This being said, what you describe is doable even now if you silence the TypeScript complaint - you can pass a React node to the label. [Check the source code](https://github.com/mdx-editor/editor/blob/main/src/plugins/toolbar/primitives/toolbar.tsx#L204-L227). 

Happy to accept a PR, it's a very small change. Cheers,

**Comment by ReadabilityOne** [comment]
looks like this feature was added in 1.4.0, thank you all :)
