### ISSUE TITLE
A codesandbox example of the live demo

### ISSUE THREAD

**Issue by insanicly** [mdx-editor/editor#118]
Hi everyone, 
the component looks great huge thank you for providing it. 

However, when I try to use it in my project I couldn't even show any toolbar. I would appreciate any help here. For example a codesandbox that is making the [demo](https://mdxeditor.dev/editor/demo) perfect.

**Comment by petyosi** [comment]
More examples are always good, of course. Notice however that this is a relatively complex component, so I do encourage people to go through the docs and understand what they want to include in their setup. A "get all" sandbox might be not the best start. 

I'm a bit surprised by your toolbar issue, though. [You can copy-paste the first snippet](https://mdxeditor.dev/editor/docs/customizing-toolbar) of the toolbar documentation in a sandbox and it works after you add the package to package.json. 

Last, but not least - this is an open source project. I'm giving away a lot of what I've done for free, but my resources are relatively limited. I'm happy to receive and integrate contributions of any kind, including documentation and samples.
