### ISSUE TITLE
Controlled mode is not working properly

### ISSUE THREAD

**Issue by insanicly** [mdx-editor/editor#119]
Hi, 
the markdown property is not working when you want to use the markdown editor in a controlled mode.

Here is a [codesandbox](https://codesandbox.io/s/mdx-editor-sandbox-7kny7w?file=/src/App.js) that is showing what is wrong. You can see that the input value is changing after the timeout (to `hello after`) but the markdown editor is not. It is just keeping its initial value. 
I am expecting that when I change the `markdown` value the content that the editor show should be changed. 

For reference I am putting the sandbox code also here:

```
export default function App() {
  const [markdown, setMarkdown] = useState("hello before");
  useEffect(() => {
    setTimeout(() => setMarkdown("hello after"), 2000);
  }, []);

  console.log({ markdown });
  return (
    <>
      <input
        value={markdown}
        onChange={(event) => {
          setMarkdown(event.target.value);
        }}
      />
      <MDXEditor
        markdown={markdown}
        plugins={[
          headingsPlugin(),
          listsPlugin(),
          quotePlugin(),
          thematicBreakPlugin(),
          toolbarPlugin({
            toolbarContents: () => (
              <>
                {" "}
                <UndoRedo />
                <BoldItalicUnderlineToggles />
              </>
            )
          })
        ]}
      />
    </>
  );
}
```

**Comment by petyosi** [comment]
Please [read the basic documentation of the editor](https://mdxeditor.dev/editor/docs/getting-started#basic-usage). You're going to have very hard time integrating it without doing so.

**Comment by insanicly** [comment]
Sorry for not seeing the basic documentation and taking your time. However, you can get this as a feature request or recomendation because In my humble opinion people will be expecting a controlled component since it is a common way to do things in editors like this. 

But, anyway thank you for pointing me out to the right direction.

**Comment by petyosi** [comment]
The editor is much more complicated than a plain text editor. Controlled mode can easily turn into a crawling performance due to markdown being processed and converted to rich text editors (and vice versa). The current API is designed so people are encouraged query the markdown when necessary (but not more often).
