### ISSUE TITLE
Question on how to customize the className(s) of root and wrapper components

### ISSUE THREAD

**Issue by sberryman** [mdx-editor/editor#121]
I have some complex styling for sizing components and need to set `flex: none` and `flex-grow: 1` on the toolBarRoot and the wrapper around ContentEditable.

https://github.com/mdx-editor/editor/blob/5a101aee11ef4f0ed6b9b0efca50f832ff8bd49b/src/plugins/toolbar/index.tsx#L39C62-L39C62

It isn't clear to me how (or if) I can adjust them. From what I can tell, it isn't possible. Is the best course of action here to customize the `@mdxeditor/editor/style.css` style?

**Comment by petyosi** [comment]
I assume you want to achieve something like this: https://codesandbox.io/s/sweet-cloud-pfs7sx?file=/src/styles.css.

**Comment by sberryman** [comment]
You are correct! I've cheated and just added some custom css around the compiled class names.

```css
._rootContentEditableWrapper_16b3d_991 {
    flex-grow: 1;
}

._toolbarRoot_16b3d_141 {
    flex: none;
}
```
Not knowing the code my first impression is that I would have to fork and add a custom hook to the toolbar plugin (and probably something similar for the wrapper, haven't really looked at that part of the code yet)

**Comment by sberryman** [comment]
My brain clearly wasn't working this morning. I looked at your example and didn't even notice the `flex-editor` class. I've gone that route for now, incredibly easy now that you point out the obvious solution.

Thanks for creating and publishing this project of yours. I'm a big fan of the editor, it allowed me to strip out `quill` from the project.
