### ISSUE TITLE
Checkbox support

### ISSUE THREAD

**Issue by Sozialarchiv** [mdx-editor/editor#13]
What a great editor! Congratulation to for this great software.

Is checkbox support planed? Something that:

- [ ] test
- [x] test2

**Comment by petyosi** [comment]
Thank you!

Up to your question what kind of backend would you use for the checkbox toggling, once the checkbox is rendered? Or maybe I am missing something

**Comment by Sozialarchiv** [comment]
Thank you for the fast answer. 

I would respond to changes from markdown.

**Comment by Sozialarchiv** [comment]
I think there is checkbox support in lexical:

* https://lexical.dev/docs/api/modules/lexical_list
* https://codesandbox.io/embed/lexical-list-plugin-example-00d642?fontsize=14&hidenavigation=1&module=/src/Editor.js,/src/plugins/ListToolbar.tsx&theme=dark&view=split

**Comment by petyosi** [comment]
Yes, there is - it's fairly easy to implement it in the editor. I was more interested in how you're going to deal with the checkboxes "outside" of the editor. For example, when you put checkboxes in the GitHub issue, they are interactive (and modify the actual markup) when rendered in read-only mode.

**Comment by yuzhouu** [comment]
hi, I try to implement task list by extend lists plugin. But I encounter some difficulties.
lexical determine a list is checkbox by `ListNode.__listType`
```
export declare class ListNode extends ElementNode {
    /** @internal */
    __tag: ListNodeTagType;
    /** @internal */
    __start: number;
    /** @internal */
    __listType: ListType;
```

but mdast(with [mdast-util-gfm-task-list-item](https://github.com/syntax-tree/mdast-util-gfm-task-list-item)) determine a list is checkbox by property `list.children.checked `
```
{
     type: 'list',
     ordered: false,
     start: null,
     spread: false,
     children: [
       {
         type: 'listItem',
         spread: false,
         checked: true,
         children: [
           {type: 'paragraph', children: [{type: 'text', value: 'Done'}]}
         ]
       }
     ]
   },
```

so in the file mdastListVisitor I must do the thing like this
``` js
const isCheck = mdastNode.children?.[0]?.checked !== null && mdastNode.children?.[0]?.checked !== undefined
const lexicalNode = $createListNode(isCheck ? 'check' : mdastNode.ordered ? 'number' : 'bullet')
```

Is my implementation correctly, do you have better suggestions?

**Comment by petyosi** [comment]
I guess that's the way to go. Technically, the user can mix and match different list items, not sure how it would work then, though.

**Comment by ValiDraganescu** [comment]
Hi, checkbox support would be great. In fact, it's just a display issue.
If the raw markdown looks like this
```
* [ ] foo
* [x] bar
```
then display like this in the rich text editor

- [ ] foo
- [x] bar

About storing the state of the boxes, I store the entire raw markdown in my database, so changing the state of the checkbox in rich text would be reflected in raw and vice versa. 

I think this would be a basic use case similar to the lists. I would implement it myself but find the Lexical system a little bit overwhelming and it will take me some time to make it. It's probably a lot easier for @petyosi :)

**Comment by petyosi** [comment]
@ValiDraganescu I appreciate your faith in my capabilities. What I do appreciate more though is some help and contributions - the project is fairly large, so the backlog is much larger than what I can handle.

**Comment by Sozialarchiv** [comment]
Thank you very  much.
