### ISSUE TITLE
Pasting code duplicates the code content into the editor

### ISSUE THREAD

**Issue by forhappy** [mdx-editor/editor#130]
When I paste code to the code block area, the code content will overflow to the outside of the code block area in plain text, this can be reproduced in mdx-editor live demo website, see the following screenshot:

https://github.com/mdx-editor/editor/assets/706422/62dd7eb6-c78f-4688-8757-25fdeeb71d34

**Comment by akarabach** [comment]
It's still reproducible for me

**Comment by petyosi** [comment]
@akarabach I need more information to address that. How to reproduce it? The original report is addressed on my side.

**Comment by akarabach** [comment]
@petyosi 

<img width="1575" alt="Screenshot 2023-10-27 at 13 51 10" src="https://github.com/mdx-editor/editor/assets/12261380/0996a970-ea06-41ae-8ffb-340fbf35c164">

you can easily reproduce it for typescript on the demo site

**Comment by petyosi** [comment]
What's the browser you're using?

**Comment by akarabach** [comment]
Chrome Version 118.0.5993.117 (Official Build) (arm64)

**Comment by petyosi** [comment]
@akarabach I'm afraid that I can't reproduce that problem on my side (Same chrome version, mac), pasting with mouse and keyboard. If you can record a video, I might spot something.

**Comment by akarabach** [comment]
@petyosi https://drive.google.com/file/d/17a6Y5qe0FjT-0ksZg38RDYZl9TfcNEAR/view?usp=sharing
