### ISSUE TITLE
How to customize the rendering of the title?

### ISSUE THREAD

**Issue by fyac** [mdx-editor/editor#133]
First of all, I would like to thank the author for providing such an excellent editor,but I also encountered some problems during use.

I need to display the outline content of the markdown document on the right side of the document, and click on a specific title to jump to the actual position of the document title(h1-h5). 

However, after research, I found that the title rendered by mdx-editor does not generate anything similar to an id attribute (generally called an anchor point), which allows the link to directly locate the title. Is there a way to customize the render title, or is there another way to achieve a similar effect?

**Comment by petyosi** [comment]
While possible, rendering the an id is far from trivial - you'll have to override the rendering of the heading Lexical nodes. It might also clash with manually set ids, which I think is possible. 

I believe that there's a much easier way to do what you describe, though. When the document changes, you scan through the editor DOM, grab the headings and build the TOC. On click, you scroll to the element [with scrollIntoView](https://developer.mozilla.org/en-US/docs/Web/API/Element/scrollIntoView). 

Hope this makes sense.
