### ISSUE TITLE
Integrate with lexical @lexical/react/LexicalTypeaheadMenuPlugin?

### ISSUE THREAD

**Issue by forhappy** [mdx-editor/editor#134]
Hey mdx-editor creator,

Is there any way to integrate with `@lexical/react/LexicalTypeaheadMenuPlugin` to support dropdown shortcuts via slash(`/`) command.  LexicalTypeaheadMenuPlugin is an official plugin supported by lexical(the feature is also available in lexcial playground: https://playground.lexical.dev/), is it easy to integrate with mdx-editor plugin system?

I can contribute a bit on this feature but need guidance from you ;) I'd love to see more docs/guides on the mdx-editor plugin usage, really appreciated in advance.

**Comment by ReadabilityOne** [comment]
This would be a very convenient feature, looking forward the community to continue :)

**Comment by petyosi** [comment]
As far as I remember, most of the React plugins are packaged as React components with `null` render. I've integrated some of them by just porting their code to the editor state management system model. However, it's totally possible to inject a React component as well. Here's an example of how I've integrated the [markdown shortcuts plugin](https://github.com/mdx-editor/editor/blob/9201e0222efdefbcc5a953ba5241509d8be58ea5/src/plugins/markdown-shortcut/index.tsx#L27-L42) by injecting the element on init. 

P.S. Feel free to start such questions in the discussions section - the issues are more suitable for concrete problems/features.

**Comment by forhappy** [comment]
Thank you @petyosi I was able to achieve that, and I can share the approach how I did in a separate discussion thread, however implementing similar feature that is flexible enough is challenging.

**Comment by S1SYPHOS** [comment]
> Thank you @petyosi I was able to achieve that, and I can share the approach how I did in a separate discussion thread, however implementing similar feature that is flexible enough is challenging.

I'd be happy to have a look at your implementation!

**Comment by switz** [comment]
would be really nice to see an example of this in action - if I finish a working model, I'll share it here

**Comment by switz** [comment]
I was able to get a basic implementation working fairly well – please tell me if I'm doing something wrong, but as promised, I'll share my code: https://gist.github.com/switz/0ee8f65f7b2c5c691473730f5d33f8df
