### ISSUE TITLE
Editor inserts '\' before any markdown characters

### ISSUE THREAD

**Issue by Alex-Cartwright** [mdx-editor/editor#136]
Hi, apologies if this has a trivial solution but I have been attempting to fix this for hours.

Essentially, whenever I enter a character such as '#', the markdown is actually updated to be '\\#', meaning that the character is escaped and not rendered as markdown. Am I misunderstanding something basic about how this library is applied? I tried cloning both the vite and next.js repos and suffered from the same issue, even with the headingsPlugin active.

If I set the markdown directly e.g. with the initial state as '# hello world', it renders correctly.
![image](https://github.com/mdx-editor/editor/assets/43017299/231f434f-8f2f-467b-a23d-29e576229a15)

I really appreciate any adivce you can give. I've tried searching the issues for someone having a similar problem but I can't find anyone, so I assume I am doing something wrong. Thank you!

**Comment by petyosi** [comment]
Just a wild guess, you need the shortcuts plugin- https://mdxeditor.dev/editor/docs/markdown-shortcuts

**Comment by Alex-Cartwright** [comment]
Thank you so much - this was the issue! I love the editor, thank you.
