### ISSUE TITLE
Can a custom Jsx Component support multiple NestedLexicalEditor

### ISSUE THREAD

**Issue by forhappy** [mdx-editor/editor#137]
Hey dear mdx-editor creator,

I'm wondering if we can support multiple `NestedLexicalEditor` in one custom JSX component, more specifically I'm curious how to implement a Layout JSX component which can support flexible layouts, e.g. two-columns, two-columns, or multiple Tabs.

I'm using this snippet:

```jsx
{
    name: "TwoColumn",
    kind: "text",
    source: "./external",
    props: [{ name: "type", type: "string" }],
    hasChildren: false,
    Editor: () => {
      return (
        <div style={{ border: "1px solid red", padding: 8, margin: 8 }}>
          <div className="grid grid-cols-2 gap-4">
            <div className="border">
              <NestedLexicalEditor<MdxJsxTextElement>
                getContent={(node) => node.children}
                getUpdatedMdastNode={(mdastNode, children: any) => {
                  return { ...mdastNode, children };
                }}
              />
            </div>

            <div className="border">
              <NestedLexicalEditor<MdxJsxTextElement>
                getContent={(node) => node.children}
                getUpdatedMdastNode={(mdastNode, children: any) => {
                  return { ...mdastNode, children };
                }}
              />
            </div>
          </div>
        </div>
      );
    },
  },
```

This can be rendered correct:

<img width="1394" alt="Xnip2023-10-20_22-51-14" src="https://github.com/mdx-editor/editor/assets/706422/9f84c442-5049-4ce7-b924-3c93420414d5">

However when I switch to the markdown mode, it turns into:

<img width="656" alt="Xnip2023-10-20_22-51-29" src="https://github.com/mdx-editor/editor/assets/706422/9d828b3d-1a67-486d-bc08-d53dfd1b05ec">

And when I switch back to rich text editor mode I can only see the content in first nest editor:

<img width="1376" alt="Xnip2023-10-20_22-51-43" src="https://github.com/mdx-editor/editor/assets/706422/efdccd4b-caa9-46a3-904f-4e5223bf16d5">

Would you help answer if JSX component is a good option to implement such layout(columns or tabs) use case, really appreciated.

**Comment by petyosi** [comment]
To start off, yes - this is totally achievable. In fact, this is one of the examples I want to create at some point. In your case, you should change the getContent/getUpdatedMdastNode function implementations in the above, so that they update the respective parts of the mdastNode (at the moment, they both change the root).

**Comment by ReadabilityOne** [comment]
@petyosi Thank you for your quick response, do you have a more concrete example on how to update the getContent and getUpdatedMdastNode? How the mdastNode organized and how to split the mdastNode into multiple nested editors?

**Comment by forhappy** [comment]
Hey @petyosi, any suggestions or guidances on this topic? I can contribute examples once this is achievable ;)

**Comment by petyosi** [comment]
If you have a JSX that looks like this:

```jsx
<TwoPane><Pane>left content</Pane><Pane>right content</Pane></TwoPane>
```

Then your getter should look like this:

```jsx
getContent={(node) => node.children[0].children} // and children[1] for the right pane.
```

And the setter should work the other way around (the fun dance of cloning objects, etc.)

Hope this makes sense. Stop with the debugger in the closure to examine the structure of the mdast node - they are very simple. If you get stuck, do a sandbox - I will help you.

**Comment by forhappy** [comment]
Let me figure this out and how can I put nested JSX components together? A single JSX component as a plugin seems not possible to do that.

**Comment by forhappy** [comment]
Thanks for the guidance, what I mean in a previous thread is it might not be able to insert

`TwoPane><Pane>left content</Pane><Pane>right content</Pane></TwoPane>` from the toolbar action button.

**Comment by petyosi** [comment]
You just need to pass the correct object structure to the `insertJsx` publisher. Use [this playground](https://codesandbox.io/s/ast-playground-r0hvjn?file=/src/index.ts) to see how it looks.

**Comment by forhappy** [comment]
Looks like `insertJsx` doesn't support insert payload with `children`, so how can we insert JSX with children in this case?

**Comment by petyosi** [comment]
True, overlooked that. Can you open a PR? Should be trivial, you can also add an example to the ladle files.

**Comment by forhappy** [comment]
I tried to add the `children` into the `InsertJsxPayload` in `jsx` plugin so that I can pass children when I invoke `insertJsx`, but the typescript checker is not happy at all:

```
interface InsertJsxPayload {
  name: string
  kind: 'flow' | 'text'
  props: Record<string, string>,
  children: Content[], // mdast.Content[]
}
```

I'm not familiar with mdast, looks like it's not that easy to add `children` into the `insertJsx` publisher.

**Comment by petyosi** [comment]
Yeah, TS typings can be a bit tedious with Mdast. I have quite the few `any`s there. I don't think that an accurate typing is achievable, so no worries if you have to force cast something. 

Let me know if you're still struggling, I can get to that later this week.

**Comment by forhappy** [comment]
Yea, I found out there are more places to change that need careful  considerations, I will stop this work as I'm quite busy on something else at this moment.

**Comment by petyosi** [comment]
Here it is. https://github.com/mdx-editor/editor/commit/b303a99341997d47eeb300913ed9f04daf816d79. Going to close this.
