### ISSUE TITLE
Can't insert text where the cursor is

### ISSUE THREAD

**Issue by ungureanustefan** [mdx-editor/editor#138]
Hi,

I've got a few issues and I'm not sure what I'm doing wrong:

1. When I insert a code block, I cannot delete it. Sometimes it can be deleted, but most of the time I can't. It looks like if I press the backspace, it's deleting a white space and then loses focus.
2. I've got a custom <ButtonOrDropdownButton> component that is supposed to add tags wherever the cursor is. It works fine with plain text, but once I add a code block, or table, it behave weirdly; it doesn't insert the tag where I click inside the block.
3. If I inserted a code block and I click above it to add a tag, if there's no text above the code block, the page breaks and returns the following error:

Uncaught Error: No CodeBlockEditor registered for language=null meta=null
    at CodeBlockEditorContainer (CodeBlockNode.js:136:11)
    at renderWithHooks (react-dom.development.js:16305:18)
    at mountIndeterminateComponent (react-dom.development.js:20074:13)
    at beginWork (react-dom.development.js:21587:16)
    at beginWork$1 (react-dom.development.js:27426:14)
    at performUnitOfWork (react-dom.development.js:26557:12)
    at workLoopSync (react-dom.development.js:26466:5)
    at renderRootSync (react-dom.development.js:26434:7)
    at recoverFromConcurrentError (react-dom.development.js:25850:20)
    at performSyncWorkOnRoot (react-dom.development.js:26096:20)

**Comment by petyosi** [comment]
Hey, to help you further, please reproduce the problems you experience in a codesandbox, and give me some steps to reproduce. Chances are, you've encountered some bugs, but I do need to reproduce them on my side to resolve them. 

Thank you,

**Comment by ungureanustefan** [comment]
Hi, Thank you very much for the prompt response. I might not be doing something right, but I'll try to be as explicit as possible and I'll also leave some comments in the code.

What I'm trying to achieve is that I want to have my own dropdown button with values that represents "tags" and if I click anywhere in the editor and then select the tag, I expect the tag to be inserted where the cursor was. Also, I would like to be able to delete the code blocks after inserting them and saving them into the DB, but for whatever reason, sometimes it works, and sometimes it doesn't; but most of the time it doesn't. 

The codesandbox is this: https://codesandbox.io/p/sandbox/stoic-napier-232h24?file=%2Fsrc%2FApp.css%3A3%2C21

The code is inside App.tsx

The issues are the following:

1. If I add a code block and I want to add a “tag” from the "Tags" button, the page breaks.

2. If I add a "table" or an "admonition" and I try to add a “tag”, it behaves weirdly.

3. If I add a code block and I save it into the DB, next time when I refresh the page I can’t delete the code block. I think that might be due to the back-end parsing the code block in a way unsupported by the editor.

This is how it's being done with regards to the code block - 
<img width="606" alt="image" src="https://github.com/mdx-editor/editor/assets/66925851/9622b111-fe56-46e2-9c5a-c07dabe794fd">

And this is what happens further.
a) Sent from the editor to the DB - 
<img width="430" alt="image" src="https://github.com/mdx-editor/editor/assets/66925851/cfd13126-4319-4b3a-aa9d-3e1876bad74a">

b) Received in the db - 
<img width="117" alt="image" src="https://github.com/mdx-editor/editor/assets/66925851/7f77d07a-abac-4812-b7f3-3780ed36568d">

c) Retrieved in the front end - 
<img width="452" alt="image" src="https://github.com/mdx-editor/editor/assets/66925851/35662a4e-54e6-4e35-99cc-7a03302451b4">

After this, I cannot delete the code block anymore. I managed to reproduce the error on the live demo on the editor's documentation page as well, but I'm not sure what caused it, because I can't do that anymore.

Thanks again.

**Comment by petyosi** [comment]
Thanks for the reproduction instructions. I've traced down the problem to an erratic ref not being correctly passed by the code block editor. Will look for a solution, probably a button of some sort. It's a known issue with code mirror, unfortunately.

As per the sandbox - I'm afraid that the direction you've taken is not going to work out. The proper way to extend the editor is with plugins that interact with the lexical API, including its selection mechanisms and node insertion/manipulation. I understand that this takes a bit more of an investment, as you need to understand how the plugins work (looking at their source code is actually not so scary), and you need to learn a bit of Lexical if you're not familiar with it, however, the model is robust and solves quite a few problems.

**Comment by ungureanustefan** [comment]
Hi @petyosi ,

Thank you for your reply.

I'll choose a different approach for the "Tags" then.

However, I've found two more bugs in the documentation live demo:

1) Click in the middle of a text and insert a code block. Click on "Diff mode" and then click on "Rich text". The page breaks.
2) Click on an empty space, insert a code block, click underneath it and add some text. Click on "Diff mode" and then click on "Rich text" again. The code block extends and covers a lot of text underneath.

**Comment by petyosi** [comment]
Thanks for reporting those! I just pushed a fix for it.
