### ISSUE TITLE
How to customize the dialog for InsertImage？

### ISSUE THREAD

**Issue by greenking19** [mdx-editor/editor#139]
I am using @ mdxeditor/editor: 1.4.2.
Its functionality meets my expectations, and now I want to customize the InsertImage dialog
This is the dialog for InsertImage👇
<img width="382" alt="image" src="https://github.com/mdx-editor/editor/assets/43332372/4f96672b-1769-4535-8b7a-bc7241051d01">
I don't need alt or title, but I need a text input box for 'name'.
How do I need to configure it?

**Comment by petyosi** [comment]
Hey, 

Making the built-in tooling properly configurable is practically impossible - there are endless variations in terms of layout, theming, etc), so I'm not considering this a viable path for the project. 

Instead, I would suggest that you examine the source code of the dialog, and build your own based on the code you see there.

**Comment by greenking19** [comment]
> Hey,
> 
> Making the built-in tooling properly configurable is practically impossible - there are endless variations in terms of layout, theming, etc), so I'm not considering this a viable path for the project.
> 
> Instead, I would suggest that you examine the source code of the dialog, and build your own based on the code you see there.

Thank you！🥳

**Comment by greenking19** [comment]
> Hey,
> 
> Making the built-in tooling properly configurable is practically impossible - there are endless variations in terms of layout, theming, etc), so I'm not considering this a viable path for the project.
> 
> Instead, I would suggest that you examine the source code of the dialog, and build your own based on the code you see there.

I customized a dialog for InsertImage. How to insert the URL returned by the server into the marddown-text?
Do I need to write an imagePlugin?

**Comment by greenking19** [comment]
I tried to imitate an imageSystem and found that the engineering quantity was not small
