### ISSUE TITLE
Image upload documentation

### ISSUE THREAD

**Issue by Aurazor** [mdx-editor/editor#140]
Hi,

I'm currently latest version of the editor and I noticed that Image upload is not working and there is no documentation on this part. Can you please help me with that? Or maybe show me a sample code?

**Comment by petyosi** [comment]
There's sample code in the documentation for image upload. If something does not work for you, reproduce the problem in a sandbox along with steps to reproduce. I will take a look.

**Comment by tomyoktavian** [comment]
Hi @petyosi , I have used your editor but I have a problem when I want to replace the image dialog from my image gallery where it only returns src and alt only, is there a way to customize the image dialog like with my image gallery and how do I put the image in an editor like YoutubeDirectiv?

**Comment by petyosi** [comment]
@tomyoktavian https://github.com/mdx-editor/editor/issues/139. 

I'm closing this, as it is not actionable at the moment. @Aurazor, if you manage to reproduce concrete problems, open a new issue with the details.
