### ISSUE TITLE
How to insert custom html with toolbar

### ISSUE THREAD

**Issue by waltherjochen** [mdx-editor/editor#142]
Hi,
I want to add custom html in the editor with the toolbar.
In the docs I can only see how to add custom directive with (insertDirective), but this always has : or :: or ::: before the text.

Basically what I want to do is add an img tag to the content.

I found also your internal insertImage function.
`
const insertImage = imagePluginHooks.usePublisher("insertImage");
insertImage('https://www.google.com/images/branding/googlelogo/1x/googlelogo_color_272x92dp.png');
`
 Currently you have to drag the current image to generate an img, but I want it to be an img at the start.

Is this clear?

Thanks a lot.

**Comment by petyosi** [comment]
> Is this clear?

Not entirely, I'm afraid. To start off, dealing with HTML is quite messy at the moment. I'm working on making things easier in [this branch](https://github.com/mdx-editor/editor/compare/main...tolerant-html), but properly handling HTML (including control over the tags attributes, etc.) is a huge work, which crawls out of the scope of dealing with Markdown content. My short term goal is to stop the editor from exploding when encountering markdown with mixed html in it. 

[There's an `insertJsx` utility](https://github.com/mdx-editor/editor/blob/bae8fb2ed8fe62ffd1429b4dc136c84f698b9eed/src/plugins/jsx/index.ts#L89-L105), which lets you inject any kind of tag, including html. But it does that near the cursor, not in the beginning of the document. 

Can you explain what you're trying to achieve from the users' perspective?
