### ISSUE TITLE
How to track the change of `viewMode` using `DiffSourceToggleWrapper`

### ISSUE THREAD

**Issue by umer4ik** [mdx-editor/editor#146]
Hey, thanks for an amazing editor!

I want to keep the setting of `viewMode` that I use in `diffSourcePlugin` in app state, however I didn't find any solution for this in the docs, is it possible?

I see in DiffSourceWrapper there's a hook for getting a `viewMode` value

```TS
...
const [viewMode] = diffSourcePluginHooks.useEmitterValues('viewMode')
...
```

but when I try to use the same hook, it leads to error with the following content

```
Uncaught TypeError: Cannot read properties of undefined (reading 'getKeyValues')
```

**Comment by petyosi** [comment]
Great work on figuring this out. What you're doing should work, unless you do the whole thing in an inline component (where the context is not available). Can you reproduce this in a sandbox? I'll take a look.

**Comment by umer4ik** [comment]
Thanks for the quick response, I don't know what "inline component" mean, but I made a sandbox https://codesandbox.io/s/priceless-stallman-xy7trl?file=/src/Editor.js

**Comment by petyosi** [comment]
Yes, that's the problem I had in mind. The hooks you're accessing are reading values from a context that the `MDXEditor` component creates, but you're trying to call them a component outside of its hierarchy. 

[Here's how it works ](https://codesandbox.io/s/goofy-cookies-yn7tt6?file=/src/Editor.js)from inside a component that gets rendered in the Toolbar.

If you want to do that from an element that is above the editor, then you can wrap the entire thing as a plugin, and [then use the approach of the toolbar plugin](https://github.com/mdx-editor/editor/blob/main/src/plugins/toolbar/index.tsx#L32). As you can see the file above is not so complex. 

Let me know if this makes sense.

**Comment by umer4ik** [comment]
It actually makes much sense, thank you, I get what's the problem/

I've [modified your sandbox](https://codesandbox.io/s/sweet-sky-szjcs6?file=/src/Editor.js) and add a store for saving the viewmode state and it exactly what I needed!

**Comment by umer4ik** [comment]
closing the issue, this is how it solved

```tsx
const DiffStatus = () => {
  const [viewMode] = diffSourcePluginHooks.useEmitterValues("viewMode");
  // viewMode can be accessed here and saved to a state
  return null;
};
export const Editor = ({ defaultValue }) => {
  // you can get viewMode from the state and set it to diffSourcePlugin
  const viewMode = 'rich-text';
  return (
    <>
      <MDXEditor
        markdown={defaultValue}
        plugins={[
          headingsPlugin(),
          diffSourcePlugin({
            diffMarkdown: defaultValue,
            viewMode
          }),
          toolbarPlugin({
            toolbarContents: () => (
              <>
                <DiffSourceToggleWrapper>
                  <UndoRedo />
                </DiffSourceToggleWrapper>
                <DiffStatus />
              </>
            )
          })
        ]}
      />
    </>
  );
};
```
