### ISSUE TITLE
Next.js: Prop `title` did not match. Server: "Undo (Ctrl+Z)" Client: "Undo (⌘Z)"

### ISSUE THREAD

**Issue by waltherjochen** [mdx-editor/editor#151]
Hi,

I get the following error on next.js:
<img width="1005" alt="image" src="https://github.com/mdx-editor/editor/assets/15231733/0412331f-51b6-4935-9f66-baa678a0074e">

How to fix this?

Thank you

**Comment by petyosi** [comment]
https://mdxeditor.dev/editor/docs/getting-started#nextjs-app-router
