### ISSUE TITLE
Can't remove escape characters for square brackets

### ISSUE THREAD

**Issue by ungureanustefan** [mdx-editor/editor#153]
Hi,

I'm trying to save some values with the following format "[[EXAMPLE_EXAMPLE]]" but it gets saved as "\\[\\[EXAMPLE\\_EXAMPLE]]" .

What can I do to address this issue?

Thank you

**Comment by petyosi** [comment]
This is automatically done by the underlying markdown AST serializer to ensure valid markdown. Most likely because the square brackets do stuff in Markdown. I am unaware of any way to disable this. You can probably post-process the resulting markdown string.
