### ISSUE TITLE
LinkDialog opens when pressing Ctrl key

### ISSUE THREAD

**Issue by gc-victor** [mdx-editor/editor#16]
When pressing the key Ctrl, the LinkDialog shows up. I guess it is related to the following:
https://github.com/mdx-editor/editor/blob/01d0f2a82aa1d834baf452077d1fa4e91a975306/src/system/LinkDialog.ts#L119

PS: The shortcuts don't work

**Comment by petyosi** [comment]
Thanks for reporting this - fixed in [v0.7.2](https://github.com/mdx-editor/editor/releases/tag/v0.7.2). Can you elaborate on

> PS: The shortcuts don't work

**Comment by gc-victor** [comment]
It was related to:

> Select a text and press Ctrl+B to make it bold, Ctrl+I to make it italic, or Ctrl+U to underline it. Use Cmd on macOS.
[Markdown keyboard Shortcuts](https://mdxeditor.dev/editor/docs/markdown-shortcuts)

I have installed the latest version, and now they are working correctly.
