### ISSUE TITLE
Getting Markdown Back Out

### ISSUE THREAD

**Issue by tris203** [mdx-editor/editor#163]
Hi Guys

Thanks for the tool this is awesome!

I have looked through the documentation and maybe I have overlooked it.

But is there a recommended way to get the data back out of the component, for example for saving into a Database, or updating data stored elsewhere.

I get that I can pass the data in, using the markdown prop. but how can I get the modified markdown back out?

Thanks

**Comment by ReadabilityOne** [comment]
https://mdxeditor.dev/editor/docs/getting-started see the Basic usage section where getMarkdown() can be called to get the markdown content.

**Comment by tris203** [comment]
Seems obvious now. I wonder if this could go in a separate section on the docs to make it clearer. Or maybe I was just too tired reading the docs!

Thanks for the advice @ReadabilityOne
