### ISSUE TITLE
Check list box and text does not align correctly

### ISSUE THREAD

**Issue by ReadabilityOne** [mdx-editor/editor#167]
Looks like the list checkbox and the text doesn't align properly if we use prose class to style the editor, it can be reproduced in editor live playground.

**Comment by petyosi** [comment]
Yes, if prose is used, some additional adjustments are necessary. Not the only instance where this is needed. This is the file where I've done quite a few of those. https://github.com/mdx-editor/site/blob/master/app/globals.css.

**Comment by petyosi** [comment]
Solved.
