### ISSUE TITLE
Plugins not displaying

### ISSUE THREAD

**Issue by blerimj** [mdx-editor/editor#168]
I'm trying to use the editor with next@14.0.2 app router, but the plugins are not loading. I'm just getting a text box without any header.
<img width="456" alt="image" src="https://github.com/mdx-editor/editor/assets/182351/df91c95d-e04b-4ea0-be22-1e2aec9f438f">
I'm following the example for nextjs getting started page - https://mdxeditor.dev/editor/docs/getting-started.
Also checked the repo that is referenced in the same getting started with nextjs section (https://github.com/mdx-editor/mdx-editor-in-next), but that also produces the same result for me. No plugins!

Thank you

**Comment by petyosi** [comment]
Did you add the toolbar plugin?
