### ISSUE TITLE
Editor steals focus when markdown is updated

### ISSUE THREAD

**Issue by urb4nc4rl** [mdx-editor/editor#170]
Setting the markdown of an MDXEditor seems to steal focus.

For example:

`mdxEditor.current?.setMarkdown(props.someMarkdown);`

This will result in `mdxEditor` taking focus, which is undesirable in an application, particularly mobile, since it causes the keyboard to appear.

**Comment by petyosi** [comment]
Didn't I fix this here? https://github.com/mdx-editor/editor/issues/97. Can you help me with a reproduction?

**Comment by petyosi** [comment]
Hey @urb4nc4rl - let me know once you give a reproduction.
