### ISSUE TITLE
Content highlighting

### ISSUE THREAD

**Issue by JR-1991** [mdx-editor/editor#172]
First of all, thanks for the amazing editor! I find it to be very useful and easy to setup 🙏

Is it possible to highlight specific parts within the editor's content? For instance, if certain keywords in an `ul` appear, I want to be able to highlight those for the user. I'd be happy if I could add a custom `id` to the respective `li` element to style it using CSS.

I was looking into this [part of the doc](https://mdxeditor.dev/editor/docs/extending-the-editor) to extend the editor, but I am not sure if that is the correct path to go. Do you have any resources or examples I could look into to make this work?

Thanks a lot in advance!

**Comment by petyosi** [comment]
Hey, 

I believe that you should think about how to represent those highlights in the markdown format - obviously there are plenty of ways to highlight something in the HTML, but that's not what the persistence works with.

You can use custom markdown directives or JSX elements, both work, and it's a matter of preference and how easy would it be for you you to handle them when it comes to rendering the markdown in "read" mode.

**Comment by JR-1991** [comment]
Thanks for the quick answer and advice! I like the JSX insertion a lot and will proceed with that 🙌
