### ISSUE TITLE
Is there cdn version?

### ISSUE THREAD

**Issue by macdevign** [mdx-editor/editor#173]
hi,
just check if there is cdn version?
I like that it can edit markdown visually similarly like html editor.

I thinking whether it can show split screen mode something like Dreamweaver, in visual and text mode, and  editing one mode will affect the other simultaneously.

If there is cdn version, it will be cool, because i can use Keyboard Maestro to show a window using this component
thank

**Comment by petyosi** [comment]
Like all NPM packages, the editor is available at unpkg and jsdelivr. However, it's only distributed in ESM format. Unfortunately, some of it dependencies are shipped as CommonJS while others have ESM. This would probably cause complications without a proper bundler.
