### ISSUE TITLE
inconsistent indentation on Check List plugin

### ISSUE THREAD

**Issue by saoudi-h** [mdx-editor/editor#174]
First of all, thank you for this project.

I've come across a minor glitch in the recently implemented checklist feature, and it appears that the behavior isn't aligning with the intended functionality.

In the spirit of numbered or bulleted lists, I aimed to apply a similar structure to the checklist—specifically, the ability to indent it.

on development mode, When attempting to use tabulations to indent a checklist item, I'm faced with an error. In production mode, I've showcased this directly on the project's site for easy replication of the issue. The observed behavior is less than optimal, with checkboxes stacking up and which are not functional.

https://github.com/mdx-editor/editor/assets/68503582/358b931e-787f-45bb-84b6-a79e07170410

**Comment by petyosi** [comment]
@forhappy - do you think that you can help me here? I'm not deep into the checkboxes usage, but you're probably affected by the problem, too.

**Comment by forhappy** [comment]
Raised a PR https://github.com/mdx-editor/editor/pull/177 to fix the style issue.

**Comment by petyosi** [comment]
Thanks to @forhappy the styling issue should be resolved, I will release an update of the site too.

There's another issue with deep indentation, far more complex and unrelated to the check list item, I believe that this is the error you've mentioned. I will open a separate issue for that.
