### ISSUE TITLE
Application crashes on production env.

### ISSUE THREAD

**Issue by iStorry** [mdx-editor/editor#176]
While deploying the application on other platform apart from vercel applications crashes.

Content-Security-Policy: The page’s settings blocked the loading of a resource at eval (“default-src”). 

[index.mjs:4762](webpack://_N_E/node_modules/.pnpm/@codesandbox+sandpack-react@2.9.0_@lezer+common@1.1.0_react-dom@18.2.0_react@18.2.0/node_modules/@codesandbox/sandpack-react/dist/index.mjs)
EvalError: call to eval() blocked by CSP

**Comment by iStorry** [comment]
<img width="1254" alt="image" src="https://github.com/mdx-editor/editor/assets/7252344/bef7cff2-7d85-4e97-bc62-bbcd74ead99a">

**Comment by petyosi** [comment]
I don't think that the vercel hosting is directly related to the problem. From what I can tell, the sandpack plugin has an eval statement in its code - which makes sense given its features. If you're not using it, you should not bundle it. 

You can examine this further by prettifying the chunk and find the surrounding code - perhaps another plugin does it, I'm not 100% sure.
