### ISSUE TITLE
Unresolvable image authoring UI

### ISSUE THREAD

**Issue by bbrewer97202** [mdx-editor/editor#179]
When using the the Insert Image plugin, if an unresolvable image URL is entered, there does not seem to be a way to correct the error in the UI. 

For example in the [demo](https://mdxeditor.dev/editor/demo) if you enter "http://www.example.com/image.jpg" or "/image.jpg", the UI remains empty because those are not valid images.

If an existing valid image is changed to become an invalid image, it is difficult to edit/remove that markdown.

Would it make sense to show something like a broken image element with the edit gear button in such cases?

Thank you for a great editor!

**Comment by petyosi** [comment]
That's a valid concern, I will look into it.
