### ISSUE TITLE
feature request : Being able to add validation rules (allow/disallow certain features)

### ISSUE THREAD

**Issue by LouisLecouturier** [mdx-editor/editor#18]
It would be awesome to be able to set some rules for instance no links, no images etc... (not just in the toolbar, I mean to have some sort of validation function to enable/disable some markdown features)

**Comment by petyosi** [comment]
Thanks, this is indeed something that can be supported (although, I guess the source mode should be disabled then). My current thoughts gravitate towards a plugin-oriented architecture that would let you omit the features you don't want. This will also reduce the final bundle size.

**Comment by LouisLecouturier** [comment]
That would be gold 🤩 !

**Comment by petyosi** [comment]
@LouisLecouturier check the [new, reworked approach in v0.11.0](https://mdxeditor.dev/editor/docs/overview). The editor now starts barebones, you enable features by including the respective plugin. The toolbar is also customizable, so you have to assemble your own now.

**Comment by LouisLecouturier** [comment]
Wow ! This new approach is awesome !! I love it !

**Comment by okeeffed** [comment]
You got a lot of work done recently @petyosi! Massive props to you
