### ISSUE TITLE
Support for multiple paragraphs within same numbered list 

### ISSUE THREAD

**Issue by fredachang** [mdx-editor/editor#180]
I was wondering if it would be possible to amend the Lists plug in so that there is support for having multiple paragraphs within the same numbered list? Like below: 
![Screenshot 2023-11-17 at 1 18 40 pm](https://github.com/mdx-editor/editor/assets/128881398/6affddb1-d2f2-4c50-84aa-d1748008817f)

Currently there is no way to create a new paragraph within a numbered list without creating a new numbered list.

**Comment by petyosi** [comment]
As far as I can tell, markdown would not like that - and, from what I've seen, Lexical too. This being said, something similar seems to be possible, but it does not use paragraphs but linebreaks (`br` tags). Is this what you're looking for? In Notion, such setup is achieved with shift+Enter. 

1. Paragraph 1
    Paragraph 1.1
    Paragraph 1.2
2. Paragraph 2

**Comment by petyosi** [comment]
Just checked, `shift+Enter` creates line breaks. This works the same way in google docs, so I believe that this should be good enough. Let me know if I am missing something. 
<img width="612" alt="image" src="https://github.com/mdx-editor/editor/assets/13347/98f1fb4c-8080-4665-a42a-aeb88b21416c">
