### ISSUE TITLE
support "slash" commands 

### ISSUE THREAD

**Issue by CHE1RON** [mdx-editor/editor#182]
hello!
is there an easy way to integrate slash commands (or any custom trigger), for stuff like for example typing `@` and trigger loading a list of people to mention that you can choose from? Emojis would work the same way, using `:` as trigger, and so on ..

Thanks for this library, really enjoying it so far!

Cheers,
CH1RON

**Comment by CHE1RON** [comment]
Right on! Thanks for clarifying the situation around the lexical framework - when I was doing research on the topic, I came across it, but since it was too low-level for what I needed, I did not consider them. It's nice to see that your library uses it, which makes it very powerful as just proven! Thanks again 🤩

**Comment by CHE1RON** [comment]
One last thing: I'm using an external plugin which requires to add something to the `initialConfig` of the `LexicalComposer` component - how would I access this in `MDXEditor`, ideally from within my custom plugin (which calls this external `lexical` plugin, like in your example)?

**Comment by petyosi** [comment]
Pushing something to the initialConfig is not available at the moment, but easily doable, happy to accept a PR on the matters. You should probably just copy the logic of the lexicalNodes management implementation. Take a look at MDXEditor.tsx and plugins/core/index.ts.

**Comment by CHE1RON** [comment]
It's strange though, [adding this setup](https://github.com/sodenn/lexical-beautiful-mentions#usage) seems to work fine, and when hitting `#` / `@` the list of mentions gets displayed, however when selecting one of them, I get this:

![image](https://github.com/mdx-editor/editor/assets/122524301/5aac9fc5-9452-440b-8515-cd5420250fa3)

This is my implementation:

![image](https://github.com/mdx-editor/editor/assets/122524301/2f1c97e1-c699-488f-ab30-6da9cd47ffa5)

**Comment by petyosi** [comment]
You do need to add an implementation that serializes the `BeautifulMentionNode` to markdown, and I believe - from it. Not sure how you're going to store those mentions in there. 

Here's [some conceptual documentation](https://mdxeditor.dev/editor/docs/extending-the-editor#markdown--editor-state-conversion).

**Comment by CHE1RON** [comment]
.. but adding a node using `addLexicalNode` was one of the few things possible to do as of now, so from your writeup (which I'm very grateful for) I guess there's no need from my side right now to extend `initialConfig`, right? 😉 

Thanks for your help and this great library 🙏

**Comment by petyosi** [comment]
That's correct I believe. Registering lexical nodes is already supported through the publishing in the `nodes`. If you don't need something else in the initial config, you don't need to extend it at all.

I did not realize that you want to add nodes to the initial config, hence my misguided recommendation.

**Comment by CHE1RON** [comment]
Well, I gotta figure out stuff by myself from time to time 😉 Another thing: It seems that my `addImportVisitor` visitor (called `MdastMentionsVisitor`) never fires, leaving me with default markup for all mentions instead of adding `data` prop etc and apply styling 🤔 

This is my test setup:

![image](https://github.com/mdx-editor/editor/assets/122524301/b878b6c6-2482-44b3-a8a4-0360777097fa)

BTW creating mentions works like a charm, and I have you to thank! 😇

**Comment by petyosi** [comment]
The code from the screenshot looks correct. I should be able to help you further if you can bring your setup into a code sandbox.

**Comment by CHE1RON** [comment]
Might take some time, but I'll do this later - thanks!

**Comment by petyosi** [comment]
@CHE1RON any chance that you're trying to parse a structure that's already parsed by another visitor? Yesterday, I added an optional `priority` numeric field to the visitors, so you may try adding something like `priority: 1000` and see what happens.

**Comment by zilahir** [comment]
@CHE1RON have you managed to figure it out by any chance? I am trying to come up with a similar thing.

**Comment by reinvanleirsberghe** [comment]
@CHE1RON possible to share some code how you implemented the mentions plugin?

Thanks!

**Comment by CHE1RON** [comment]
Hey there! Since we're working on a different feature right now, I never picked it up again .. sorry mate 😅
