### ISSUE TITLE
Custom styling

### ISSUE THREAD

**Issue by zasuh** [mdx-editor/editor#183]
I tried using Tailwind to directly style the editor. While this worked, I noticed there was a separate div at the bottom of my page which was also being styled. I presume this is some hidden element the editor relies on.

Is there a proper way to style the editor to my liking?

**Comment by petyosi** [comment]
The hidden element you refer to is hosting the various popups used across the editors. It's worth to improve that, perhaps the passed class from the props should not be applied there, or there should be a separate prop exclusively for the element.

In the meantime, you can do the following:

- Make the CSS selector `.yourclassname.mdxeditor` - the editor wrapper has a "public" `mdxeditor` class set.
- Style the content using the `contentEditableClassName` prop. 
- Change the "chrome" of the editor through the CSS variables exposed. 

Let me know if this helps.

**Comment by zasuh** [comment]
Managed to do it targeting roles in css:

```javascript
const StyledMDXEditor = styled(MDXEditor)`
  [role='toolbar'] {
    border: 1px solid #d1d5db;
    border-radius: 0.15rem;
    border-bottom-right-radius: 0;
    border-bottom-left-radius: 0;
  }

  [role='textbox'] {
    background-color: white;
    border: 1px solid #d1d5db;
    border-top: none;
    border-radius: 0.15rem;
    border-top-right-radius: 0;
    border-top-left-radius: 0;
    height: 300px;
    overflow-y: auto;
  }
`;
```
