### ISSUE TITLE
Markdown links aren't autolinked if pasted, escaped when getMarkdown()

### ISSUE THREAD

**Issue by rex-iotum** [mdx-editor/editor#186]
Correctly formatted markdown links aren't being autolinked if pasted, only when typed in. When calling `ref.current.getMarkdown()` the pasted link is escaped.

## Steps to Reproduce:
1.  Go to https://mdxeditor.dev/editor/demo
2.  Paste `[test](https://www.test.com)`  into the editor
3.  Paste `[test](https://www.test.com` into the editor and type in `)` manually

## Current behaviour:
Step 2 does not autolink, when `ref.current.getMarkdown()` is called we get an escaped string `'\\[test]\\(http://www.test.com)'`. Step 3 autolinks.

## Expected behaviour:
Both step 2 and 3 creates a markdown link, `ref.current.getMarkdown()` returns both scenarios as a link.

**Comment by petyosi** [comment]
If I understand you correctly, you expect that pasting a ***source*** markdown into **rich text mode** would interpret and convert the markdown payload. This is quite the effort and complexity, to be honest - following that logic, things like lists, headings, and paste content that includes image markdown should be handled in the same way. I might be wrong, but this sounds like you're looking for a different kind of an editor, where the plain text markdown formatting markers are kept intact. This is not the direction of this project.
