### ISSUE TITLE
custom components for toolbar

### ISSUE THREAD

**Issue by CHE1RON** [mdx-editor/editor#187]
hey there,

we're using `@mui` components, and it would be great if we could use the functionality exposed by the plugins (eg if they were hooks like `const { toggleBold } = useBoldItalic()` or whatever), but the only chance I see currently is copying your components (located under `editor/src/plugins/toolbar/components`), modify them & include them in `toolbarContents`, right? 🤔

**Comment by CHE1RON** [comment]
.. or would this be doable within the `contents` prop (which as I see it expects "just" some `React.ReactNode`)

**Comment by petyosi** [comment]
If you want to build your own toolbar, you can use the hooks exposed - https://github.com/mdx-editor/editor/blob/main/src/plugins/toolbar/components/BoldItalicUnderlineToggles.tsx#L10-L11. Most of the toolbar components have almost no logic in them. The API I've exposed through those hooks is not private, just quite... large to be documented. 

If you just want to use your custom icons and you're ok with the toolbar styling, you can take advantage of a recent change I made - the `iconComponentFor` function prop - [take a look](https://github.com/mdx-editor/editor/commit/fc131a232957e3257d7ab82167f5229e7efa75e8#diff-2f87cce00a8d14ad3c01b722933f51f0108605b69fda14856ec6c9148ca1c89e).

**Comment by CHE1RON** [comment]
Another thing that just popped up is re/focus, when having custom elements (not just icons, sorry for not being very concise about that), the editor needs to be refocused after clicking on them ..

**Comment by CHE1RON** [comment]
On a side note: It would be useful to re-export some types from `lexical`, the one I just stumbled across being `ListType` from `@lexical/list` 🤔

**Comment by petyosi** [comment]
- No, the focus is not managed by the radix wrappers but by the internal state management calls. 
- I don't think re-exporting Lexical is necessary, I'm far from being able to create a complete abstraction on top of it, so hiding it does not make sense in my head.

**Comment by CHE1RON** [comment]
I'm deeply sorry, I had some problems installing `@lexical/list` and made some wrong assumptions as to why that is, but didn't realize I was in another repository 🤷 

You are absolutely right, my proposal was not optimal!

**Comment by CHE1RON** [comment]
Closing as what I'm trying to achieve works, woohoo! This library is great 💪
