### ISSUE TITLE
Cursor jumps to start of editor and writes each character on new line

### ISSUE THREAD

**Issue by yashsuhagiya** [mdx-editor/editor#193]
### Description
When typing in the editor, the cursor jumps to the start of the editor and each character is written on a new line. This behavior is unexpected and disrupts the user experience.

## Expected Behavior
The cursor should stay where the last character was typed, and new characters should be added at that position.

## Actual Behavior
The cursor jumps to the start of the editor and each character is written on a new line.

### Code Snippet (.tsx)
```
export default function Editor({ item, handleAnswerChange, value }: any) {
  const ref = React.useRef<MDXEditorMethods>(null);
  const [markdownValue, setMarkdownValue] = useState("");

  useEffect(() => {
    if (ref.current && value) {
      ref.current.setMarkdown(value);
      setMarkdownValue(value);
    }
  }, [value]);

  const handleChange = () => {
    const markdown = ref.current?.getMarkdown();
    setMarkdownValue(markdown as string);
    handleAnswerChange(item.Id, markdown);
  };

  return (
    <>
      <MDXEditor
        ref={ref}
        className="editor-container"
        contentEditableClassName="editor-input"
        placeholder={item.example}
        markdown={markdownValue}
        plugins={[
          headingsPlugin(),
          linkPlugin(),
          linkDialogPlugin(),
          listsPlugin(),
          quotePlugin(),
          imagePlugin(),
          markdownShortcutPlugin(),
          toolbarPlugin({
            toolbarContents: () => (
              <>
                <UndoRedo />
                <BoldItalicUnderlineToggles />
                <BlockTypeSelect />
                <CodeToggle />
                <CreateLink />
                <ListsToggle />
                <InsertImage />
              </>
            ),
          }),
        ]}
        onChange={handleChange}
      />
    </>
  );
```

### Environment

Library version: @mdxeditor/editor: ^1.10.0
Browser: Microsoft Edge
OS: Windows 10

**Comment by petyosi** [comment]
The component is designed as non-controlled on purpose - converting a markdown string to an editable UI is an expensive operation. Your approach is working hard to undo the optimization, causing a heavy computation to happen each keystroke. 

You should set the editor value only when you actually need this.
