### ISSUE TITLE
Cannot use "#" if the headingsPlugin hasn't been included.

### ISSUE THREAD

**Issue by nictruong** [mdx-editor/editor#198]
If I don't include the headingsPlugin, typing "# hello" in Source mode, and then click on Rich-text mode, will cause the following error.

```
no MdastImportVisitor found for heading {"type":"heading","depth":1,"children":[{"type":"text","value":"hello","position":{"start":{"line":1,"column":3,"offset":2},"end":{"line":1,"column":8,"offset":7}}}],"position":{"start":{"line":1,"column":1,"offset":0},"end":{"line":1,"column":8,"offset":7}}}
```

**Comment by petyosi** [comment]
Yes? What do you expect? You're manually adding unsupported formatting.

**Comment by nictruong** [comment]
I'd expect to be able to write "# hello" in Source mode, and see literally "# hello" with no formatting when switching back to rich-text mode, not erroring out.

**Comment by petyosi** [comment]
No, that's not supported, and far from achievable.

**Comment by nictruong** [comment]
Just to confirm, without the plugin (which I don't want to use), it's literally impossible to write `# hello world` and have it display exactly as is, in source mode without the component crashing? It's like a forbidden string.

**Comment by petyosi** [comment]
Confirming that. There's no way to turn off heading parsing in the markdown AST.
