### ISSUE TITLE
support ``` code blocks

### ISSUE THREAD

**Issue by adaboese** [mdx-editor/editor#199]
I was trying to implement basic code block editor following https://mdxeditor.dev/editor/docs/code-blocks guide and was very confused where my code kept disappearing. It appears that only indented code blocks are supported, but ``` are deleted.

**Comment by petyosi** [comment]
I'm afraid I can't help you with that amount of information. From what I see so far I feel like you're facing substantial challenges integrating the editor in your project, which is understandable, given the complexity of the matter. However, I don't have the capacity to provide the amount of support you seem to need. 

I would recommend that you consider another solution that fits your requirements better.

**Comment by adaboese** [comment]
I've moved to https://milkdown.dev/. Honestly, I wish I discovered it earlier. This project is better advertised, but that project is a lot more complete. None of these issues existed. Maybe consider deprecating this project in favor of contributing to https://milkdown.dev/? Just check their playground – it is very complete, and the API is easy to use.
