### ISSUE TITLE
Unsupported plugins break the editor 

### ISSUE THREAD

**Issue by fredachang** [mdx-editor/editor#202]
In the case where a specific plugin is not included (for controlling UI purposes) but the user ends up invoking it via keyboard actions in source code mode, is there a way to handle `no MdastImportVisitor found` errors elegantly?

[](url)
![Screenshot 2023-11-27 at 3 51 56 pm](https://github.com/mdx-editor/editor/assets/128881398/4d19f73f-a098-4e7e-96ec-f2dada9319d9)

**Comment by petyosi** [comment]
You can register a plugin that registers a "catch-all" visitor that does nothing. This will drop the unsupported constructs. Pseudo-code:

```
export const CatchAll: MdastImportVisitor<Mdast.ThematicBreak> = {
  testNode: () => true,
  visitNode({ actions }) {
    // maybe notice the user
  }
}
```

You can grab a [plugin skeleton from here](https://github.com/mdx-editor/editor/blob/main/src/plugins/thematic-break/index.ts).

**Comment by petyosi** [comment]
@fredachang - let me know if the above recommendation worked for you. Thank you.

**Comment by fredachang** [comment]
thanks so much for the quick response again. We will implement this and let you know how we go!

**Comment by fredachang** [comment]
@petyosi do we need to do this for every plug in that we don't plan to include? And in the example where the user tries to input a html comment like `<!-- -->` for one reason or another, would this approach still work if we are not targeting an existing plug in?

**Comment by fredachang** [comment]
I ended up digging into previous issues and found a [solution](https://github.com/mdx-editor/editor/issues/95#issuecomment-1755320066) suggested by a user that worked! Would be ideal if it could be built in but understand if it's hard to make it generic enough to work for everyone.

**Comment by fredachang** [comment]
The catch all works well in `1.9.0` for most cases I've tested but in the latest update something in `source` view in `diffSourceToggle` is broken so unsupported characters throw a different error I haven't seen before. For example `<!— —>`stills throws the following error `Unexpected character `!` (U+0021) before name, expected a character that can start a name, such as a letter, `$`, or `_` (note: to create a comment in MDX, use `{/* text */}`)`.

**Comment by fredachang** [comment]
@petyosi Thank you so much for actively addressing this and extending the help resources on this issue. We are continuing the refine this editor so will let you know if we encounter anything else :)
