### ISSUE TITLE
How to insert a jsx element to a container jsx element

### ISSUE THREAD

**Issue by larryro** [mdx-editor/editor#203]
Thank you for your hard work. The` mdx-editor` is really cool.

Recently, I have been trying to use this editor in the company's project. I need to heavily utilize JSX components, but I have encountered some issues. 

I have two jsx components, one of which acts as a container. 
**Card** - act as the child component
**Grid** - act as the container component

When I insert the child components into the container component via the buttons in the toolbar, an error occurs.

![image](https://github.com/mdx-editor/editor/assets/5787117/1c3fa00a-f94f-4cf7-9369-9cc8b6554c1e)

![image](https://github.com/mdx-editor/editor/assets/5787117/13bd3947-7d57-45db-a457-d1dbda7720f3)

**Reproduce Code:** https://github.com/larryro/mdx-editor-in-cra/blob/master/src/Example.tsx

**Comment by petyosi** [comment]
Thank you very much for the reproduction - this is a very good use case, it helped me track a few outstanding problems with the JSX behavior. 

I just pushed a fix that addresses the error you encounter + few other inconsistencies when it comes to reporting the updates of the nested editor. Your code is right, the only thing which I believe you might need is to:

1) Make the content of the grid separated with new lines
2) add `block` prop to the `NestedLexicalEditor`. 

See the commit above, it includes a slightly modified version of your code. 

Let me know if you encounter any more troubles with your integration. With a reproduction like you have, I should be able to help you.

**Comment by petyosi** [comment]
Thanks for that report. Pushed a fix. FYI: I've noted two other things I would like to improve in that scenario:

- [ ] JSX - nested editor with block does not accept one-liner markdown. Could be solved.
- [ ] Inserting JSX leaves too much whitespace around.
