### ISSUE TITLE
Not rendering with Next.js 13&14

### ISSUE THREAD

**Issue by d3ni00** [mdx-editor/editor#204]
Hello,

i struggle a little bit. I tried mdx-editor in my project (Next.js 14, Node 20). I followed the instructions in the documentation. But all i get is a "textarea".
So i checked out the example (https://github.com/mdx-editor/mdx-editor-in-next) but even that is not running too (tried Next.js 13&14 with Node 18&20).  Also forced the versions in the example. All i get is this (same as in my project):

`<div class="_contentEditable_1g25u_324" contenteditable="true" role="textbox" spellcheck="true" data-lexical-editor="true" style="user-select: text; white-space: pre-wrap; word-break: break-word;"><h1 dir="ltr"><span data-lexical-text="true">Hello world!</span></h1><p dir="ltr"><span data-lexical-text="true">Check the EditorComponent.tsx file for the code .</span></p></div>`

<img width="413" alt="Screenshot 2023-11-28 at 20 29 02" src="https://github.com/mdx-editor/editor/assets/20122367/6fcf64f9-cf1b-4948-956c-965320d56e91">

No UI will rendered. No error messages.

Has anybody an idea what the problem could be?

**Comment by petyosi** [comment]
From what I see, it's rendering as expected. Do you want to add a toolbar? If so, you need the toolbar plugin. Refer to the docs for more details.

**Comment by d3ni00** [comment]
Uff. Im so sorry. Just followed the "getting-started" page and was expecting the toolbar renders as default.
