### ISSUE TITLE
Image dimension fields in dialog?

### ISSUE THREAD

**Issue by dbateman** [mdx-editor/editor#210]
I'm new to this project, so perhaps there is a way to take care of this already. It would be great to add width and height fields (or the option to show them) to the add/edit image dialog.

I've tried using explicit image tags in the editor to specify them that way, but the img tags are always escaped.

The reason this would be great is to help with responsive images to avoid layout shift etc.

**Comment by petyosi** [comment]
If I understand your motivation correctly, there's probably a solution on a markdown rendering level that does [this properly - like this](https://www.npmjs.com/package/rehype-img-size). 

Having an explicit control over the dimensions is not a bad thing, the only problem is that setting it moves away from the markdown syntax, which I personally find not desirable. The current dialog does not support that, though. 

In general, the editor should support and correctly parse the passed HTML images - [see this example](https://github.com/mdx-editor/editor/blob/main/src/examples/images.tsx).

**Comment by dbateman** [comment]
So, for context, I'm using the [NextJS image component](https://nextjs.org/docs/pages/building-your-application/optimizing/images) in conjunction with Cloudinary to serve optimised images to suit the client device being used. This technique needs the image dimensions in order to avoid layout shift.

Whenever I try to create an img tag directly via MDX editor (typing it in - not using the insert image dialog), the tag is escaped. This is true for both the HTML img tag and the markdown syntax. I am using the markdown shortcut plugin in the editor creation but it doesn't prevent the tags being escaped (and it seems that plugin does not support images anyway, based on looking at the source?).

**Comment by dbateman** [comment]
Using the image example you linked to, if I use the diff/source plugin then I am able to insert raw HTML img tags and specify the height and width attributes.

I just updated to the latest release (1.12) and whenever I edit in the source view, the editor switches back immediately to rich text view (making it very difficult to use that way).

**Comment by dbateman** [comment]
OK, sure. It was really about having the option of including width and height fields in the image dialog so that we don't have to roll our own plugin just to be able to add support for them that way. Yes, there are other ways to do it - lie including the dimensions in the image name to be parsed by the client etc and that is fine.

As for the diff/source issue - here is a [fork of the sandbox you linked](https://codesandbox.io/p/sandbox/mdx-editor-base-forked-j5g2hs?file=%2Fpackage.json%3A12%2C27&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clpq48i9g00073b6i3oal8q5o%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clpq48i9g00033b6ihmzjhypi%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clpq48i9g00043b6iu1spwbkf%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clpq48i9g00063b6iynz6qetr%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clpq48i9g00033b6ihmzjhypi%2522%253A%257B%2522id%2522%253A%2522clpq48i9g00033b6ihmzjhypi%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clpq4afso00723b6ipuvqd96b%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A20%252C%2522startColumn%2522%253A28%252C%2522endLineNumber%2522%253A20%252C%2522endColumn%2522%253A28%257D%255D%252C%2522filepath%2522%253A%2522%252Fsrc%252FApp.tsx%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522id%2522%253A%2522clpq518y900023b6hpjdqnsz1%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A12%252C%2522startColumn%2522%253A27%252C%2522endLineNumber%2522%253A12%252C%2522endColumn%2522%253A27%257D%255D%252C%2522filepath%2522%253A%2522%252Fpackage.json%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522activeTabId%2522%253A%2522clpq518y900023b6hpjdqnsz1%2522%257D%252C%2522clpq48i9g00063b6iynz6qetr%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clpq48i9g00053b6ibyyszbxs%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522path%2522%253A%2522%2522%257D%255D%252C%2522id%2522%253A%2522clpq48i9g00063b6iynz6qetr%2522%252C%2522activeTabId%2522%253A%2522clpq48i9g00053b6ibyyszbxs%2522%257D%252C%2522clpq48i9g00043b6iu1spwbkf%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522clpq48i9g00043b6iu1spwbkf%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D) to demonstrate it. It seems that whenever there is an onChange handler when you try to edit the markdown in source view, you are thrown back to rich text view.
