### ISSUE TITLE
onBlur event doesn't work in source code mode

### ISSUE THREAD

**Issue by antrusha0223** [mdx-editor/editor#216]
Hi,

the `onBlur` event doesn't get called in the `source` view mode.

But it worked fine in the `rich-text` mode.

Is there any solution to use `onBlur` in the `source`  view mode?

I created an example to reproduce the issue.

```javascript
<MDXEditor
  markdown={content}
  plugins={[
    headingsPlugin(),
    diffSourcePlugin({ viewMode: "source", diffMarkdown: content }),
  ]}
  onBlur={() => {
    console.log("====== blur event ========");
  }}
/>
 ```

https://codesandbox.io/p/sandbox/frosty-albattani-qrl8f7?file=%2Fsrc%2Findex.js%3A14%2C1

**Comment by petyosi** [comment]
That's a bug, the focus/blur handlers are not attached to the source code editor.

**Comment by antrusha0223** [comment]
Will you fix the bug soon?

**Comment by petyosi** [comment]
Happy to accept a PR on the matters.

**Comment by antrusha0223** [comment]
How can I create a PR? I am not able to create a PR.

**Comment by antrusha0223** [comment]
https://github.com/mdx-editor/editor/pull/222
PR is here @petyosi ...
