### ISSUE TITLE
Change markdownShortcutPlugin logic

### ISSUE THREAD

**Issue by staf02** [mdx-editor/editor#219]
In the case I write text in header (with '#' tag), and then and then completely erase it, then the text that I write will then be without a tag. But if I do the same with Italic ('*') or Bold, I have to press Ctrl+I to switch to clear text without tags. Can you please make the ability to work with Italic or Bold in the same way as with Headers?

**Comment by petyosi** [comment]
This is a behavior that's entirely controlled by Lexical's rich text logic - I. You can dig further in their docs/discord for more details and potential way to override it and do so through a plugin.
