### ISSUE TITLE
Missing MDXEditorMethods on import

### ISSUE THREAD

**Issue by amgabisan** [mdx-editor/editor#220]
I am unsure if I have missed anything on the documentation but so far I have been following based on the examples. I am trying to use the methods `getMarkdown()` and `setMarkdown()` on `MDXEditorMethods`. However I am getting an error: 

`export 'MDXEditorMethods' (imported as 'MDXEditorMethods') was not found in '@mdxeditor/editor'`.

**Comment by petyosi** [comment]
MDXEditorMethods is a TypeScript type. Can you replicate the error somewhere? Also, take a look at the sample repositories for the popular frameworks, perhaps that will help you.

**Comment by amgabisan** [comment]
Thank you so much fixed it!
