### ISSUE TITLE
Table click listeners are off

### ISSUE THREAD

**Issue by SeveHo** [mdx-editor/editor#230]
Whenever a previous cell is focused, and you want to focus/edit a different cell, you have to click twice to focus the cell if you click right on the text inside the cell. This does not happen when I click on the empty space after the text in the cell instead. How can I change this behavior so that there is always only one click necessary?

Happy to work on a PR with some guidance :)

[Here is a link to a sandbox](https://codesandbox.io/p/sandbox/focused-meadow-cxr28g-cxr28g?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clpy3qjn300063b6g01yuzvsq%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clpy3qjn300023b6gmr7vqpf9%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clpy3qjn300033b6g2uv6y4ny%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clpy3qjn300053b6g76q728vv%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clpy3qjn300023b6gmr7vqpf9%2522%253A%257B%2522id%2522%253A%2522clpy3qjn300023b6gmr7vqpf9%2522%252C%2522tabs%2522%253A%255B%255D%257D%252C%2522clpy3qjn300053b6g76q728vv%2522%253A%257B%2522id%2522%253A%2522clpy3qjn300053b6g76q728vv%2522%252C%2522activeTabId%2522%253A%2522clpy3qjn300043b6gb0kgu0pr%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clpy3qjn300043b6gb0kgu0pr%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522path%2522%253A%2522%252F%2522%257D%252C%257B%2522type%2522%253A%2522SANDBOX_INFO%2522%252C%2522id%2522%253A%2522clpy4xjra00b93b6g2r5r8d45%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%255D%257D%252C%2522clpy3qjn300033b6g2uv6y4ny%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522clpy3qjn300033b6g2uv6y4ny%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

**Comment by petyosi** [comment]
Thanks for the repro, this should be easy to fix, somewhere the focus even in the table editor component misbehaves. You can give it a try, just clone the repo, add the example in the ladle examples and throw a few debuggers in the focus/blur logic in the component. 

If you can't solve it, I think I will be able to take a look at that in the upcoming weeks.

**Comment by SeveHo** [comment]
The issues seems to be here:
https://github.com/mdx-editor/editor/blob/32b984c99449dc30c5b63b6c68e0d9df0ac6a933/src/plugins/table/TableEditor.tsx#L324
```js
const saveAndFocus = React.useCallback(
    (nextCell: [number, number] | null) => {
      editor.getEditorState().read(() => {
        const mdast = exportLexicalTreeToMdast({
          root: $getRoot(),
          jsxComponentDescriptors,
          visitors: exportVisitors,
          jsxIsAvailable
        })
        parentEditor.update(() => {
          lexicalTable.updateCellContents(colIndex, rowIndex, (mdast.children[0] as Mdast.Paragraph).children)
        })
      })

      setActiveCell(nextCell)
    },
    [colIndex, editor, exportVisitors, jsxComponentDescriptors, jsxIsAvailable, lexicalTable, parentEditor, rowIndex, setActiveCell]
  )
```

Somehow the `setActiveCell` is called with nexCell being null when clicking on text in another cell when there is already a cell focused. I will investigate this further, but I will have to dig into the concepts of lexical. So if you see a quick solution I'd appreciate it.

**Comment by petyosi** [comment]
Thank you, that was helpful, pushed a fix. Let me know if you still experience problems.
