### ISSUE TITLE
Rewriting the markdown does not render it.

### ISSUE THREAD

**Issue by shhivv** [mdx-editor/editor#235]
I have the MDX editor component setup as such
```tsx
<MDXEditor className="dark-theme dark-editor" contentEditableClassName="twindprose" markdown="# Hello world" plugins={[headingsPlugin()]} />
```
Now, on the initial render the markdown gets rendered perfectly.
![image](https://github.com/mdx-editor/editor/assets/75499121/959ef2bf-01c9-4a48-94a3-20b4ee96aed1)

but when I try to write my own content beyond that, nothing happens.
![image](https://github.com/mdx-editor/editor/assets/75499121/950bb0c5-8517-4f2e-956a-91a7fc72602c)

**Comment by petyosi** [comment]
You don't have the right configuration for the editor to behave as you expect. To avoid further confusion, you can go through [the doc pages](https://mdxeditor.dev/editor/docs/getting-started) here to understand what the various plugins of the editor do - afterwards, you should be able to assemble a configuration that works for you.
