### ISSUE TITLE
Unable to find an active editor state

### ISSUE THREAD

**Issue by fredachang** [mdx-editor/editor#236]
Hello @petyosi, sorry it's me again. After upgrading to `1.13.5` I am encountering a breaking change whenever I click on the new markdown editor. Not sure if this is `next.js` related, as we recently upgraded to next 14. Your help would be appreciated, I have eliminated several other elements (conditional rendering, custom plug ins) and the issue still persists. 

`Lexical.dev.js:7663 Uncaught Error: Unable to find an active editor state. State helpers or node methods can only be used synchronously during the callback of editor.update() or editorState.read().
    at getActiveEditorState (Lexical.dev.js:7663:13)
    at Object.$getRoot (Lexical.dev.js:802:26)
    at $findMatchingParent (LexicalUtils.dev.js:497:27)
    at eval (index.js:55:134)
    at eval (realm.js:206:55)
    at Set.forEach (<anonymous>)
    at eval (realm.js:206:29)
    at SetMap.use (realm.js:38:7)
    at pubIn (realm.js:205:23)
    at Object.pubKeys (realm.js:438:5)
    at handleSelectionChange (index.js:127:9)
    at eval (index.js:264:9)
    at readEditorState (Lexical.dev.js:7749:12)
    at EditorState.read (Lexical.dev.js:8873:12)
    at eval (index.js:263:19)
    at triggerListeners (Lexical.dev.js:7954:20)
    at commitPendingUpdates (Lexical.dev.js:7914:3)
    at eval (Lexical.dev.js:8150:9)`

**Comment by petyosi** [comment]
Should not be Next 14, I'm using it as well. Can you replicate the error by forking the [nextjs sample repo](https://github.com/mdx-editor/mdx-editor-in-next)? Might be something specific that I have not taken into account.

**Comment by fredachang** [comment]
hey @petyosi I couldn't reproduce the issue 1 to 1 in the next.js fork because our app has a pretty complicated folder structure but I think I have found the cause. We put the markdown editor in our `packages > design` and were importing it into `app` and getting the `unable to find active editor state issue` error. 

Two fixes I tried and their results: 
1. importing `lexical` as a peer dependency next to mdx editor, even if lexical is not directly referenced anywhere. I got this idea from this [thread](https://github.com/facebook/lexical/issues/4055). This made the above error went away, but somehow the lists toggle stopped responding. 
2. To resolve the above, I got the sense that lexical states are influenced by where mdx is located/how its imported. I moved the mdx editor into the same folder in `app` where it is imported, and all our plug-ins under `1.13.4` seem to be working as expected now. In this scenario I can get rid of the lexical peer dependency and things still work. 

I am not sure what changed between `1.9.0` and `1.13.4` but from experimentation it seems like the mdx location is now important and functionality breaks if its imported from a diff app / package in a multi-app structure.

**Comment by petyosi** [comment]
I'm afraid that I can't help you without seeing what goes on in your project - none of the above rings a bell. 

If you and your company has such practice, I'm happy to troubleshoot and help you with your setup as a consulting service - it's something that I offer for my other open source projects as well. If you want to consider this, you can contact me over an email.

**Comment by fredachang** [comment]
No worries. If it means we have to move its location that's not too big of a deal for us. Just wanted to provide more context in my response above to help anyone else who may be running into similar issues. You've been extremely helpful so far and will reach out if anything in the realm of consulting services are required.
