### ISSUE TITLE
How to track if the editor is in focus?

### ISSUE THREAD

**Issue by darioscattolini** [mdx-editor/editor#237]
I'm building a custom toolbar for the editor [following the approach suggested here](https://github.com/mdx-editor/editor/issues/187). 

I have managed to get my custom buttons working, but I need the toolbar to be displayed only if the user has focused on an editor. I have many different editors on the screen I'm building, so this would help me save space by removing toolbars in non-focused editors.

I have managed to get this feature partially working, and even to bypass the momentaneous loss of focus due to users clicking on a toolbar button. This is the way i handle it in my `<Toolbar />` component:

```ts
const editorInFocus = corePluginHooks.useRealmContext().getKeyValue('inFocus');
const editorInFocusRef = useRef(editorInFocus);
const [toolbarVisible, setToolbarVisible] = useState(false);

useEffect(() => {
  editorInFocusRef.current = editorInFocus;
}, [editorInFocus]);

useEffect(() => {
  if (!editorInFocus) {
    setTimeout(() => {
      if (!editorInFocusRef.current) setToolbarVisible(false);
    }, 100)
  } else {
    setToolbarVisible(true);
  }
}, [editorInFocus]);
```

This is working almost perfectly. However, the way I have found to obtain the value for `editorInFocus` is not so accurate, especially when the editor component is initially mounted. It fails to recognize the first time I focus on an editor, and it doesn't update the `editorInFocus` value until I click another editor and go back to the editor I want to use. 

Do you know the reason for this, if there is some way to prevent this or some other way to get the focus state of the editor? [I have also revised this issue but I'm not sure if this is what I need](https://github.com/mdx-editor/editor/issues/87).

**Comment by petyosi** [comment]
If I understand you correctly [something like this](https://codesandbox.io/p/sandbox/mdx-editor-base-forked-9vh8fs) should work. Of course, you need to style the toolbar, etc. 

Most of the toolbar commands will return the focus to the editor. Perhaps you might be challenged with the dropdowns, though.

**Comment by darioscattolini** [comment]
This has done the trick: 

```ts
 const [inFocus] = corePluginHooks.useEmitterValues("inFocus");
```

Thanks!

**Comment by tihomir-kit** [comment]
Sorry to resurrect this, but where exactly is `corePluginHooks` coming from?

![image](https://github.com/mdx-editor/editor/assets/535842/3d82be94-0967-4051-b72d-cf3d37ac9b65)

The codesandbox sample is also missing that detail. 

Thanks!

**Comment by tihomir-kit** [comment]
Hi, I left a comment earlier and then thought I made a mistake and had it figured out so I deleted it. But now I realize I'm still struggling with this.

Am I missing something or does `corePluginHooks` not exist in `@mdxeditor/editor` any longer? How can I access `inFocus` now?

Thanks!

**Comment by petyosi** [comment]
@tihomir-kit that's an example made with the previous major version, there's a migration guide in the docs. In that case, you can get the focus state with something like `useCellValue(inFocus$)`, with both the function and the variable being importable from `@mdxeditor/editor`.

**Comment by djm158** [comment]
hi @petyosi I'm trying to style the editor based on the focus state. I want to apply a border/outline to the entire component when the editor has focus. However when I call `useCellValue(inFocus$)` from the parent of `<MDXEditor />` I get an error

```
Uncaught Error: useRealm must be used within a RealmContextProvider
```

Do you have any thoughts on how to accomplish this?

**Comment by petyosi** [comment]
@djm158 the `:focus-within` [CSS pseudo-class works](https://developer.mozilla.org/en-US/docs/Web/CSS/:focus-within) for the specific case you describe. 

If you want to do something more complex, you can lift state from the editor component through a plugin, [like this](https://codesandbox.io/p/devbox/mdx-editor-base-3-forked-mfpr9l?file=%2Fsrc%2FApp.tsx%3A25%2C15&workspaceId=ws_5xmhxQ6gmw1x8bUXrqEq26).
