### ISSUE TITLE
Cannot insert an image in a table cell

### ISSUE THREAD

**Issue by dferrerobios** [mdx-editor/editor#238]
I don't know if it is a bug or just that this option has not been developed but you cannot insert an image in a table.

![image](https://github.com/mdx-editor/editor/assets/117347147/0ab97741-d205-4ee7-82aa-7d594b228438)

When you try to load the image it imports it under the table as you can see in the image.

**Comment by petyosi** [comment]
Good point. It's not yet done, but I think it's easy to be done. Images now only go to the root editor.

**Comment by dferrerobios** [comment]
Thank you very much for your comment, I appreciate it. I will check if I can propose you a PR with this functionality.
