### ISSUE TITLE
Link popup is being styled improperly and not overrideable

### ISSUE THREAD

**Issue by gitisz** [mdx-editor/editor#239]
The linkDialogue does not appear properly in a Material Theme layout, and appears to be positioned using javascript code that sets the element.style.  How can the position of the linkDialog be centered in page the same way as the image dialogue?

![image](https://github.com/mdx-editor/editor/assets/4492953/72a4140c-2bf5-4597-83d0-eb759ba70191)

**Comment by petyosi** [comment]
These are two different implementations. The link dialog acts as a contextual popover, positioning itself relatively to the link text. The image input form is just a regular centered dialog. 

My wild guess is that the Material Theme layout does something wild like html/body margins or re-positioning, but I can't be sure. If you can replicate the problem (use [this sandbox as a starting point](https://codesandbox.io/p/sandbox/mdx-editor-base-q8s7zr?file=/public/index.html)), I might be able to help you.

**Comment by petyosi** [comment]
@gitisz let me know if there's anything doable here.
