### ISSUE TITLE
Line breaks passed through markdown prop are not preseved

### ISSUE THREAD

**Issue by nobu-sh** [mdx-editor/editor#244]
```tsx
<ForwardRefEditor markdown={`hello\n\nworld`} />
```
When editing in the editor line breaks are inserted in the dom as `<p><br /></p>` but when the editor first renders with markdown passed to markdown prop newlines are omitted.

**Comment by petyosi** [comment]
Not sure I understand what you mean here. Two line breaks are considered a paragraph. In the editor, enter creates a new paragraph, and shift+enter creates line break. Can you fork [this sandbox](https://codesandbox.io/p/sandbox/mdx-editor-base-forked-6mrs68?file=/src/App.tsx:16,9) and demonstrate what's the malfunction?

**Comment by forhappy** [comment]
In my experiment I used the following code snippet to import markdown content to the current selection element node:

```
editor.update(() => {
  $convertFromMarkdownString(markdown, TRANSFORMERS, elementNode);
});

```

However the observation is when I had the markdown like: 

```
# head 1 

- list 1
- list 2
- list 3
```

The markdown can be parsed and inserted to the selection point.

However when I change to source code view I can see the markdown is:

```
# head 1 - list 1
- list 2
- list 3
```

Thus when I change back to rich text mode I get 

# Head 1 - list 1 

As the new heading, which means the blank line in the original markdown content was removed.

**Comment by forhappy** [comment]
> In my experiment I used the following code snippet to import markdown content to the current selection element node:
> 
> ```
> editor.update(() => {
>   $convertFromMarkdownString(markdown, TRANSFORMERS, elementNode);
> });
> 
> ```
> 
> However the observation is when I had the markdown like: 
> 
> ```
> # head 1 
> 
> - list 1
> - list 2
> - list 3
> ```
> 
> The markdown can be parsed and inserted to the selection point.
> 
> However when I change to source code view I can see the markdown is:
> 
> ```
> # head 1 - list 1
> - list 2
> - list 3
> ```
> 
> Thus when I change back to rich text mode I get 
> 
> # Head 1 - list 1 
> 
> As the new heading, which means the blank line in the original markdown content was removed.
> 
> 

I managed to make my use case work perfectly, the issue was when I use `convertFromMarkdownString` to convert markdown to lexical states, the element node must be a block node, e.g. a custom node baking by a div. Now I can programmatically insert markdown content into the current selection point. This is a great library, you can use it to do anything while the content of the editor  would be as lightweight as possible and more importantly markdown compatible. thanks the author @petyosi.

**Comment by petyosi** [comment]
@forhappy this sounds like a proper feature to me, happy to accept a contribution of such kind. Thank you!

**Comment by forhappy** [comment]
Let me clean up my code base and raise a PR this week, thank you @petyosi

**Comment by petyosi** [comment]
@paschaldev https://github.com/mdx-editor/editor/pull/294
