### ISSUE TITLE
Insert/edit link inconsistencies with title

### ISSUE THREAD

**Issue by sieem** [mdx-editor/editor#245]
We noticed that inserting and editing a link with regards to the title field is inconsistent. Let's try to describe all the scenario's we encountered:

1. Clicking on "Create link" in the toolbar when having no text selected, the title field controls both the visible text as well as the title attribute.
2. Clicking on "Create link" in the toolbar when you have text selected, the title field only controls the title attribute.
3. Clicking on "Create link" in the toolbar when you have a link selected, the title field is filled in and only controls the title attribute.
4. Clicking on "Edit link URL" in the popup when you have a link selected, the title field isn't filled in and doesn't control anything.

What we expected was that the title field would control the visible text, since we don't see the value in defining a title attribute.

In scenario 2, we would expect the title field to be filled in with the text you selected.
In scenario 4, we would expect the title field to be filled in with the visible text and editing that would result the visible text to be changed.

But at the very least, in scenario 4, changing the title field would change the title attribute. As for now, it doesn't seem to impact anything.

**Comment by petyosi** [comment]
Thanks for reporting that. Perhaps Scenario 1 confuses you. When there's no text selected, the editor uses the title field in order to create *something*, otherwise there would be an invisible link inserted. 
2) I don't believe that what you suggest is useful. The title field is meant to provide additional context on the link, not repeat the text it contains. 
4) The edit button is indeed working in a weird way, the title is not taken. This is a bug, I will look into it.

**Comment by sieem** [comment]
Thanks for the quick response. I start to understand the logic behind the title field now. Maybe it would be useful to have a "text" field? This way there is no need to borrow the data from the title field when creating a link, which would clear out the confusion.

**Comment by petyosi** [comment]
That's a logical option, my concern with it is that the text field can't pick the eventual rich text formatting of the link contents (well, it can, but it's quite complex), so creating a link over a formatted portion of the text can eventually conflict with the formatting.

**Comment by sieem** [comment]
I wouldn't expect the rich text formatting to be visible in the link dialog. But I still see the complexity.
In Slack they solved it like this: you can add a link over formatted text, it would show the unformatted text in the text field, when that is not edited, it would keep the formatting. Once you edit the text field, it removes all formatting. However, in Slack you have less formatting option as here, so it might not be a solid solution here.

After playing a bit more with MDXEditor, it's just the filling in of the title tag in scenario 4 that fails. It controls the title field after all. I guess filling that in would already alleviate some confusion.
