### ISSUE TITLE
How to insert texts or pics into markdown?

### ISSUE THREAD

**Issue by wengxiaoxiong** [mdx-editor/editor#246]
I want to implement a feature where, once a button is pushed, the editor automatically inserts a picture or a text, which may be generated by AI. However, I'm still not sure how to achieve this

**Comment by petyosi** [comment]
This is too broad of a question, to be honest. The short answer is that you need to use the Lexical API for content manipulation - node insertion, node removal, etc.

**Comment by wengxiaoxiong** [comment]
Thank you for your answer. If possible, could you provide a demo?
