### ISSUE TITLE
How to make the tool bar under the text area?

### ISSUE THREAD

**Issue by hereAlexT** [mdx-editor/editor#248]
Hi, I am trying to make the toolbar stay under the textarea.

I tried to adjust CSS, for example:
```css
._toolbarRoot_utjas_145 {
  /* border: var(--spacing-px) solid var(--baseBorder); */
  z-index: 1;
  display: flex;
  flex-direction: row;
  gap: var(--spacing-1);
  border-radius: var(--radius-medium);
  padding: var(--spacing-1_5);
  align-items: center;
  overflow-x: auto;
  position: static; /* Changed from sticky to static */
  /* Removed top: 0; */
  /* background-color: var(--baseBg); */
  width: inherit;
}
```

but they are not working at all.

I wonder how to make the toolbar stay under the textarea?

Thanks!

**Comment by hereAlexT** [comment]
What's more, is it possible to implement customised buttons outside the MDXEditor? e.g. A bold button to trigger the built-in bold function. This is for style purposes, I am creating an editor like Twitter's.
![image](https://github.com/mdx-editor/editor/assets/79433869/221d84b1-6203-4ae2-8b1d-bb86d99adc7c)

I tried to pass the submit button to the `toolbarContents` with a state variable `content`. However, it looks like the context is changed so the button is not functional at all.

Thanks!

**Comment by petyosi** [comment]
1) You can probably use something like reversed flexbox to move the toolbar below, but I have not tried that. 
2) Yes, custom buttons are supported, you can check how the built-in ones are implemented in the editor source code. I'm not sure what you mean with the state variable part, though. You can [use a sandbox](https://codesandbox.io/p/sandbox/mdx-editor-base-q8s7zr) to show what the problem is.

**Comment by hereAlexT** [comment]
Thanks!
1. the column-reverse works, just need to add `._editorWrapper_utjas_138` to a `column-reverse`
```css
._editorWrapper_utjas_138 {
  display: flex;
  flex-direction: column-reverse;
}
```

2. I have created a [sandbox](https://codesandbox.io/p/sandbox/mdx-editor-base-forked-jr6t4x?file=%2Fsrc%2FApp.tsx%3A27%2C11&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clqap1nxq00063b6k0dt26gqg%2522%252C%2522sizes%2522%253A%255B100%252C0%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clqap1nxq00023b6kdockh9ku%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clqap1nxq00033b6kucebrr0d%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clqap1nxq00053b6k0nb1ssqz%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clqap1nxq00023b6kdockh9ku%2522%253A%257B%2522id%2522%253A%2522clqap1nxq00023b6kdockh9ku%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clqapgtpo00023b6lz3mrgrzf%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A27%252C%2522startColumn%2522%253A11%252C%2522endLineNumber%2522%253A27%252C%2522endColumn%2522%253A11%257D%255D%252C%2522filepath%2522%253A%2522%252Fsrc%252FApp.tsx%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522activeTabId%2522%253A%2522clqapgtpo00023b6lz3mrgrzf%2522%257D%252C%2522clqap1nxq00053b6k0nb1ssqz%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clqap1nxq00043b6km057nomj%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522clqap1nxq00053b6k0nb1ssqz%2522%252C%2522activeTabId%2522%253A%2522clqap1nxq00043b6km057nomj%2522%257D%252C%2522clqap1nxq00033b6kucebrr0d%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522clqap1nxq00033b6kucebrr0d%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Afalse%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

here are the steps to reproduce it

1. Open console
2. type something in the editor
3. Click the Submit button on the toolbar
4. You'll find that the `content` is not empty. but when you click the `submit` button, you'll find the `content` became empty.

![iScreen Shoter - Google Chrome - 231218202612](https://github.com/mdx-editor/editor/assets/79433869/d2fdedd9-6ed5-4507-9ec5-385c1a3e9d19)

**Comment by petyosi** [comment]
Ah, I see what you mean. The toolbar contents are not re-rendered, so changes in their scope are not reflected. 

I think this is easy to fix in the toolbar plugin, but in the meantime you can work around by moving the button in a separate component and using context to communicate with it (I know, not the most elegant way).

**Comment by andyfelder16** [comment]
> I think this is easy to fix in the toolbar plugin, but in the meantime you can work around by moving the button in a separate component and using context to communicate with it (I know, not the most elegant way).

Hi, i want to implement something that i think this reply helps me. I'm working on a project with a canvas where nodes can be text nodes (md editors) and each node has its toolbar (with things about the node). I want to integrate to my actual node toolbar that if its a text node to add some features to my actual toolbar (Bold, italic, etc...). Is there a way to communicate with the editor but not using the Toolbar plugin that already exists? Because I want to add it to the one that i already have of my nodes. If there are any examples would be really useful. 

Thanks!

**Comment by petyosi** [comment]
> > I think this is easy to fix in the toolbar plugin, but in the meantime you can work around by moving the button in a separate component and using context to communicate with it (I know, not the most elegant way).
> 
> Hi, i want to implement something that i think this reply helps me. I'm working on a project with a canvas where nodes can be text nodes (md editors) and each node has its toolbar (with things about the node). I want to integrate to my actual node toolbar that if its a text node to add some features to my actual toolbar (Bold, italic, etc...). Is there a way to communicate with the editor but not using the Toolbar plugin that already exists? Because I want to add it to the one that i already have of my nodes. If there are any examples would be really useful.
> 
> Thanks!

The editor exposes an API through hooks that are dependent on its context - you can take a look at the toolbar [components as an example](https://github.com/mdx-editor/editor/blob/main/src/plugins/toolbar/components/BoldItalicUnderlineToggles.tsx). As long as your toolbar is injected in the editor (take a look at the current toolbar source for an example), you should be able to replicate its behavior quite easily.
