### ISSUE TITLE
Guideline to create customized plugin

### ISSUE THREAD

**Issue by hereAlexT** [mdx-editor/editor#249]
Hey, 

I need to use `tag` in my app. It needs to render a tag and callback some functions when it detects a tag such as `#tag1`, or `#tag_2`.

I think I need to implement a custom plugin. I looked around the source code but haven't found where to start. Would you like to provide a guideline about how to create a custom plugin? 

I'm really happy to contribute to docs or submit a PR after I figure it out.

**Comment by petyosi** [comment]
Such a guide is indeed necessary, but quite vast in its nature. I do want to take my time on adding more content to the documentation; However, some things actually go a bit beyond the functionality of the editor itself. Let me give you an outline:

- First, if you need to either find or create a **mdast plugin** that recognizes the syntax you intend to use. You can start from the [mdast repo](https://github.com/syntax-tree/mdast-util-from-markdown?tab=readme-ov-file#list-of-extensions). 
- Next, you should create an mdxeditor plugin  that would register the plugin from above, and use it as a visitor
- Next, you will need to build a custom Lexical node (my guess would be a decorator node), along with an editor (React component) that meets your requirements. You might find something similar in the lexical playground. 
- Finally, you will need something that serializes the lexical node back to a mdast node, along with the right mdast plugin (*-to-markdown) that will convert your structure back to the right markdown. 

This sounds like a lot, but (I might be missing something here, though) you're trying to add an extension to the markdown language, which is makes the first and last step necessary.

Hope this helps.
