### ISSUE TITLE
TS errors with Vite

### ISSUE THREAD

**Issue by SeveHo** [mdx-editor/editor#250]
Bundling with TS fails with ~60 errors due to type problems with the modules **lexical**, **mdast-util-from-markdown**, **@stitches/core**. This problem only occurs when setting `"skipLibCheck": false`. I checked your example repo and it's the same there.

 Disabling the check is not good, so do you see any quick fix for this issue? 

[Here is a reproduction of the issue.](https://codesandbox.io/p/devbox/vite-react-ts-forked-4n52cw?file=%2Ftsconfig.json%3A7%2C5-7%2C27&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clqdk04k400093b6hqnh7ej6y%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clqdk04k400023b6h6h1mg9it%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clqdk04k400063b6hpzfiybb8%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clqdk04k400083b6hhj3y6rui%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B47.597146611601275%252C52.402853388398725%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clqdk04k400023b6h6h1mg9it%2522%253A%257B%2522id%2522%253A%2522clqdk04k400023b6h6h1mg9it%2522%252C%2522activeTabId%2522%253A%2522clqdks0xw03vs3b6hgeit08fo%2522%252C%2522tabs%2522%253A%255B%257B%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252F.codesandbox%252Ftasks.json%2522%252C%2522id%2522%253A%2522clqdk6h0t01cp3b6hawc0jmds%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522id%2522%253A%2522clqdks0xw03vs3b6hgeit08fo%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A7%252C%2522startColumn%2522%253A5%252C%2522endLineNumber%2522%253A7%252C%2522endColumn%2522%253A27%257D%255D%252C%2522filepath%2522%253A%2522%252Ftsconfig.json%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%257D%252C%2522clqdk04k400083b6hhj3y6rui%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clqdk04k400073b6hc3d6hoxr%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_PORT%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522port%2522%253A3000%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522clqdk04k400083b6hhj3y6rui%2522%252C%2522activeTabId%2522%253A%2522clqdk04k400073b6hc3d6hoxr%2522%257D%252C%2522clqdk04k400063b6hpzfiybb8%2522%253A%257B%2522id%2522%253A%2522clqdk04k400063b6hpzfiybb8%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clqdk04k400033b6h2irctfwy%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522dev%2522%257D%252C%257B%2522id%2522%253A%2522clqdk04k400043b6hp3no29y9%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522build%2522%257D%252C%257B%2522id%2522%253A%2522clqdk04k400053b6hyc0npk6k%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522serve%2522%257D%255D%252C%2522activeTabId%2522%253A%2522clqdk04k400033b6h2irctfwy%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

**Comment by petyosi** [comment]
I would not consider disabling this check to be not good. If anything, it's slows down your ts build considerably. If I remember correctly, the default setting for a new vite project is `skipLibCheck: true`. 

As far as I can tell, there are several errors in there that are fixable in the mdx editor source code itself (e.g. imports which some how end up being unresolvable). I will see what can be done there.

**Comment by petyosi** [comment]
I tried changing one inference in the code, but unfortunately, it did not help. The generated code still pulls a type from the '/lib' directory, which, for some reason, is not recognized by the TypeScript configuration. Which is strange, given that there's an index.d.ts in there. 

However, even if I fix that, there are still plenty of things in the dependencies (Lexical, sandpack, etc), that this config does not like. I'm not sure what's to be done in this case, apart from toggling the flag. Happy to accept a contribution on the matters.
