### ISSUE TITLE
How customize ListsToogle without check list?

### ISSUE THREAD

**Issue by SeungyeopShin** [mdx-editor/editor#251]
Hi,

I want to insert ListsToggle without check list.

So I tried to make own ListToggle component refer to original [ListsToggle.tsx](https://github.com/mdx-editor/editor/blob/v1.13.5/src/plugins/toolbar/components/ListsToggle.tsx)

```
import React from 'react'
import { SingleChoiceToggleGroup, listsPluginHooks } from '@mdxeditor/editor'

/**
 * A toolbar toggle that allows the user to toggle between bulleted and numbered lists.
 * Pressing the selected button will convert the current list to the other type. Pressing it again will remove the list.
 * For this button to work, you need to have the `listsPlugin` plugin enabled.
 */
export const ListsToggle: React.FC = () => {
  const [currentListType] = listsPluginHooks.useEmitterValues('currentListType')
  const applyListType = listsPluginHooks.usePublisher('applyListType')
  const [iconComponentFor] = listsPluginHooks.useEmitterValues('iconComponentFor')
  return (
    <SingleChoiceToggleGroup
      value={currentListType || ''}
      items={[
        {
          title: 'Bulleted list',
          contents: iconComponentFor('format_list_bulleted'),
          value: 'bullet'
        },
        {
          title: 'Numbered list',
          contents: iconComponentFor('format_list_numbered'),
          value: 'number'
        }
      ]}
      onChange={applyListType}
    />
  )
}

```

But I encountered an error in runtime. Bundle work was fine.
<img width="541" alt="image" src="https://github.com/mdx-editor/editor/assets/109323024/ed20dd1b-f805-422c-bc2c-e267b8e2fd10">

How could I customize ListsToggles?

**Comment by petyosi** [comment]
Are you using ListsToggle within the toolbar? Your error looks like your component is outside of the mdx editor state provider.

**Comment by SeungyeopShin** [comment]
Sorry, I resolved this issue using written way.
Thanks reply.

**Comment by SeungyeopShin** [comment]
As I mentioned, I worte own ListsToggle.tsx in my project.
And I import own ListToggle `import {ListToggle} from './ListToggle'` instaed of `import {ListToggle} from '@mdxeditor/editor'`
