### ISSUE TITLE
Feature: Adding contributors section to the README.md file. 

### ISSUE THREAD

**Issue by kalyani2003** [mdx-editor/editor#254]
There is no Contributors section in readme file .
As we know Contributions are what make the open-source community such an amazing place to learn, inspire, and create.
The Contributors section in a README.md file is important as it acknowledges and gives credit to those who have contributed to a project, fosters community and collaboration, adds transparency and accountability, and helps document the project's history for current and future maintainers. It also serves as a form of recognition, motivating contributors to continue their efforts.
![Uploading contributors.jpg…]()

**Comment by kalyani2003** [comment]
@petyosi  Kindly assign me this issue, I want to work on it. Thank You!

**Comment by petyosi** [comment]
Thanks, but I will pass on your offer. I appreciate contributions, but the quality of those motivated by "I want to become a contributor and have my name listed there" is usually horrible.
