### ISSUE TITLE
Issue with Checklist Markdown Conversion in Editor

### ISSUE THREAD

**Issue by ventsarevich** [mdx-editor/editor#255]
i there,

I'm encountering a problem with the checklist format in mdxEditor.
 When I use checklists in the editor, the resulting markdown appears identical to a bullet list format, which is not as expected. Attached is an image illustrating this issue.
 <img width="932" alt="image" src="https://github.com/mdx-editor/editor/assets/31828081/90b3bc83-aafa-48df-80b7-5989db680150">
 
Based on the documentation at [mdxEditor Markdown Processing](https://mdxeditor.dev/editor/docs/markdown-processing), it seems that the conversion from lexical tree to markdown is handled by the 'mdast-util-to-markdown' library. To address the checklist formatting, I integrated the 'mdast-util-gfm-task-list-item' extension, which is designed to convert checklist lexical trees to markdown.

After installing and extending the editor with this extension, there was no change in the formatting. Subsequently, I directly used the 'mdast-util-to-markdown' with the aforementioned extension on a sample lexical tree, and the formatting was correct, with the list appearing as expected.

There is lexical tree converstion example:

```
  const options = {
    extensions: [gfmTaskListItemToMarkdown()],
  };

  const mdast = {
    type: 'root',
    children: [
      {
        type: 'list',
        ordered: false,
        start: null,
        spread: false,
        children: [
          {
            type: 'listItem',
            checked: true,
            children: [
              {
                type: 'paragraph',
                children: [
                  {
                    type: 'text',
                    value: 'Task 1 completed',
                  },
                ],
              },
            ],
          },
          {
            type: 'listItem',
            checked: false,
            children: [
              {
                type: 'paragraph',
                children: [
                  {
                    type: 'text',
                    value: 'Task 2 pending',
                  },
                ],
              },
            ],
          },
        ],
      },
    ],
  };

  const markdown = toMarkdown(mdast, options);
  console.log(markdown);
  // Output: 
  // * [x] Task 1 completed
  // * [ ] Task 2 pending
```

To resolve this issue, I need assistance with the following:

Can you confirm if the correct lexical tree is being generated by mdxEditor for task lists?
Are there any options or settings within mdxEditor to adjust list formatting at the lexical tree level or during the tree conversion step?
Your guidance on these points would be greatly appreciated to help resolve this formatting issue.

Thank you for your assistance.

**Comment by forhappy** [comment]
I observed this issue before and had a debug when check list was implemented, when mdxeditor export to markdown it uses the lexical node `getChecked` to determine if the least is a check list or not, you can see the lexical list item visitor implementation here https://github.com/mdx-editor/editor/blob/main/src/plugins/lists/LexicalListItemVisitor.ts#L19

The problem behind is if the user doesn't clicked the checkbox once, the lexical node `getChecked` is undefined, under which case mdxeditor will convert to normal list, if a user clicked the checkbox once or more than more once, lexical node `getChecked` is true or false and mdxeditor can correctly convert to checklist in mdast.

I am not sure if it's a bug in lexical, you can help dive deeper if you're interested in this issue.

**Comment by ventsarevich** [comment]
When a checklist is inserted by default, it appears correctly.

I've observed that the 'gfmTaskListItemFromMarkdown' method from the 'mdast-util-gfm-task-list-item' extension correctly converts markdown to a Lexical list, indicating that the Lexical checklist and its plugin are functioning properly.

However, I suspect the problem might lie in the process of inserting ListNode into the page. It seems that this step might not be working as intended, leading to the formatting issue.

Maybe some necessary fields are filled incorrectly or smth.

Unfortunately, I'm not an expert in lexical and realm and couldn't dive deeper.

**Comment by ventsarevich** [comment]
Ok! I see an issue.

For Lexical it doesn't matter if ListItemNode checked field is false or undefined. It renders a checklist based on parent type. 

It's more likely a problem of 'mdast-util-gfm-task-list-item' plugin because it doesn't check the type of parent and just convert the lexical tree to markdown based on List Item elements, not the type of Parent List Node.

**Comment by petyosi** [comment]
I wonder if the markdown to AST can't explicitly force the isChecked to false. Will take a look...

**Comment by petyosi** [comment]
@forhappy @ventsarevich  I think I got that right, please check the latest release.

**Comment by gopal-virtual** [comment]
The issue still persist on 1.14.3.

**Comment by ventsarevich** [comment]
I have checked. I agree with @gopal-virtual, the issue still reproduces. Nothing changes, the resulting markdown still contains incorrect format of the check list.

**Comment by gegen** [comment]
Hey, I still get this Issue in version 3.21.2. It is reproducible on the demo.
I'm loving this editor and I'd thus appreciate help with this issue :)

![Image](https://github.com/user-attachments/assets/4a9d8122-8a01-41db-87e1-5fcaefd7f7e3)

![Image](https://github.com/user-attachments/assets/f493463f-f104-4c69-b128-5405673eb9be)

**Comment by petyosi** [comment]
@gegen I'm reopening this in a new issue.
