### ISSUE TITLE
Missing caret on empty editor

### ISSUE THREAD

**Issue by makkeu** [mdx-editor/editor#257]
I have a really weird issue on a project I'm working on, but can't reproduce it in a sandbox. I'm quite sure that this isn't strictly an issue with this editor, more like some weird safari rendering bug.

Basically, if the editor is empty, caret is missing, but as soon as I start typing text, it appears. The issue happens on Safari, no problems with Chrome. This might be some kind of safari rendering issue. The triggering element seems to be linkDialogAnchor with z-index: -1. If I remove linkDialogPlugin or set the z-index to 0 (causing another bug), caret appears. I don't have any idea, why it would cause the issue, since it is invisible, zero width element. To make it even more confusing, if I add a border to the main editor element, it also fixes the issue but brings an another hard to reproducible glitch in safari 🤯.

Editor is used inside shadcn-ui dialog (radix), and I have set z-index for it to fix popover menus being invisible. Removing that z-index from editor component also fixes the issue, but then the popover dialogs stops working. I'm out of ideas how to work around this issue. This is driving me nuts :)  I'm still trying to reproduce this with a sandbox or simpler project.

Any ideas?

**Comment by petyosi** [comment]
I've seen the cursor missing due to a border or an outline of some sort, but it happened in Chrome. Could be due to something like this. Try to toggle those on/off and see if it won't appear. At any case, it's purely a visual thing when I managed to reproduce it, not an actual missing cursor.

**Comment by petyosi** [comment]
@makkeu what happened here? Let me know if this needs any work on the editor's side.

**Comment by makkeu** [comment]
I haven't had time to debug that much. It is still an issue, but I have only been able to reproduce it in Safari.

It might have something to do with the placeholder element. I remember playing with web console and modifying styles on fly. Setting `background: white` to _contentEditable_utjas_351 element brings partially visible cursor, but placeholder element goes on top of it. Setting `background: transparent` to the placeholder element finally brings the whole cursor visible. That would also explain why cursor becomes visible after typing one character => placeholder element is removed from dom. If I manually remove the placeholder element in web console, cursor is still invisible without setting the background color.

I can't figure out, why background color fixes the issue (or removing z-index, or adding a border), so I still think this is some kind of safari rendering issue. `z-index` might be the original source for the issue, since it won't occur in simple test project.

I'll update here, if I find a proper fix or a reliable way to reproduce it.
