### ISSUE TITLE
Help needed - extending with variable tags

### ISSUE THREAD

**Issue by amitav13** [mdx-editor/editor#260]
Hi!
These are my requirements:
1. Nextjs frontend with editor, with support for variable tags like this  - https://www.qualified.com/university/articles/building-advanced-experiences/using-variable-tags-to-personalize-your-experiences?from_search=135662986
2. Save the markdown in a db - string should be fine here
3. Render the markdown in a different React app, that is also built by us

Using this editor for 1 and rendering in 3 using something like [this](https://github.com/remarkjs/react-markdown?tab=readme-ov-file) looks simple enough. Adding variable tags into the editor is what I'm not sure of how to execute.

What we want to do within the editor is: 
1. Have the ability to add in a fixed set of variables, with the ability to add in fallbacks. Something like `Hi there {{ name | "John Doe" }}!`. Flexible on the syntax for this.
2. Dynamically find and replace instances of this on our backend - swap out the name to have a final markdown string like `Hi there Jane!`. 

Going through the docs, is [directives](https://mdxeditor.dev/editor/docs/custom-directive-editors) the right way to accomplish this? Not sure if the processing can also be done easier on the final react app easier using [remark-directive](https://github.com/remarkjs/remark-directive).

Thanks for the help and the great editor!

**Comment by petyosi** [comment]
Yes, you can certainly use either directives or jsx elements for the purpose. As far as I know, the syntax you've given as an example is not one that's supported by markdown or any of its extensions, though.

**Comment by amitav13** [comment]
Found this after some digging - https://github.com/mrzmmr/remark-variables?tab=readme-ov-file. Seems to be exactly what I need but out of date. Would you happen to know of any similar plugin?
