### ISSUE TITLE
Add complete code examples in the docs

### ISSUE THREAD

**Issue by EssamWisam** [mdx-editor/editor#261]
This seems to be the best markdown editor on the internet. At least that's what I thought when I checked the live demo and learned that it also supports custom functionality.

I think it would be quite nice to have complete code examples available. For instance, many people including me may be just interested in the code corresponding to the example shown in the live demo as the starting point (e.g., for popular frameworks such as React and Next). I have been trying to reconstruct it but even that isn't so trivial (e.g., can't instantly render markdown while maintaining cursor position...). 

Thanks for this great effort.

**Comment by petyosi** [comment]
Thanks, a lot of the credit goes to the underlying Lexical platform.  

Writing more docs is an ongoing effort (in fact, I'm working on something that will let me write docs for the editor in the editor). I'm very happy to accept contributions in that regard. 

To help with the live demo, I've opened the repository of the site [itself - take a look here](https://github.com/mdx-editor/site/blob/master/app/editor/demo/live-demo.tsx).

**Comment by petyosi** [comment]
@EssamWisam the scope of that issue is large and generic. I'm closing it - happy to accept contributions on the matter.
