### ISSUE TITLE
Full directive example in the docs

### ISSUE THREAD

**Issue by EssamWisam** [mdx-editor/editor#262]
While reading the [documentation for directives](https://mdxeditor.dev/editor/docs/custom-directive-editors), I noticed that the YouTube example (adding a new button in the toolbar) does not include the code to construct the directive descriptor itself. 

I was able to successfully make a custom editor that processes text  with `NestedLexicalEditor` but I was unable to integrate that with a toolbar icon. It would be helpful if either:
- The YouTube example's directive descriptor is shown in the docs 
- An example for a custom toolbar button that simply renders given text in the implemented directive descriptor  is shown in the docs 

I tried to look at the source code (e.g., `ChangeAdmonitionType.tsx`) but it seems to be implemented differently than what the docs depict.

Thanks for this nice package.

**Comment by petyosi** [comment]
PRs welcome. https://github.com/mdx-editor/editor/issues/261#issuecomment-1876779142.
