### ISSUE TITLE
Functionality to process selected text

### ISSUE THREAD

**Issue by EssamWisam** [mdx-editor/editor#264]
I assume that the package does not currently support applying arbitrary transformations to text using JavaScript (e.g., converting selected text to uppercase or changing words in a sentence or even adding a custom style to text with JS). I think it would be quite nice to have this functionality; I was only able to achieve a poor approximate of this using directives.

Thanks again for this nice package.

**Comment by petyosi** [comment]
I'm not sure I understand what have in mind - perhaps #92? Alternatively, if you are looking for runtime text manipulation in the editor environment, then this is doable [through the Lexical API](https://lexical.dev/docs/api/modules/lexical).

Let me know if I got that right.

**Comment by EssamWisam** [comment]
Yes, you got it right, runtime text manipulation with JS functions. I haven't use Lexical before, let me know if you are aware of the part of their API that could help achieve this functionality; `@lexical/selection` does not seem to directly provide that. #92 is partially relevant.

Thank you.

**Comment by petyosi** [comment]
I usually manage to find answers to my problems in the Lexical Discord channel - their API is quite large, and sometimes examples are missing. The playground source code is very instructive, though. A few pointers that might be helpful - the core API has stuff like $getTextContent, $createTextNode, and $insertNodes.

**Comment by EssamWisam** [comment]
Speaking of their playground, do you plan to bring more of its features as external plugins to this package (e.g., comments)? As far as I understand they are implemented from scratch in the playground.

**Comment by petyosi** [comment]
The straightforward answer is no, not directly. My focus is to make the editor work great with the built-in markdown syntax, support extensibility for MarkdownX, and let people do whatever they need with plugins. In that particular case, I hope that I can make it easy enough for people to integrate whatever specifics they have as plugins.
