### ISSUE TITLE
Adding markdown in the text input doesn't update the style of the text

### ISSUE THREAD

**Issue by JorensM** [mdx-editor/editor#270]
I'm not sure if I'm doing something incorrectly or if it's just not working, but when I go to edit text in my `MDXEditor` component's text field, the text stays unformatted/unstyled. The initial markdown that I pass to the `markdown` prop does get styled, but any subsequent text doesn't change its appearance.

**Comment by JorensM** [comment]
@petyosi I don't think a code example is necessary. It's just an `MDXEditor` component with a headings plugin and `markdown` prop set to "# aaa".

Let me try to explain better. The problem is that the text is not being rendered with any styles when I input some markdown into the editor.

For example if I type "## Another heading" into the editor, the text still shows "## Another heading" instead of "Another heading" in a big font and in bold.

The inital markdown that I passed to the `markdown` prop does get styled, but any text that I input into the field directly remains as plain unstyled text

**Comment by JorensM** [comment]
@petyosi 

https://github.com/mdx-editor/editor/assets/17122123/f8090ee1-853e-414e-9ac0-5007ed90e9a2

Here I have attached a video demonstration. As you can see the text that I input does not get converted to styled text even though it's valid syntax. And you can also see that the initial heading that was passed to the `markdown` prop does get styled.

**Comment by petyosi** [comment]
You're looking for the markdown shortcut plugin.

**Comment by JorensM** [comment]
@petyosi Ah, thank you very much. I didn't bother checking that section because I thought it was about keyboard shortcuts
