### ISSUE TITLE
Styles are not working in Webpack projects

### ISSUE THREAD

**Issue by KacperKozak** [mdx-editor/editor#272]
First of all, I want to thank you. This editor saved my project from ugly HTML! But I found one problem. The styles are not loading properly in projects that use Webpack. I isolated a problem in a clean webpack setup where you can reproduce this problem:

https://github.com/KacperKozak/mdx-editor-in-webpack/

Overall, it seems that for some reason, `css-loader` and `style-loader` cannot load the editor's global CSS file. I added the example `styles.css`, which works without problems. Other CSS files from external packages are working.  Event if you copy-paste editor CSS file directly to source it works... Here, you can see that styles are not included:

```ts
import "@mdxeditor/editor/style.css";
import "./styles.css";
```

<img width="2027" alt="image" src="https://github.com/mdx-editor/editor/assets/582227/995eb0c2-f46a-4eb5-9265-7888d0d8d768">

Any ideas?

**Comment by petyosi** [comment]
You're [encountering this problem](https://github.com/webpack/webpack/issues/8814#issuecomment-677828996).

**Comment by nulian** [comment]
Thanks for referencing that after enabling tree shaking on our project I spend a fair amount of time looking a solution for that issue.

**Comment by KacperKozak** [comment]
@petyosi Thanks, now it works. If I understand correctly, this is because of `"sideEffects": false` in editor `package.json` + Webpack tree-shaking/optimisation? Maybe changing this to `"sideEffects": ["*.css"]` will help for others?

Also, I updated the example, and if you want, feel free to copy it to the examples.

**Comment by petyosi** [comment]
@KacperKozak this makes sense - I'm not sure how the other bundlers treat this flag, or if this is something only of importance for Webpack...

**Comment by KacperKozak** [comment]
@petyosi  I also don't know, but the Create React App is built on top of Webpack, but it probably has this option enabled for CSS loaders under the hood. For Storybook, it also worked. Suppose this would give useful information for bundlers that support that. And if this fixes problems like this, everyone will be happier using this package.
