### ISSUE TITLE
Inline code format ignores bold and italic

### ISSUE THREAD

**Issue by SeungyeopShin** [mdx-editor/editor#273]
When use inline code format with bold and italic, in editor it looks like well.

But the value in markdown state doesn't include bold and italic format.

<img width="630" alt="image" src="https://github.com/mdx-editor/editor/assets/109323024/e57674f4-c8d3-4f42-ad97-84d80a0ccf49">

<img width="485" alt="image" src="https://github.com/mdx-editor/editor/assets/109323024/512d413a-9758-44a8-9e18-0f4083856a79">

**Comment by petyosi** [comment]
That's an omission in the conversion logic, indeed. I will see how if this is fixable.

**Comment by SeungyeopShin** [comment]
Thanks for reply.
Additionally, code format in blockquote is also same case.

**Comment by jschoder** [comment]
From what I can see from the original specification you can't format code-snippets. It will print them out literally: https://daringfireball.net/projects/markdown/syntax#precode

Showing them formatted in the editor is the actual bug. Ideally the buttons should be deactivated when editing inline code

**Comment by petyosi** [comment]
@jschoder code snippets can't be formatted, but you can nest an inline code (single ticks) inside bold/italic. This has practical implications, like an emphasized paragraph that has some variables in it.

**Comment by khushal87** [comment]
Ideally, Something like **`this`** or *`this`* is possible, but `**this**` won't format anything and would just add the snippet inside ``.
