### ISSUE TITLE
H1 tag breaking editor while span does not

### ISSUE THREAD

**Issue by shaipetel** [mdx-editor/editor#277]
Unsure if I am missing something in the documentation, but it seems some html tags are fine and others are not.

this breaks:
```md
# hello
<h1>world</h1>
```
while this works:
```md
# hello
<span>world</span>
```

My questions are:
1. Can I add support for other tags?
2. Is there a list of tags that are allowed?
3. Can I add a map for tags that are not allowed?
4. Can I have better error-handling, so that it would just ignore the tag and render the content (just plain text)?

Thanks!

**Comment by petyosi** [comment]
I think that the break you experience might be related to markdown, how linebreaks are handled and the nature of h1 being a block element while span is inline. I can't be sure without an error to look at, though. 

Up to your questions, yes, you can do pretty much everything you describe by writing your own HTML MDAST visitor that takes precedence over the built-in one - the process is outlined in the docs. Take a look at the source code of the built-in one for details, it's actually fairly straightforward. In fact, you might not need to create the export visitor, the built-in one should work for you.

**Comment by shaipetel** [comment]
Thanks!
Easily reproduce it using the public demo page, just put this markdown in the previewer.

**Comment by shaipetel** [comment]
Thanks! I will check now

**Comment by shaipetel** [comment]
Works perfectly :) thanks!
