### ISSUE TITLE
Image Upload Buttons Transparent

### ISSUE THREAD

**Issue by jeffsummer08** [mdx-editor/editor#278]
For some reason the buttons when uploading the image are transparent:
![image](https://github.com/mdx-editor/editor/assets/86799981/1c995d2f-10dd-4804-a3bb-727fd8726938)

**Comment by petyosi** [comment]
Most likely this is tailwind. You need to arrange your imports like this: 

https://github.com/mdx-editor/mdx-editor-in-next/blob/master/app/globals.css. 

Please confirm if this is the cause of the problem and if the fix works for you.

**Comment by jeffsummer08** [comment]
Yes, that was the error and your fix worked. Thanks for your help.
