### ISSUE TITLE
ImageUploadHandler not working

### ISSUE THREAD

**Issue by philipp985** [mdx-editor/editor#281]
Hello,
thanks for the elegant editor!
In case it is not yet know but the ImageUploadHandler for pasting images from the clipboard is not working anymore. I tried to work through the recent prs but could identify the changes that lead to the new behaviour. But my guess is that it worked prior to v2.

**Comment by petyosi** [comment]
Thanks for the report, most likely a bug I introduced in v2. Will look into it.

**Comment by philipp985** [comment]
Thanks for the quick reaction. Unfortunately this does not solve the problem.

**Comment by petyosi** [comment]
I saw that paste still does not work, which is weird.
