### ISSUE TITLE
Missing icons

### ISSUE THREAD

**Issue by nalnir** [mdx-editor/editor#284]
I'm using the editor in next.js project, but some icons are just not showing. Functionality works all well.

![Screenshot 2024-01-08 at 11 20 10](https://github.com/mdx-editor/editor/assets/28774583/6bf976ee-ab21-4806-937a-062585deca10)
![Screenshot 2024-01-08 at 11 20 18](https://github.com/mdx-editor/editor/assets/28774583/c7b4ccfe-e095-42c3-b92a-732a8d5e304d)

**Comment by petyosi** [comment]
Not sure what's wrong with your setup. Can you replicate it using one of the starting nextjs samples?

**Comment by nalnir** [comment]
Yeah so it works well when I create a new next js app, but does not show everything in my current app.
I think tho it's now much of an issue at least for now, since I'm able to just insert my own icons using `iconComponentFor`

**Comment by petyosi** [comment]
I'm afraid can't help much, then.

**Comment by nalnir** [comment]
No worries, iconComponentFor is definitelly a great workaround :)
