### ISSUE TITLE
Rich Text mode doesn't render markdown correctly

### ISSUE THREAD

**Issue by jojonoparat** [mdx-editor/editor#29]
Hi, really appreciate for your work so far, I have tried cloning from your [Nextjs example repo](https://github.com/mdx-editor/mdx-editor-in-next/tree/master) and run it. And it seems that Rich Text mode doesn't render markdown correctly
<img width="1458" alt="image" src="https://github.com/mdx-editor/editor/assets/100260851/f697070b-5c5d-4b14-8262-c9462cf4988d">
<img width="1456" alt="image" src="https://github.com/mdx-editor/editor/assets/100260851/5b0bb70e-4812-473f-b1cd-e590f7021831">
From the image above you can see that the size of text "hello world" should be rendered as Header1, however it still was rendered as normal text. Additionally, bulleted list and numbered list are also not working in rich text mode but bolding, underlining and italic work fine.

To replicate the issue:
- clone this [repo](https://github.com/mdx-editor/mdx-editor-in-next/tree/master)
- `npm i`
- `npm run dev`
- go to `localhost:3000` and see how the "hello world" text is rendered

So far, I've tried different version of both nextjs (version 13.4.12 and 13.4.4) and @mdxeditor/editor(version 0.6.1 and 0.10.1) and different local computer (Macbook M2 Pro and Macbook M2 Air). Still, it yields the same result.

Am I missing any configuration for rendering markdown properly in Rich text mode ?
Or is it only happening on my local computer only ?

**Comment by petyosi** [comment]
Hi, thanks for giving the editor a try! I will update the repo to ensure people don't get confused with it.

The problem you're observing is due to the tailwind reset, which Next.js ships by default. Even though the markup is there, the styling is not present. 

For [the live demo](https://mdxeditor.dev/editor/demo), I've applied the typography plugin. If you use something similar, you can [just pass the class](https://mdxeditor.dev/editor/docs/content-styling) to the editor component.

Alternatively, you [can also remove the tailwind reset](https://github.com/mdx-editor/mdx-editor-in-next/blob/master/app/globals.css#L1).

**Comment by vignesh-gupta** [comment]
I tried an other idea for this. Instead of removing `@tailwind base` which causes a lot of style disruption. We can do a [extend pre-flight css](https://tailwindcss.com/docs/preflight) and the changes as we need. I was just creating simple editor so I override for heading and anchor only - 

```css

@tailwind base;
@layer base {
  h1 {
    @apply text-3xl;
  }
  h2 {
    @apply text-2xl;
  }
  h3 {
    @apply text-xl;
  }
  h4 {
    @apply text-lg;
  }
  h5 {
    @apply text-base;
  }
  h6 {
    @apply text-sm;
  }
  a {
    @apply text-blue-600 underline;
  }
}
@tailwind components;
@tailwind utilities;

```

**Comment by armannaj** [comment]
> > Hi, thanks for giving the editor a try! I will update the repo to ensure people don't get confused with it.
> > The problem you're observing is due to the tailwind reset, which Next.js ships by default. Even though the markup is there, the styling is not present.
> > For [the live demo](https://mdxeditor.dev/editor/demo), I've applied the typography plugin. If you use something similar, you can [just pass the class](https://mdxeditor.dev/editor/docs/content-styling) to the editor component.
> > Alternatively, you [can also remove the tailwind reset](https://github.com/mdx-editor/mdx-editor-in-next/blob/master/app/globals.css#L1).
> 
> just want to simplify it more , just install `@tailwindcss/typography` to your next application and pass "pose" like this `<MDXEditor markdown={""} contentEditableClassName="prose" />`

Thanks, It works. If anyone else had issues with installing typography, check [here](https://tailwindcss.com/docs/typography-plugin#installation)
