### ISSUE TITLE
State does not change when markdown is set from a parent component

### ISSUE THREAD

**Issue by nalnir** [mdx-editor/editor#293]
This is a very strange behavior. I use `RichEditor` component in several components. On the image in the left RichEditor editor I am directly inputing content which works just fine. But the content is not reflected on the right side editor and remains empty
![Screenshot 2024-01-10 at 13 10 04](https://github.com/mdx-editor/editor/assets/28774583/673e9fbd-dff5-4926-8617-44626e08609c)

What is strange also is that the console log is reflecting the change correctly since the right editor is readOnly, but the MDXEditor state is not changed.

```
export const RichEditor = ({ markdown, onChange, readOnly }: RichEditorProps) => {
  if (readOnly) {
    console.log('readOnly markdown: ', markdown)
  }

  return (
    <Suspense fallback={<></>}>
          <MDXEditor
            readOnly={readOnly}
            onChange={onChange}
            className='text-black bg-white rounded-lg h-80'
            markdown={markdown ?? '# Hello world'}
            contentEditableClassName='prose max-w-full font-sans'
            plugins={allPlugins(markdown ?? '')}
          />
    </Suspense>
  );
};
```

**Comment by petyosi** [comment]
This? https://mdxeditor.dev/editor/docs/getting-started#basic-usage

**Comment by nalnir** [comment]
Yebs, this works. Thanks a million!
