### ISSUE TITLE
Link dialog does not support dark-theme

### ISSUE THREAD

**Issue by braincore** [mdx-editor/editor#295]
Similar to #125. When applying the `dark-theme` class to `MDXEditor`, the link dialog box retains its light theme. The input elements in the dialog box do correctly switch to dark theme.

**Comment by petyosi** [comment]
Can you elaborate? As far as I can tell, the dialog works well in the example from the source code. It did need an update to the color names, though - check this: https://github.com/mdx-editor/editor/commit/7d100d56ae7935c32f93bc1b48d49f1d6ea2184c. 
<img width="323" alt="image" src="https://github.com/mdx-editor/editor/assets/13347/5ccf5ebd-c99c-4728-8971-14c74cdc4eff">

**Comment by braincore** [comment]
Your screenshot is what I want, but the behavior I see differs.

Repro:
- Go to the live demo (https://mdxeditor.dev/editor/demo)
- Open inspect
- Add `dark-theme` class to the `editorRoot` with the `mdxeditor` class

The toolbar switches to dark mode, but the link dialog does not.

**Comment by petyosi** [comment]
That's not how the component operates, though. The class name you pass to the component is applied to the editor element **and** to a popup container that's responsible for containing the dialogs. 

Take the example from the commit I linked above and use it in your implementation.

**Comment by braincore** [comment]
I understand that `dark-theme` gets applied to both the editor and the popup container when using the editor's `className` prop. My mistake was thinking that `dark-theme` was sufficient to get a minimal dark theme for the dialog. I now understand that defining `dark-editor` with the correct css var overrides is necessary. Thanks!
