### ISSUE TITLE
Not able to combine bold and italic like the front page example: what am I missing?

### ISSUE THREAD

**Issue by j-weave** [mdx-editor/editor#296]
I have a react component of the following nature:

```
export const RichTextArea = (props: RichTextAreaProps) => {
  const [value, setValue] = useState<string>(props.value || '');

  const handleChange = (updatedValue: string) => {
    setValue(updatedValue);
    props.onChange?.(updatedValue);
  };

  return (
    <MDXEditor
      markdown={value}
      onChange={handleChange}
    />
  );
};
```

However, when I utilize this plugin, I cannot combine *both* bold and italic using keyboard shortcuts or any other means.  The sequence seems to go like this:
* Ctrl-B: text turns bold
* Ctrl-I: text doesn't change
* Ctrl-B: bold is removed, but _now the text is italic_ (appears to have been stored behind the scenes)
* Ctrl-I: text is unitalicized

Inspecting the element when bolded gives me something like the following:
```
<strong class="_bold_16kwi_10 _italic_16kwi_14" data-lexical-text="true">es</strong>
```

If I do the reverse, I get other odd behavior:
Ctrl-I: italicized
```
<em class="_italic_16kwi_14" data-lexical-text="true">es</em>
```
Then hit Ctrl-B, the italics disappear and the text turns bold, with the tag now being:
```
<strong class="_bold_16kwi_10 _italic_16kwi_14" data-lexical-text="true">es</strong>
```

But neither style shows up in my console to inspect, either, so I'm not sure what the deal is here?  Thoughts?

**Comment by petyosi** [comment]
No, no thoughts. Reproduce it in a sandbox and add the link here, I will take a look, and re-open the issue if necessary.

**Comment by j-weave** [comment]
Certainly - behavior is directly [replicated here](https://codesandbox.io/p/sandbox/react-new?file=%2Fpackage.json%3A10%2C29&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clr8umfde00063b6h2un3gp33%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clr8umfde00023b6h8d9bumb7%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clr8umfde00033b6hkxgs1etq%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clr8umfde00053b6h75wkosb1%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clr8umfde00023b6h8d9bumb7%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clr8umfdd00013b6h47zmshhx%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fsrc%252Findex.js%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522id%2522%253A%2522clr8ung83004r3b6hqogrx1c9%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A10%252C%2522startColumn%2522%253A29%252C%2522endLineNumber%2522%253A10%252C%2522endColumn%2522%253A29%257D%255D%252C%2522filepath%2522%253A%2522%252Fpackage.json%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522id%2522%253A%2522clr8umfde00023b6h8d9bumb7%2522%252C%2522activeTabId%2522%253A%2522clr8ung83004r3b6hqogrx1c9%2522%257D%252C%2522clr8umfde00053b6h75wkosb1%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clr8umfde00043b6hrxexmpxj%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522clr8umfde00053b6h75wkosb1%2522%252C%2522activeTabId%2522%253A%2522clr8umfde00043b6hrxexmpxj%2522%257D%252C%2522clr8umfde00033b6hkxgs1etq%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522clr8umfde00033b6hkxgs1etq%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

**Comment by j-weave** [comment]
@petyosi No problem!  

[Reproduced here](https://codesandbox.io/p/sandbox/amazing-shape-ys3xyp?file=%2Fsrc%2FApp.js).

* Go to the "HI there"
* select the text
* hit Ctrl-B
* hit Ctrl-I
* hit Ctrl-B again 

and you'll see the same issue.  Clearly this isn't happening on the front page of the MDXEditor, so what would the difference be here?

**Comment by j-weave** [comment]
@petyosi I think I've got something here...the classes for the style formatting are all present in the css file attached to your front page:

```
._bold_16kwi_10 {
    font-weight: 700
}

._italic_16kwi_14 {
    font-style: italic
}

._underline_16kwi_18 {
    text-decoration: underline
}

._strikethrough_16kwi_34 {
    text-decoration: line-through
}

._underlineStrikethrough_16kwi_38 {
    text-decoration: underline line-through
}

._subscript_16kwi_42 {
    font-size: .8em;
    vertical-align: sub!important
}

._superscript_16kwi_47 {
    font-size: .8em;
    vertical-align: super
}
```

I don't have these styles present in the css in the sandbox example, nor my own code, so this appears to be something created or added into a tailwind css file.  Since I don't receive these styles by default when installing the editor, is there something I / other users can be doing to pull this in?

**Comment by petyosi** [comment]
Without trying to scold you:
- There are **several working examples** as repositories for all modern React stacks, all of them mentioned in the docs. 
- The [getting started page](https://mdxeditor.dev/editor/docs/getting-started) refers to this line in more than one example:

```tsx
import '@mdxeditor/editor/style.css'
```

It's great that you're giving the editor a try, but it's going to be very hard to trial and error your way through the integration without reading the docs. I have no means to support you through chatting in Github issues.

**Comment by j-weave** [comment]
Hi!  Thanks, no worries and I appreciate the aid!  Pretty easy for that dependency to slip by, but glad I figured it out - that's a pretty key piece of troubleshooting info!  =)  

Speaking of trialing and erroring my way through the docs, hope there's some plans to  beef up the docs for the API`core` aspect - would help a lot when figuring out how to build our own plugins beyond a trivial one!  

Thanks again for your work in making this library, really appreciating it greatly!

**Comment by j-weave** [comment]
Also submitted https://github.com/mdx-editor/editor/pull/300 to add this note to the docs!  Have a great day!
