### ISSUE TITLE
Editor not editable inside a shadowroot on Chrome

### ISSUE THREAD

**Issue by Caligone** [mdx-editor/editor#299]
Hello there,

We are using MDXEditor (v2.2.1) component inside a shadow root because of context isolation requirements. Unfortunately, the content editable `div` is not editable and the `onChange` callback is never called but only on Chrome (v121). It's properly working on Firefox (v121) and a plain `contenteditable` `div` has no issue on both browser.

You can find a minimal reproducible example here: https://codesandbox.io/p/sandbox/mdxeditor-shadowroot-vn7rpw

Couldn't find any lead to dig further into the issue yet.

Cheers

**Comment by petyosi** [comment]
No idea, really. Could be a browser regression, it seems to be working fine in the current version of Chrome (v120)? You might have success finding more details in the Lexical discord channel. 

Let me know if you find something, I have no capacity to research this, I'm afraid.

**Comment by ndugger** [comment]
This is an issue with how shadow dom handles text selection, see https://github.com/facebook/lexical/issues/6709

(This totally killed my momentum, I will have to figure out moving my browser extension out of shadow dom)
