### ISSUE TITLE
Improve docs about custom buttons in toolbar (for example, strikethrough).

### ISSUE THREAD

**Issue by SpeedySH** [mdx-editor/editor#30]
I want to make a strikethrough button, but I can't. Because sources, as I found in the repo, don't provide these functions, etc.

And only one option is what I have, which is to fork and append it, but I don't want to.

Maybe you can provide any examples or improve the documentation about it?

Thanks.

**Comment by petyosi** [comment]
> And only one option is what I have, which is to fork and append it, but I don't want to.

I'm afraid that strikethrough support is not available at the moment, not only as a button but as import/export logic, as well - so it's not only a matter of a button in the toolbar.

I am working on making it easier to plug in such features without the necessity to fork. It's possible now as well, but, as you've pointed out, it's lacks examples and conceptual documentation.

**Comment by AdityaBorkar** [comment]
@SpeedySH,
I am working on this functionality and would love to hear your feedback in the pull request https://github.com/mdx-editor/editor/pull/39#issuecomment-1681733975

**Comment by tatarianBarbarian** [comment]
@petyosi why in the world would you disable these features? 
Do you plan to make it available?

**Comment by petyosi** [comment]
@tatarianBarbarian I did not disable these features. They were never implemented in the first place. The PR above was written against the previous major version of the editor. You can pick it up, follow the comments I've left there and open a new one.

**Comment by tatarianBarbarian** [comment]
@petyosi Do I understand it right that in this case I'll need to add gfm extensions, visitors and probably transformer for shortcut plugin, too?

**Comment by petyosi** [comment]
I don't think you need gfm extensions, but I might be missing something. The rest is more or less the same as the bold/italic/underline logic.

**Comment by petyosi** [comment]
v3.1.0 includes support and a toolbar item for superscript, subscript and strikethrough. https://github.com/mdx-editor/editor/releases/tag/v3.1.0.
