### ISSUE TITLE
Toolbar dialogs not working when using with shadcn/ui

### ISSUE THREAD

**Issue by StasSemak** [mdx-editor/editor#301]
When i try to use editor in project that uses `shadcn/ui` library, toolbar dialogs (like `<CreateLink/>` or  `<BlockTypeSelect/>`) are not functioning. My suggestion is that **both** `shadcn/ui` and `mdx-editor` are using Radix UI.  Is there any way to resolve this issue?

Here's my code:
[Editor initialization](https://github.com/StasSemak/sas-web/blob/main/src/components/MDXEditor.tsx)
[Usage](https://github.com/StasSemak/sas-web/blob/main/src/components/CreateActivityForm.tsx#L278-L282)

[You can observe behaviour here](https://sas-nuwm.vercel.app/test)

**Comment by petyosi** [comment]
No idea. I'm not familiar with shadcn. Given that shadcn is breaking the behavior of the Radix UI components, you should rather bring this to the attention of them - they might know more.
