### ISSUE TITLE
Readonly mode is still editable

### ISSUE THREAD

**Issue by GNITOAHC** [mdx-editor/editor#302]
Following is my Editor component. After passing `readOnly` as true, the content is still editable.
```tsx
export default function Editor({
  markdown,
  setMarkdown,
  readOnly,
}: {
  markdown: string
  setMarkdown?: React.Dispatch<React.SetStateAction<string>>
  readOnly?: boolean
}) {
  const onContentChange = (md: string) => {
    if (readOnly) return
    if (setMarkdown) setMarkdown(md)
  }

  return (
    <MDXEditor
      markdown={markdown}
      // className={styles.editor}
      className="border-2 border-gray-300 rounded-md"
      contentEditableClassName="prose"
      plugins={readOnly ? readOnlyPlugins(markdown) : allPlugins(markdown)}
      onChange={(md) => onContentChange(md)}
      readOnly={readOnly ? readOnly : false}
    />
  )
}
```

BTW, passing `readOnly` as true will cause error in rendering table component.

`readOnly == true`
<img width="660" alt="截圖 2024-01-14 上午12 42 01" src="https://github.com/mdx-editor/editor/assets/91186819/7bb08016-cc2d-4e63-8181-eebf534c783a">

`readOnly == false`
<img width="646" alt="截圖 2024-01-14 上午12 40 51" src="https://github.com/mdx-editor/editor/assets/91186819/0109e905-3d9d-4b94-96c5-489b4d9d3713">

**Comment by petyosi** [comment]
The table needs some love indeed. Notice that changing plugins at runtime is unlikely to work though. 

I seem to be missing something, though - the basic readOnly flag works in my tests. Can you help me by reproducing the problem in a sandbox?

**Comment by GNITOAHC** [comment]
Yeah sure!! [This](https://codesandbox.io/p/devbox/thirsty-bash-tv4ry7?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clrcxdtba00073b6euey9pb39%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clrcxdtba00023b6epvg4lzdx%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clrcxdtba00043b6eg30t564u%2522%257D%252C%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clrcxfi00006o3b6ektmyotrk%2522%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clrcxdtba00063b6e51na1afw%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B47.95609435179448%252C52.04390564820552%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clrcxdtba00023b6epvg4lzdx%2522%253A%257B%2522id%2522%253A%2522clrcxdtba00023b6epvg4lzdx%2522%252C%2522activeTabId%2522%253A%2522clrcyaflq01qv3b6etbvqlnan%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clrcxdtba00013b6e8njykby6%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252FREADME.md%2522%257D%252C%257B%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fapp%252Freadonly%252Fpage.tsx%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A24%252C%2522endLineNumber%2522%253A24%252C%2522startColumn%2522%253A7%252C%2522endColumn%2522%253A100000006%257D%255D%252C%2522id%2522%253A%2522clrcyaflq01qv3b6etbvqlnan%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%255D%257D%252C%2522clrcxdtba00063b6e51na1afw%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clrcxdtba00053b6eslhzd2gq%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_PORT%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522port%2522%253A3000%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522clrcxdtba00063b6e51na1afw%2522%252C%2522activeTabId%2522%253A%2522clrcxdtba00053b6eslhzd2gq%2522%257D%252C%2522clrcxdtba00043b6eg30t564u%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clrcxdtba00033b6es294bt3u%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522dev%2522%257D%255D%252C%2522id%2522%253A%2522clrcxdtba00043b6eg30t564u%2522%252C%2522activeTabId%2522%253A%2522clrcxdtba00033b6es294bt3u%2522%257D%252C%2522clrcxfi00006o3b6ektmyotrk%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clrcxf96m006d3b6elqe7i65b%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TERMINAL%2522%252C%2522shellId%2522%253A%2522clrcxflhn007nefge45w3er21%2522%257D%255D%252C%2522id%2522%253A%2522clrcxfi00006o3b6ektmyotrk%2522%252C%2522activeTabId%2522%253A%2522clrcxf96m006d3b6elqe7i65b%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D) is the sandbox.

**Comment by petyosi** [comment]
Thank you, the sandbox was helpful. Apparently I messed it up specifically in the Next.js context. v2.3.2 fixes it, here's an [updated version of your sandbox with the new version](https://codesandbox.io/p/devbox/thirsty-bash-tv4ry7). 

Fixed the table layout as well.
