### ISSUE TITLE
MDXEditor inside mui dropdown or inside higher order stacking context element

### ISSUE THREAD

**Issue by Eliav2** [mdx-editor/editor#305]
MDXEditor dropdowns, like the ones in `BlockTypeSelect` are not displayed correctly inside mui Dialog or mui Backdrop.

heres a [CodeSandbox link](https://codesandbox.io/p/sandbox/mdxeditor-mui-dropdown-34rmjy?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clrcgncfo00063j6gee5tani4%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clrcgncfn00023j6g4zyd8c6u%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clrcgncfn00033j6g7ezt39qk%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clrcgncfn00053j6gsw1nsu5h%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clrcgncfn00023j6g4zyd8c6u%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clrcgncfm00013j6g6dcrqbh8%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fpublic%252Findex.html%2522%257D%255D%252C%2522id%2522%253A%2522clrcgncfn00023j6g4zyd8c6u%2522%252C%2522activeTabId%2522%253A%2522clrcgncfm00013j6g6dcrqbh8%2522%257D%252C%2522clrcgncfn00053j6gsw1nsu5h%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clrcgncfn00043j6gq48ydy0b%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522clrcgncfn00053j6gsw1nsu5h%2522%252C%2522activeTabId%2522%253A%2522clrcgncfn00043j6gq48ydy0b%2522%257D%252C%2522clrcgncfn00033j6g7ezt39qk%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522clrcgncfn00033j6g7ezt39qk%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

**Comment by sahishnu** [comment]
I am having the same issue with the link plugin. The link dialog is not focusable. I cannot type in the url or label field.

**Comment by ReadabilityOne** [comment]
You can easily re-implement the block type select component with MUI ;)

**Comment by Eliav2** [comment]
I've would love to provide a 'component' to some of the inner component. i can see you used [radix-ui select](https://github.com/mdx-editor/editor/blob/fa71fc01bff22f3a929a7760cb5d03f77e4a0eec/src/plugins/toolbar/primitives/select.tsx#L2) component for the Select component used by many components in MDXEditor, and apparently it does not play well with MUI.

currently i cloned the component and re-implemented some UI. MUI is the most popular UI library for react by far and a native support for it could have been awsome.

**Comment by ReadabilityOne** [comment]
I agree, I also found some weird issues when I implemented UI based on shadcn/ui, the popover and drop down wouldn't work well.

One idea is MDXEditor can provide a headless mode without depending on any UI framework. In this mode MDXEditor only handles the editor core features, e.g set text format, JSX, directives, code editing etc. Anything else will be  handled by UI adapter, e.g MUI, mantine, radix-ui/shadcn-ui etc.

Not sure if the creator @petyosi would have different ideas, we can move this topic to discussions.

**Comment by petyosi** [comment]
@Eliav2 [here's a fix for your sandbox](https://codesandbox.io/p/sandbox/mdxeditor-mui-dropdown-forked-7w5lhn?file=%2Fsrc%2Fstyles.css%3A8%2C1). As an enhancement, I will make this CSS selector more convenient and document how would that work. I believe that there are several existing issues where people mention this approach as working. To sum it up, it's an arms race of which overlay should have the higher z-index. 

@sahishnu I'm not sure what kind of issue do you have, but you can test the above. If it does not work for you, I need a reproduction to help you further. 

> by the way, I've debugged the behavior of the stacking context of the radix-ui select component and it acting completely strange and incorrect! You should completely re-consider the using of this UI library as it does not behave in a standard way in the context of z-index and stacking context behavior.

I would love to understand this better. Can you help me out? A very simple reproduction (does not need MDXEditor I guess?) would be very helpful. Perhaps I can contribute a fix to the Radix library. 

@ReadabilityOne Up to the broader problem, I believe that an "adapter layer" that lets users plug their UI primitives of choice is going to be a massive hit in the React ecosystem in general :). Are there any working examples of such implementation? 

I believe that the problem here is solved, but let me know if I'm missing something.

**Comment by Eliav2** [comment]
@petyosi 
> I would love to understand this better. Can you help me out? A very simple reproduction (does not need MDXEditor I guess?) would be very helpful. Perhaps I can contribute a fix to the Radix library.

To understand, or actually just debug(because I could not fully _understand_ the stacking formation behavior of radix-ui Select component)  we can use the awesome [3d-view](https://stackoverflow.com/a/60094185/10577976)  in Edge devtools, in test out 3 senarios.
- native `select` component.
- mui `Select` component.
- radix-ui `Select` component

take a look at [this sandbox](https://codesandbox.io/p/sandbox/mdxeditor-mui-dropdown-forked-7w5lhn?file=%2Fsrc%2Fstyles.css%3A8%2C1&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clrd9uo8900073j6guxkwm2d9%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clrd9uo8800033j6gqlocjghs%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clrd9uo8800043j6gj2ekmky6%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clrd9uo8800063j6gpjcawlof%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clrd9uo8800033j6gqlocjghs%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clrd9uo8800023j6gsproyhoo%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A8%252C%2522startColumn%2522%253A1%252C%2522endLineNumber%2522%253A8%252C%2522endColumn%2522%253A1%257D%255D%252C%2522filepath%2522%253A%2522%252Fsrc%252Fstyles.css%2522%257D%255D%252C%2522id%2522%253A%2522clrd9uo8800033j6gqlocjghs%2522%252C%2522activeTabId%2522%253A%2522clrd9uo8800023j6gsproyhoo%2522%257D%252C%2522clrd9uo8800063j6gpjcawlof%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clrd9uo8800053j6ggyyycd2y%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522clrd9uo8800063j6gpjcawlof%2522%252C%2522activeTabId%2522%253A%2522clrd9uo8800053j6ggyyycd2y%2522%257D%252C%2522clrd9uo8800043j6gj2ekmky6%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522clrd9uo8800043j6gj2ekmky6%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D). and the [preview link](https://m3wl8j.csb.app/). open the 3d-view tab in the edge devtools.

### the composite layers
![image](https://github.com/mdx-editor/editor/assets/47307889/d021fa22-9851-42c1-9561-54621977cbf0)

note the default composite layers when no dropdown in open.

#### native `select` 

![image](https://github.com/mdx-editor/editor/assets/47307889/6b51ca9c-e8f9-4dee-bd6d-d36bfe161f42)

we can see that native `select` does not form another composite layer.

#### mui `Select` 

![image](https://github.com/mdx-editor/editor/assets/47307889/8ae6c7f6-53f6-46ce-b707-f99180cdbeb1)

mui `Select` component does create a new layer, but on top it's children, as expected.

#### radix-ui `Select` 

![image](https://github.com/mdx-editor/editor/assets/47307889/f96307bb-1257-4694-8775-15a6d176efe1)

when radix-ui `Select` dropdown was opened, at replaced it's parent layer, which should not happen, I've even taken a look at the dom tree and opening the dropdown changes dom trees above its parent which is super weird. i'm not sure how they implemented their Select component but it does not behave as expected. 

z-index is always resolved from within the parent stacking context, take this [example](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_positioned_layout/Understanding_z-index/Stacking_context#example):
> It is important to note that DIV #4, DIV #5 and DIV #6 are children of DIV #3, so stacking of those elements is completely resolved within DIV #3

so if the dialog is the parent, and toolbar is it children, and dropdown is its children, in correct implementation the dropdown can never be behind the dialog. because if a new stacking context is formed, it should be formed 'above' it's parent

**Comment by petyosi** [comment]
Thank you for the explanation. What you observe has nothing to do with Radix UI select and is a deliberate implementation in MDXEditor. 

Upon initialization, the editor appends a popup placeholder at the end of the document, and uses it for its dialogs, popovers, and tooltips. This avoids problems related to tooltips being cut-off from scrollable/overflow-hidden containers. 

I will consider how this (and its implications/workarounds) can be documented better.

**Comment by Eliav2** [comment]
This explains the weird behavior. you should consider providing an option to opting out of this behavior via a prop or re-think the implementation later. not must-have, but nice-to-have 🙌

**Comment by finnianj** [comment]
I had a similar issue viewing the BlockTypeSelect dropdown when the editor was displayed inside a modal. 

Resolved with:

`div[role="listbox"] {
  z-index: 2000 !important;
}`
<img width="815" alt="Screenshot 2024-04-10 at 12 45 37" src="https://github.com/mdx-editor/editor/assets/114495682/3c4e14f7-76aa-40f5-8bd2-a84a68b10325">

**Comment by eBaeza** [comment]
Just set the z-index to the value works for you guys. I'm using it in Next.js

```css
.mdxeditor-popup-container {
    z-index: 9999; // use the value that works for you
}
```

**Comment by murtazablt** [comment]
> Just set the z-index to the value that works for you guys. I'm using it in Next.js
> 
> ```css
> .mdxeditor-popup-container {
>     z-index: 9999; // use the value that works for you
> }
> ```


the simplest solution ever, thank you man!

**Comment by murtazablt** [comment]
Adding z-index fixes the problem if there is only one modal. When you open another modal/dialog in the modal, pop-up container shows up with border and causes overflowing like this:
