### ISSUE TITLE
Undo only works when focus is inside the text editor

### ISSUE THREAD

**Issue by lambardi** [mdx-editor/editor#32]
If I highlight some text in the live demo, and then change the paragraph style. e.g. place my cursor/focus in a bit of "Heading 1" text and then click into the paragraph dropdown and change the style to another paragraph style, say "Caution" and then realize I didn't want to do that and hit undo (cmd+z) nothing happens. I must first click back into the editor text, and then I can cmd+z back from "Caution" to "Heading 1"

**Comment by petyosi** [comment]
I think I fixed that at some point, restoring the focus back to the editor from the block type select. 

Cheers!
