### ISSUE TITLE
[BUG] Impropor dark-mode style for `diff mode` and `source mode`

### ISSUE THREAD

**Issue by cuttle-fish-my** [mdx-editor/editor#323]
**Describe the bug**
The dark-mode style is weird for `diff` and `source` modes:
![image](https://github.com/mdx-editor/editor/assets/82512952/d70b0195-4e08-44f7-9fb8-8a79dc554343)

![image](https://github.com/mdx-editor/editor/assets/82512952/ccdd2763-f241-446b-a549-82217ad719fd)

**Reproduction**
https://codesandbox.io/embed/k43d4d?view=Editor+%2B+Preview&module=%2Fsrc%2FApp.js

Thanks for your great work, and I look forward to your early reply!

**Comment by petyosi** [comment]
Thank you for the report, I will look into it. 

> I look forward to your early reply!
If you have any expectations about the timeframe of me fixing this, you should sponsor the project.

**Comment by petyosi** [comment]
The diffSource plugin has an configuration option that lets you specify additional code mirror extensions, including themes. You can take for example the basic dark theme and apply [it like this](https://codesandbox.io/p/sandbox/mdxeditor-darkmode-forked-3w2lfz).

**Comment by cuttle-fish-my** [comment]
Thanks!

**Comment by reinismu** [comment]
I guess previous link went out of date

Light theme is coming from this code

https://github.com/mdx-editor/editor/blob/98e63f3bdda328977410930efa515dcf286433d3/src/plugins/diff-source/SourceEditor.tsx#L13

To change it to other theme you need to override extensions

```
import { basicDark } from 'cm6-theme-basic-dark'
...
    diffSourcePlugin({ diffMarkdown: 'An older version', viewMode: 'rich-text', codeMirrorExtensions: [basicDark] }),
...
```
