### ISSUE TITLE
[BUG]CodeMirrorPlugin: How does CodeMirrorPlugin support other language such as `c` or `cpp`?

### ISSUE THREAD

**Issue by tohsaka888** [mdx-editor/editor#325]
If you want to ask for support or request features, [sponsor the project](https://github.com/sponsors/petyosi) and contact me over email.
If you want to discuss something, use the discussions section for that. 

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] I have read the documentation and cannot find an answer.

**Describe the bug**
I wish to use CodeMirrorPlugin to render syntax highlighting in other language modes. When I set the `codeBlockLanguages` parameter to c, the syntax highlighting is still consistent with js. I don't know how to handle it to support it. (PS. I also checked the CodeMirror documentation and found that there is [language model](https://codemirror.net/5/mode/index.html) support, but I don’t know how to apply it)
**Reproduction**
Use https://codesandbox.io/ to reproduce the problem so that I can observe the issue on my side and make sure that a potential fix reliably addresses it.

**To Reproduce**
NA

**Expected behavior**
I wish to use CodeMirrorPlugin to render syntax highlighting in other language modes. When I set the `codeBlockLanguages` parameter to c, the syntax highlighting is still consistent with js. I don't know how to handle it to support it. (PS. I also checked the CodeMirror documentation and found that there is [language model](https://codemirror.net/5/mode/index.html) support, but I don’t know how to apply it)

Here is my code:

```tsx
<MDXEditor
      plugins={[
        // Example Plugin Usage
        headingsPlugin(),
        listsPlugin(),
        linkPlugin(),
        quotePlugin(),
        thematicBreakPlugin(),
        codeBlockPlugin({ defaultCodeBlockLanguage: "cpp" }),
        // sandpackPlugin(),
        diffSourcePlugin({
          diffMarkdown: "An older version",
          viewMode: "rich-text",
        }),
        codeMirrorPlugin({
          codeBlockLanguages: {
            js: "JavaScript",
            ts: "typescript",
            c: "C-like",
            shell: "Shell",
          },
          
        }),
        tablePlugin(),
        toolbarPlugin({
          toolbarContents: () => (
            <DiffSourceToggleWrapper>
              <UndoRedo />
              <BoldItalicUnderlineToggles />
              <InsertCodeBlock />
              <InsertTable />
            </DiffSourceToggleWrapper>
          ),
        }),
        markdownShortcutPlugin(),
      ]}
      {...props}
      ref={editorRef}
    />
```
**Screenshots**

**Desktop (please complete the following information):**
 - Arch WSL
 - Chrome

**Additional context**
NA.

**Comment by petyosi** [comment]
The codemirror plugin does not support additional languages at the moment. I filed this idea here - https://github.com/mdx-editor/editor/discussions/328.
