### ISSUE TITLE
[BUG] Website API page is full of broke links (https://mdxeditor.dev/editor/api)

### ISSUE THREAD

**Issue by TomNUSDS** [mdx-editor/editor#329]
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] I have read the documentation and cannot find an answer.

**Describe the bug**
Relative links in "Table of contents" sections on api page are all 404.

**To Reproduce**
1. Go to Table of Contents section on Api page https://mdxeditor.dev/editor/api#table-of-contents
2. Click on any specific API section link (e.g. `https://mdxeditor.dev/editor/interfaces/MDXEditorMethods`)
Result: 404

**Expected behavior**
The correct urls seems to require `/api/` in the path?
Fails => `https://mdxeditor.dev/editor/interfaces/MDXEditorMethods`
Works => `https://mdxeditor.dev/editor/api/interfaces/MDXEditorMethods`

**Screenshots**

**Desktop (please complete the following information):**
 - OS: MacOS desktop
 - Browser: Chrome

**Comment by TomNUSDS** [comment]
Humm.. maybe this issue should be over on `https://github.com/mdx-editor/site/issues` ? Let me know if I should move it.

**Comment by petyosi** [comment]
Thanks, solved.
