### ISSUE TITLE
Issue with import

### ISSUE THREAD

**Issue by mrunalsen** [mdx-editor/editor#33]
![image](https://github.com/mdx-editor/editor/assets/97331976/0c5c1924-82d7-4a7d-ba65-a53d0f2a4a00)

Hi,
I've recently switched to react from angular and I'm giving this library a try and it is showing me this error no matter what I do. Can you help me with this?
Thanks

**Comment by petyosi** [comment]
Looks like this: https://github.com/mdx-editor/editor/issues/14#issuecomment-1636264226.

**Comment by mrunalsen** [comment]
@petyosi thank you for your quick response. Saved me a lot of time.
It was indeed problem with create-react-app.
Its working in the project i created with Vite.
Thank you so much once again
