### ISSUE TITLE
Select All doesn't select text in the editor

### ISSUE THREAD

**Issue by vcarl** [mdx-editor/editor#34]
When I hit `cmd-a` I expected to select all text in the editor. Instead, it just flasheed and lost my cursor position

https://github.com/mdx-editor/editor/assets/1551487/7b623f0f-9a29-402e-a324-daaa10ee31e5

**Comment by petyosi** [comment]
Confirming, a bug in Lexical, discussed here. https://github.com/mdx-editor/editor/discussions/21. Will do the suggested workaround.

**Comment by petyosi** [comment]
Fixed in v0.15.0.
