### ISSUE TITLE
[BUG]headingsPlugin and listsPlugin not working

### ISSUE THREAD

**Issue by gushaorong** [mdx-editor/editor#344]
I downloaded the example from https://github.com/mdx-editor/mdx-editor-in-next and ran on my local machine.
I added headingsPlugin and listsPlugin and toolbar as follow:
```
<MDXEditor
      ref={editorRef}
      markdown={markdown}
      plugins={[
        headingsPlugin(),
        listsPlugin(),
        toolbarPlugin({
          toolbarContents: () => (
            <>
              {" "}
              <ListsToggle />
            </>
          ),
        }),
      ]}
    />
```
but heading and list don't work. I think it's maybe related to tailwindcss.

**Comment by petyosi** [comment]
The plugins work just fine, but the tailwind base resets the styling of the lists and the headings. You need to add your additional styling to overcome that.

**Comment by rissois** [comment]
You can use `className="prose max-w-none"` to remove the tailwind styling.

**Comment by incpo** [comment]
I solve it by 3 steps:
1. Download tailwind plugin - 
```bun add  @tailwindcss/typography```
3. Add it to tailwind config - 
```/** @type {import('tailwindcss').Config} */
module.exports = {
  theme: {
    // ...
  },
  plugins: [
    require('@tailwindcss/typography'),
    // ...
  ],
} satisfies Config;
```

5. Update contentEditableClassName - 
``` <MDXEditor contentEditableClassName='prose' markdown={markdown} />```

**Comment by Safian-Haq** [comment]
> The plugins work just fine, but the tailwind base resets the styling of the lists and the headings. You need to add your additional styling to overcome that.

Would recommend adding this as note in the docs or in the readme.

**Comment by yotaro-shimose** [comment]
I got stuck with this problem.

I cloned the [next-js template](https://github.com/mdx-editor/mdx-editor-in-next).

And then add a line `contentEditableClassName="prose max-w-none"` resulting below EditorComponent.tsx file.
```tsx
"use client";

import { MDXEditor, MDXEditorMethods, headingsPlugin } from "@mdxeditor/editor";
import { FC } from "react";

interface EditorProps {
  markdown: string;
  editorRef?: React.MutableRefObject<MDXEditorMethods | null>;
}

/**
 * Extend this Component further with the necessary plugins or props you need.
 * proxying the ref is necessary. Next.js dynamically imported components don't support refs.
 */
const Editor: FC<EditorProps> = ({ markdown, editorRef }) => {
  return (
    <MDXEditor
      onChange={(e) => console.log(e)}
      ref={editorRef}
      markdown={markdown}
      plugins={[headingsPlugin()]}
      contentEditableClassName="prose max-w-none"
    />
  );
};

export default Editor;
```
I also installed @tailwindcss/typography and added `require('@tailwindcss/typography'),` in tailwind.config.js's pulgins list.

But I still get not heading styling
![Image](https://github.com/user-attachments/assets/84c04ce8-cd6b-4395-bbf6-58cce2a2cd14)

Could anyone help me?
