### ISSUE TITLE
Update Plugins after initial render

### ISSUE THREAD

**Issue by androidplayer1** [mdx-editor/editor#359]
Greetings,

I started using this module, and so far so good. Can say documentation can be better tho.

I am facing an issue, using the diff check plugin. I want to change the "original value markdown" later, but there is no way that I can update a specific plugin after the MDXEditor has been initialised.

Changing configs and re-rendering of component doesnt do the trick.

**Comment by petyosi** [comment]
What you describe should work. Some plugins, including the diff-source one actually accept updates on their config. 

It would be great if you accompany your bug reports with actual reproductions of what you're doing, as the issue template strongly recommends. In the meantime, I'm closing this.

**Comment by androidplayer1** [comment]
> What you describe should work. Some plugins, including the diff-source one actually accept updates on their config.
> 
> It would be great if you accompany your bug reports with actual reproductions of what you're doing, as the issue template strongly recommends. In the meantime, I'm closing this.

            diffSourcePlugin({
              viewMode: 'rich-text',
              diffMarkdown: props.originalValue,
              codeMirrorExtensions: [basicDark],
            }),

This function is passed to plugins array on MDXEditor, and no, it does not update the diffMarkdown value when originalValue inside props is changing.
