### ISSUE TITLE
[BUG] Editor does not pick dark mode class when applied to html / parent tag. Only when applied to the MdxEditor tag.

### ISSUE THREAD

**Issue by hirenr** [mdx-editor/editor#361]
If you want to ask for support or request features, [sponsor the project](https://github.com/sponsors/petyosi) and [contact me over email](mailto:petyo@mdxeditor.dev).

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] I have read the documentation and cannot find an answer.

**Describe the bug**
Editor does not pick dark mode class when applied to html tag. Only when applied to the MdxEditor tag.

**Reproduction**
Start from https://codesandbox.io/p/sandbox/mdx-editor-base-q8s7zr?file=/src/App.tsx to reproduce the problem so that I can observe the issue on my side and make sure that the fix reliably addresses it.

**To Reproduce**
1. Go to 'App.tsx'
2. Add "dark" or "dark-theme" to the parent div className.

**Expected behavior**
"dark" or "dark-theme" present in its parent hierarchy should trigger dark mode in the editor

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Mac
 - Browser: Chrome, Safari

**Additional context**
I am using shadcn / tailwindcss for my website. MDXEditor is a component within the website. My website gets into dark mode when "dark" is added to the html class list. This is standard behaviour that is their in any website using tailwindcss. If I insert "dark" in the Editor classname directly, dark mode is triggered. it should be triggered if present in html tag.

**Comment by petyosi** [comment]
You have not given a reproduction, but my guess is that you have copy-pasted the example without adjusting the CSS selectors accordingly. Use your inspector to verify that the CSS variables are correctly applied.
