### ISSUE TITLE
Support for remark plugin?

### ISSUE THREAD

**Issue by artt** [mdx-editor/editor#37]
Just found out about this. Is there a way for me to add a custom remark plugin that would process the markdown before rendering?

**Comment by petyosi** [comment]
Yes. The project uses the `mdast-util` [family of packages](https://github.com/syntax-tree/mdast#list-of-utilities) internally. [Here's how the table plugin works](https://github.com/mdx-editor/editor/blob/main/src/plugins/table/index.ts#L55-L62), for example. Notice that you'll most likely need both the utility that converts the markdown to AST and the one that converts the AST to markdown. 

Let me know what you want to achieve - I should be able to help you further.

**Comment by artt** [comment]
Thanks. I'll look into it.

I have a Gatsby site with markdown files for its content with some custom processing (like citation, etc.). Right now the person doing the content updating has to do it "blind" (as in she memorize how to do figures and references) but doesn't have a way to check. Thinking about ways to help her.

I looked into [Decap CMS](https://decapcms.org/) (formerly NetlifyCMS) before, but it doesn't support custom plugins, so it doesn't solve the "blind editing" problem. If I understand correctly, this MDX editor component can be integrated into it, and that would make things a lot better.

**Comment by petyosi** [comment]
That's great - thank you for sharing. Can you show me an example of the syntax you use? I would love to use such real life cases as examples in the documentation.
