### ISSUE TITLE
[BUG] Parsing of the following markdown structure failed: {"type":"code","name":"N/A"}.

### ISSUE THREAD

**Issue by floatrx** [mdx-editor/editor#370]
**Description:**
When using the MDXEditor in source mode and attempting to insert a code block using triple backticks (```), the editor fails to parse the markdown structure, resulting in a parsing error. This issue prevents users from adding code snippets to their markdown documents directly in the source mode.

**Error Message:**
`Parsing of the following markdown structure failed: {"type":"code","name":"N/A"}.
Steps to Reproduce:`

**Steps 2 reproduce**
- Open the MDXEditor.
- Switch to source mode by selecting the "Source" option.
- Attempt to insert a code block by typing or pasting in triple backticks followed by some code, then closing with triple backticks again. 
For example:
```
some code
```
- Observe the parsing error message as described above.

**Expected Behavior:**
The editor should correctly parse the code block enclosed in triple backticks, allowing the user to insert code snippets into their markdown document without encountering a parsing error.

**Actual Behavior:**
The editor displays a parsing error when attempting to insert a code block using triple backticks, preventing the user from successfully adding code snippets in source mode.

**Comment by petyosi** [comment]
My guess is that you need to configure the codeMirrorPlugin to support code blocks without any language specified, by passing a `'': 'Text'` to the codeBlockLanguages. Give it a try.

**Comment by floatrx** [comment]
> My guess is that you need to configure the codeMirrorPlugin to support code blocks without any language specified, by passing a `'': 'Text'` to the codeBlockLanguages. Give it a try.

I don't use the codeMirrorPlugin, and it's unnecessary for my purposes. Markdown inherently supports code blocks without the requirement to specify a language.

This bug was also reproduced in the [official live demo](https://mdxeditor.dev/editor/demo.)
<img width="392" alt="Screenshot 2024-03-01 at 17 16 57" src="https://github.com/mdx-editor/editor/assets/6949882/6923184a-2f94-4412-86c4-094f8ad31dd2">
<img width="524" alt="Screenshot 2024-03-01 at 17 17 33" src="https://github.com/mdx-editor/editor/assets/6949882/397ab756-310f-4b76-a117-c033dc388b70">

This issue is not critical but it would be nice to have it fixed.

**Comment by wp0403** [comment]
I have encountered the same error as you, and need to configure all the code block languages you use in markdown to codeMirrorPlugin
<img width="710" alt="image" src="https://github.com/mdx-editor/editor/assets/75709526/876fe630-707d-469a-ae1b-d2328c494518">
<img width="287" alt="image" src="https://github.com/mdx-editor/editor/assets/75709526/bfd8ae6d-6eb6-46ff-a55d-e03757fce94c">

**Comment by floatrx** [comment]
@wp0403 Helps, but we should explicitly provide an empty string ('') 


```javascript
    const codeBlockLanguages = ['', ...]; // <- here                                           
    ...
    codeMirrorPlugin({
      codeBlockLanguages: codeBlockLanguages.reduce((acc, language) => {
        acc[language] = language;
        return acc;
      }, {}),
    }),```

**Comment by pbjorklund** [comment]
> My guess is that you need to configure the codeMirrorPlugin to support code blocks without any language specified, by passing a `'': 'Text'` to the codeBlockLanguages. Give it a try.

This would be great to have in the example in the docs.
