### ISSUE TITLE
[BUG] Directives cause following content to not render

### ISSUE THREAD

**Issue by ckpearson** [mdx-editor/editor#372]
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] I have read the documentation and cannot find an answer.

**Describe the bug**
When adding the directives plugin ANY directive encountered causes content following it to not render

**Reproduction**
Minimal repro here:  https://codesandbox.io/p/sandbox/mdx-editor-base-forked-3k4wff

**To Reproduce**
1. Have markdown with a directive in it followed by other content
2. Add the directives plugin

**Expected behavior**
I would expect the plugin to skip over directives it cannot handle and for the editor to then render any following content

**Desktop (please complete the following information):**
 - OS: MacOs
 - Browser: Chrome

**Comment by ckpearson** [comment]
This may actually be down to the markdown receiving weird additional `\` characters at newlines from a multiline literal string. I've since tested it by importing from a markdown file directly as a string and it behaves as expected.

Was able to diagnose this by using the source viewer mode.

**Comment by petyosi** [comment]
> I would expect the plugin to skip over directives it cannot handle and for the editor to then render any following content

That's not how the directives plugin (and the Editor in general) works. It would silently destroy content if it skips unknown constructs. If you expect such content, you can create a catch-all directive descriptor that does some basic rendering but preserves the structure.

Up to your example, one possible problem I see is the indent in the multiline string. However, I doubt that this would work without the catch all descriptor.

**Comment by dogmatic69** [comment]
I've run into something similar, but code blocks with triple backticks. I don't care about a fancy editor, just loading random md content into the editor and basic functionality.

duplicated the above basic example, using what is specified [here](https://mdxeditor.dev/editor/docs/markdown-shortcuts) and I get the same cut off content. ( have tried various combinations of 

    ```
    
    or
    
    ```js (and others)



https://codesandbox.io/p/sandbox/mdx-editor-base-forked-kdj54k?file=%2Fsrc%2FApp.tsx
