### ISSUE TITLE
[BUG] Lexical import error using Astro (Vite)

### ISSUE THREAD

**Issue by smitbarmase** [mdx-editor/editor#375]
If you want to ask for support or request features, [sponsor the project](https://github.com/sponsors/petyosi) and [contact me over email](mailto:petyo@mdxeditor.dev).

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] I have read the documentation and cannot find an answer.

**Describe the bug**
SyntaxError
An error occurred.
Named export '$isElementNode' not found. The requested module 'lexical' is a CommonJS module, which may not support all module.exports as named exports.
CommonJS modules can always be imported via the default export, for example using:

import pkg from 'lexical';
const { $isElementNode } = pkg;
Stack Trace
file:///Users/smitbarmase/site/node_modules/@mdxeditor/editor/dist/exportMarkdownFromLexical.js:1
import { $isElementNode } from "lexical";
         ^^^^^^^^^^^^^^
SyntaxError: Named export '$isElementNode' not found. The requested module 'lexical' is a CommonJS module, which may not support all module.exports as named exports.
CommonJS modules can always be imported via the default export, for example using:

import pkg from 'lexical';
const { $isElementNode } = pkg;

    at ModuleJob._instantiate (node:internal/modules/esm/module_job:132:21)
    at async ModuleJob.run (node:internal/modules/esm/module_job:214:5)
    at async ModuleLoader.import (node:internal/modules/esm/loader:329:24)
    at async nodeImport (file:///Users/smitbarmase/site/node_modules/vite/dist/node/chunks/dep-G-px366b.js:54796:17)
    at async ssrImport (file:///Users/smitbarmase/site/node_modules/vite/dist/node/chunks/dep-G-px366b.js:54696:24)
    at async eval (/Users/smitbarmase/site/src/components/Editor.tsx:4:31)
    at async instantiateModule (file:///Users/smitbarmase/site/node_modules/vite/dist/node/chunks/dep-G-px366b.js:54758:9)

**Reproduction**
[Codesandbox link](https://codesandbox.io/p/devbox/njq54y?migrateFrom=wt4lhd&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522cltfb4ltj00063b6f11o8v9c8%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522cltfb4lti00023b6f2pe3fifx%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522cltfb4lti00043b6flwsmi3e5%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522cltfb4lti00053b6f69x67qk6%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522cltfb4lti00023b6f2pe3fifx%2522%253A%257B%2522id%2522%253A%2522cltfb4lti00023b6f2pe3fifx%2522%252C%2522tabs%2522%253A%255B%255D%257D%252C%2522cltfb4lti00053b6f69x67qk6%2522%253A%257B%2522id%2522%253A%2522cltfb4lti00053b6f69x67qk6%2522%252C%2522tabs%2522%253A%255B%257B%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A4321%252C%2522id%2522%253A%2522cltfbalu700pe3b6fpdahpuna%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522activeTabId%2522%253A%2522cltfbalu700pe3b6fpdahpuna%2522%257D%252C%2522cltfb4lti00043b6flwsmi3e5%2522%253A%257B%2522id%2522%253A%2522cltfb4lti00043b6flwsmi3e5%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522cltfb4lti00033b6f779igon3%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TERMINAL%2522%252C%2522shellId%2522%253A%2522cltfb4m69000bddf8do7rclvf%2522%257D%255D%252C%2522activeTabId%2522%253A%2522cltfb4lti00033b6f779igon3%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

**To Reproduce**
1. Create Astro project
2. Install and import component like this `import { MDXEditor, headingsPlugin } from "@mdxeditor/editor";`
3. `npm run dev`

**Expected behavior**
It should build on dev.

**Screenshots**
<img width="1333" alt="image" src="https://github.com/mdx-editor/editor/assets/37347831/8170789e-51b8-47b3-afd6-1dd4ed021f37">

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: Chrome

**Additional context**

**Comment by smitbarmase** [comment]
Might be related:
https://github.com/vitejs/vite/issues/14332
https://github.com/facebook/lexical/pull/5618

**Comment by petyosi** [comment]
I'm afraid I'm not familiar with the Astro stack to help you with this. Vanilla Vite works out of the box, you can check some of the adjustments that were made for Next and Remix - perhaps this will give you some clue.

**Comment by smitbarmase** [comment]
@petyosi https://github.com/withastro/astro/issues/10353#issuecomment-1983613912 can you look into this?

**Comment by petyosi** [comment]
> @petyosi [withastro/astro#10353 (comment)](https://github.com/withastro/astro/issues/10353#issuecomment-1983613912) can you look into this?

I gave you directions in my previous reply, which you did not take into account.  

If you expect me to support you and find solutions for your technology of choice, sponsor the project.

**Comment by the-wc** [comment]
Thank you for your work here, @petyosi. 

I think this might become a common issue you'll see listed here. This issue isn't isolated to Astro. I've replicated this via `remix-vite`: 

- `vite-plugin-cjs-interop` => same error
- `ClientOnly` via `remix-utils` => same error
- `noExternal` gives a different error, but it's faulty because (as what @smitbarmase references): 

> I don't think this is an Astro issue. When you `noExternal` a dependency in Vite (especially in dev), you're also saying that the dependency is entirely written in ESM, however `@lexical/react` isn't written in ESM, so the issue arises.
> 
> I think we should fix step 1 first (Initial Issue with Named Export), instead of making the rest work. The issue can be replicated by creating a `test.mjs` file with:
> 
> ```js
> import "@mdxeditor/editor";
> ```
> 
> And running `node test.mjs`. The `@mdxeditor/editor` package is not Node-friendly and should be fixed instead.

**Comment by petyosi** [comment]
@the-wc I'm not following the latest development of remix closely, noticed that they're moving to vite. There's a working mdxeditor in remix setup, https://github.com/mdx-editor/mdx-editor-in-remix. As far as I can tell, ClientOnly works as expected. You can fork that example and show me what's going on to help further. 

Up to your quote above, this package is unlikely to be node friendly anytime soon, for a few reasons: 

- Lexical is CJS only
- The markdown utils are ESM only
- And, last, but not least, I see zero sense in rendering it on the server given its function. 

I greatly appreciate effective help and contributions on the matter in the sense of concrete, reproducible issues that take into account the directions I've given so far. "Does not work" and "same error" are not enough, unfortunately.

**Comment by david10sing** [comment]
@petyosi 

I am also getting this issue with a project I am working on and I have pushed a PR to upgrade `lexical`. Hopefully it fixes the problem but it might not be as simple as that and the fix might need to happen in the `lexical` library.

https://github.com/mdx-editor/editor/pull/402

Look forward to any feedback.

Cheers
