### ISSUE TITLE
Question: Using MDXEditor as a replacement for the GitHub's makrdown editor

### ISSUE THREAD

**Issue by Stamo-Gochev** [mdx-editor/editor#378]
Have you tried embedding the editor on GitHub, e.g. using a custom [tampermonkey script](https://www.tampermonkey.net/scripts.php?locale=en) or through a browser extension?

For example, I am using [Github writer](https://chromewebstore.google.com/detail/github-writer/diilnnhpcdjhhkjcbdljaonhmhapadap), but want to try MDXEditor as a replacement. Github writer's [readme](https://github.com/ckeditor/github-writer/blob/master/src/README.md) says it was not that difficult for them, maybe there is an opportunity for MDXEditor to also be provided in some form as an extension.

**Comment by petyosi** [comment]
No, I have not tried that. Their editor has neat contextual features like issue/user autocomplete, which I use a lot.
