### ISSUE TITLE
The "options" parameter of the "BlockTypeSelect" toolbar component

### ISSUE THREAD

**Issue by tolms** [mdx-editor/editor#381]
Are you planning to add an "options" parameter to the "BlockTypeSelect" toolbar component to control elements and their order?
Something like:
{ options: ['quote', 'paragraph', 'heading1', 'heading2'] }

**Comment by petyosi** [comment]
I don't. The component is fairly simple; you can copy/paste [its implementation](https://github.com/mdx-editor/editor/blob/main/src/plugins/toolbar/components/BlockTypeSelect.tsx) to your own custom toolbar component and tweak it as you wish.
