### ISSUE TITLE
[BUG] unable to "control" md code block formatting

### ISSUE THREAD

**Issue by dogmatic69** [mdx-editor/editor#382]
If you want to ask for support or request features, [sponsor the project](https://github.com/sponsors/petyosi) and [contact me over email](mailto:petyo@mdxeditor.dev).

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] I have read the documentation and cannot find an answer.

**Describe the bug**

Unable to control code blocks created from markdown triple back ticks. From a quick look at the code, seems to do internal things that does not pass through any configurations (eg: theme)

**Reproduction**

Simple mardkown setup with code blocks results in black blocks of code (due to "auto" dark theme due to system settings)

**Expected behavior**

I'm using this for non technical use, so I want the code block to be styled more simply but don't seem to be able to do anything related to style for mardkown code blocks.

**Screenshots**
![image](https://github.com/mdx-editor/editor/assets/94674/b9b35b9c-84ad-4522-8b08-e712fa9f4ccc)

**Comment by petyosi** [comment]
This is a missing feature. The code blocks editor has be migrated to a plain codemirror setup (they use the sandpack config), and from there it's fairly easy to make them themeable, like the diff/source editors. 

Happy to accept a PR.

**Comment by dogmatic69** [comment]
Ok, at least I know. Not really familiar with this all so won't be able to make a PR.

**Comment by petyosi** [comment]
This is solved (solved a while back), just missed closing this feature. The codemirror plugin accepts codemirror options, which let you pass a theme plugin of your choice.
