### ISSUE TITLE
[BUG] net::ERR_BLOCKED_BY_ORB when trying to load an image

### ISSUE THREAD

**Issue by StepsOnes** [mdx-editor/editor#388]
I upload pictures to Google Storage, they are publicly available, that is, they are loaded onto the page with a regular tag, but when I insert the picture through the editor, an error occurs

**Comment by petyosi** [comment]
This does not seem to be an error that can be caused by the editor. Use google to find similar issues, perhaps this will give you some more clues on what goes on.
