### ISSUE TITLE
Vitejs SSR not work

### ISSUE THREAD

**Issue by enri90** [mdx-editor/editor#40]
hello we tried to find a solution to make it compatible 
with **vitejs** and **vite-plugin-ssr** but nothing is working can anyone help us?

https://github.com/brillout/vite-plugin-ssr/discussions/1084

**Comment by petyosi** [comment]
I'll take a look today. I've seen similar error related to the diff-view lib in other setups as well, might have to fix it with a fork. 

In general, I think that it's not necessary to render the component from the server. Nevertheless, there should be a working solution for such setup, even if it involves some sort of exclusion.

**Comment by petyosi** [comment]
Here's a [fork of the repo](https://github.com/mdx-editor/MdxEditor-vitejs-ssr) from the discussion above. To avoid duplication, I will discuss the approach in the discussion above, to get the input of the author.
