### ISSUE TITLE
[BUG] Unable to find an active editor state.

### ISSUE THREAD

**Issue by zasuh** [mdx-editor/editor#400]
- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] I have read the documentation and cannot find an answer.

**Describe the bug**
I'm using MDX Editor with Next.js (Pages router) and get the following error in my browser when simply trying to render the editor. Not using any styling or anything else, just trying to render the editor in a component. I've added the necessary code into next config, but it didn't resolve the issue.

`Error: Unable to find an active editor state. State helpers or node methods can only be used synchronously during the callback of editor.update() or editorState.read().`

**Reproduction**

**To Reproduce**

**Expected behavior**
I expect the editor to work as it did before and not crash the page when clicking inside the input.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: Chrome

**Additional context**

**Comment by zasuh** [comment]
Also tried using dynamic imports, same issue

```javascript
const MDXEditor = dynamic(() => import('@mdxeditor/editor').then((mod) => mod.MDXEditor), {
  ssr: false,
});
```

**Comment by petyosi** [comment]
Not sure I follow what you describe. Is this some sort of a regression? Did the error appear after an upgrade? What's different than https://github.com/mdx-editor/mdx-editor-in-next-pages?

**Comment by zasuh** [comment]
The error appeared after upgrading to v2. The only difference between your example and mine is that you are using server components and I'm not, also I'm on pages router.

**Comment by petyosi** [comment]
I have created two sample repos, one with app router and one with pages router. The one I linked specifically is using the pages router. Can you fork it and reproduce the problem there? I'm not going to be able to help you otherwise.

**Comment by Debnathweb** [comment]
Same problem when i am running [https://github.com/mdx-editor/mdx-editor-in-cra](https://github.com/mdx-editor/mdx-editor-in-cra) this example on @nx/react app, client side using "@mdxeditor/editor": "2.18.0" version 
and same example working with this version on cra app

**Comment by petyosi** [comment]
@Debnathweb I'm afraid that I don't understand what you mean, nor I can help without being able to reproduce the problem on my side. Since I have not heard back from @zasuh I'm closing this.

**Comment by Debnathweb** [comment]
i will create a reproduction today

**Comment by Debnathweb** [comment]
this error solved for me, I think this was happening because **lexical** was in the dependencies on my nx repo,
tried other things, but after removing all lexical packages its solved.
