### ISSUE TITLE
Disable image resizing

### ISSUE THREAD

**Issue by jaijuneja** [mdx-editor/editor#410]
Hi there,

I'm working with both MDX Editor and React Markdown and am running into issues with the <img> tag from resized images not being correctly parsed (MDX Editor handles this gracefully/as expected, but React Markdown does not unless I use specific plugins). I would prefer if the regular image markup ![]() not be converted to <img> tags.

To solve this and reduce complexity I'd like to disable the ability for the end-user to resize images in the editor. Is there an easy way to achieve this?

This is an awesome project and by far the best Markdown editor I've worked with - thank you!

**Comment by petyosi** [comment]
The image plugin accepts `disableImageResize` option.
