### ISSUE TITLE
[BUG] Cursor bug after deleting a paragraph before/after a table.

### ISSUE THREAD

**Issue by ajboni** [mdx-editor/editor#420]
Hi, this is a bit hard to explain, if you open the demo at https://mdxeditor.dev/editor/demo and replace the content with this table:
```
| 1 | 2 | 3 |
| - | - | - |
| a | b | c |
| e | e | f |
```

then go back to editing mode and delete the empty paragraph after the table. The user is unable to enter text either before or after the table. in this particular example,  they cannot edit the document any more. 

![image](https://github.com/mdx-editor/editor/assets/12578313/45b03a3d-c2c6-4783-8062-f81efa48374b)

### Workarounds
Inerting an image or a link

**Comment by petyosi** [comment]
@ajboni that's a fair point, but I have no definitive idea on how to address this in an elegant way. One approach would be to always keep a paragraph at the bottom, if the last node is a decorator (table, code block, etc). This should be doable with Lexical. I will think about this.

**Comment by petyosi** [comment]
I have done something here, for the "after" part. The before part is not so trivial, I'm afraid. Google docs seems to always keep a paragraph above the table, for example.

**Comment by ajboni** [comment]
Works great! I think the "after" part is the most common case, thank you!
