### ISSUE TITLE
[BUG] Link dialog can't be opened even if editor is not in readonly mode

### ISSUE THREAD

**Issue by jpreis** [mdx-editor/editor#421]
**Describe the bug**
The popover for editing, copying and removing a link does not appear, even when the editor is not in `readonly` mode.

**To Reproduce**
1. Go to https://mdxeditor.dev/editor/demo
2. Click on the _Daring Fireball_ link

This was introduced in [v2.20.2](https://github.com/mdx-editor/editor/releases/tag/v2.20.2), probably with the fix for #418.

Tested in macOS in Chrome, Firefox and Safari.

**Comment by haralddietrich** [comment]
Link Dialog does not appear on [Release 3.21.0](https://github.com/mdx-editor/editor/releases/tag/v3.21.0) again

**Comment by petyosi** [comment]
@haralddietrich it works for me - can you elaborate?

**Comment by petyosi** [comment]
Got it, it's the toolbar button. https://github.com/mdx-editor/editor/issues/681

**Comment by haralddietrich** [comment]
Correct. If I select a text and hover over the toolbar button, nothing happens. If I select a link I'm the page and click on the edit button in the pop-up, the edit dialog is displayed.
