### ISSUE TITLE
[BUG] Cannot rename sandpack snippetFileName

### ISSUE THREAD

**Issue by kennarddh** [mdx-editor/editor#425]
If you want to ask for support or request features, [sponsor the project](https://github.com/sponsors/petyosi) and [contact me over email](mailto:petyo@mdxeditor.dev).

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] I have read the documentation and cannot find an answer.

**Describe the bug**

Cannot change `snippetFileName` in  [SandpackPreset](https://mdxeditor.dev/editor/api/interfaces/SandpackPreset) to value other than `/App.js`

This bug only happen if `snippetFileName` is not `/App.js`

**Reproduction**
Start from https://codesandbox.io/p/sandbox/mdx-editor-base-q8s7zr?file=/src/App.tsx to reproduce the problem so that I can observe the issue on my side and make sure that the fix reliably addresses it.

https://codesandbox.io/p/sandbox/mdx-editor-base-forked-g3wymh?file=/src/App.tsx

**To Reproduce**
1. Create sandpack component
2. See it has 2 files. one with the name in the config and `App.js`. The default one is the only one that is editable.

**Expected behavior**
It should only has 1 file as the config and it should be editable.

**Screenshots**
![image](https://github.com/mdx-editor/editor/assets/79390992/52bccf98-59b6-48d2-baeb-e2089b26bad2)

**Desktop (please complete the following information):**
 - OS: Windows - Windows can act funny sometimes.
 - Browser: Chrome

**Additional context**

**Comment by petyosi** [comment]
I think this might be related to sandpack and its templates, can you make this work with sandpack itself outside of the MDXEditor?

**Comment by petyosi** [comment]
@kennarddh did you figure this out?

**Comment by kennarddh** [comment]
no, not yet.
