### ISSUE TITLE
[BUG] Mask id not unique

### ISSUE THREAD

**Issue by IMBeniamin** [mdx-editor/editor#426]
If you want to ask for support or request features, [sponsor the project](https://github.com/sponsors/petyosi) and [contact me over email](mailto:petyo@mdxeditor.dev).

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] I have read the documentation and cannot find an answer.

**Describe the bug**
The mask id declared for the editor icon is not unique and causes issues when having multiple instances of which one is hidden

**Reproduction**
[codesandbox link](https://codesandbox.io/p/sandbox/mdx-editor-base-q8s7zr?file=%2Fsrc%2FApp.tsx&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clv6dhjak0007356mqg0xtrkn%2522%252C%2522sizes%2522%253A%255B100%252C0%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clv6dhjaj0003356mr3votc2l%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clv6dhjak0004356mht4l2owl%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clv6dhjak0006356mndxlepxu%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clv6dhjaj0003356mr3votc2l%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clv6dhjaj0002356mw683uce9%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fsrc%252FApp.tsx%2522%257D%255D%252C%2522id%2522%253A%2522clv6dhjaj0003356mr3votc2l%2522%252C%2522activeTabId%2522%253A%2522clv6dhjaj0002356mw683uce9%2522%257D%252C%2522clv6dhjak0006356mndxlepxu%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clv6dhjak0005356m7164zxr8%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522clv6dhjak0006356mndxlepxu%2522%252C%2522activeTabId%2522%253A%2522clv6dhjak0005356m7164zxr8%2522%257D%252C%2522clv6dhjak0004356mht4l2owl%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522clv6dhjak0004356mht4l2owl%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Afalse%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

**To Reproduce**
1. Create at least 2 editor instances
2. Change the visibility of the first instance
3. Enjoy the extra blank space instead of the buttons in the second editor

**Expected behavior**
Icons should be visible on all instances even if one or more instances are hidden

**Screenshots**
![image](https://github.com/mdx-editor/editor/assets/35833890/f17caae5-de84-4b59-9c62-037262234916)
![image](https://github.com/mdx-editor/editor/assets/35833890/8d80bde5-ff63-45a1-900f-3160cc272fc2)
![image](https://github.com/mdx-editor/editor/assets/35833890/2ce04f64-1066-406f-981a-529ec616ea19)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Chrome

**Additional context**
Refer to [this issue on devexpress's support forum for the original troubleshooting](https://supportcenter.devexpress.com/ticket/details/t1228017/second-instance-of-mdxeditor-s-component-inside-a-tabeditor-s-tab-has-no-icons-in-the)

**Comment by petyosi** [comment]
I think I explored this at some point, it's a matter of svgr configuration. Happy to accept a PR. On a side note, it's great that you're a devexpress customer. A sponsorship of the MDXEditor project would help me to prioritize my work on problems like this one and further feature development.

**Comment by david10sing** [comment]
@petyosi 

I tried to have look at this and not sure that SVGR config would help here.

We could force visibility on `mask` elements to alway be visible with `!important` to avoid `visibility: hidden` being inherited.

If we want really unique ids for each instance of the svg, then it would require a bit of time.

Thoughts on which path you would prefer?

Cheers

**Comment by petyosi** [comment]
@david10sing I'm even thinking about using spritesheet for the icons, some authors mention it as more performant. 

Alternatively, I can rework the icons to not use masks, but this would require a bit of leveling up of my figma skills :).

**Comment by david10sing** [comment]
Thanks @petyosi 

I was wondering too why the mask was needed...
