### ISSUE TITLE
[BUG]: Nested Admonitions

### ISSUE THREAD

**Issue by lebalz** [mdx-editor/editor#428]
If you want to ask for support or request features, [sponsor the project](https://github.com/sponsors/petyosi) and [contact me over email](mailto:petyo@mdxeditor.dev).

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] I have read the documentation and cannot find an answer.

**Describe the bug**
A valid MDX with [nested Admonitions](https://docusaurus.io/docs/markdown-features/admonitions#nested-admonitions) is displayed correctly, but it can not be created over the toolbar - no option to insert a new admonition when the focus is already inside a admonition.

**Reproduction**
Start from https://codesandbox.io/p/sandbox/mdx-editor-base-q8s7zr?file=/src/App.tsx to reproduce the problem so that I can observe the issue on my side and make sure that the fix reliably addresses it.

**To Reproduce**
1. Go to https://mdxeditor.dev/editor/demo
2. Go to the diff' viewer
3. Insert a nested admonition, e.g. the one from here https://docusaurus.io/docs/markdown-features/admonitions#nested-admonitions
4. Switch back to the Richt Text Mode and see that it works
5. Focus inside an Admonition
6. Bug: the toolbar does not show the option to insert another admonition

**Expected behavior**

Step 6: Would be wonderful to insert nested admonitions :)

**Screenshots**
<img width="937" alt="image" src="https://github.com/mdx-editor/editor/assets/22354689/ba6c2dc0-3d10-4c66-8834-fa00b9bacb38">

**Desktop (please complete the following information):**
 - OS: Windows.
 - Browser Chrome, Edge, Firefox

**Additional context**

**Comment by petyosi** [comment]
This is an intentional design of the toolbar item; a nested admonition UI can easily get messy. You can easily do a toolbar item that does what you describe if you want to, just follow the source of the current one.
