### ISSUE TITLE
getting duplicate react errors when importing the package

### ISSUE THREAD

**Issue by sarah-finley** [mdx-editor/editor#453]
- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] I have read the documentation and cannot find an answer.

im getting a duplicate react error (im running on v17 but seems like there's dev dependency for react 18)...

not sure if this is related, but even though it compiles i get this error as well `react__WEBPACK_IMPORTED_MODULE_0__.useSyncExternalStore is not a function`

is the only solution migrating to react 18?

**Comment by petyosi** [comment]
Yes, you need to upgrade.
