### ISSUE TITLE
[BUG] Sublists are created with 3 spaces

### ISSUE THREAD

**Issue by kathriciya** [mdx-editor/editor#455]
Hey and thanks for the awesome library!

Nested lists are created with 3 spaces, while they should be created with 4 spaces (https://spec.commonmark.org/0.31.2/)
Please fix it.

![1](https://github.com/mdx-editor/editor/assets/60149375/653f80a7-2e75-4c14-900e-80b125c3a403)
![2](https://github.com/mdx-editor/editor/assets/60149375/d35ac7e4-2f10-4bb0-8b1f-5aad90d9afa0)

**Comment by petyosi** [comment]
There seems to be some argument around the right spacing over the internet. 

However, you can control the spacing for the indentation through the `toMarkdownOptions`, which accepts this: https://github.com/syntax-tree/mdast-util-to-markdown#options.
