### ISSUE TITLE
[BUG] Link URL/Title editing doesn't work

### ISSUE THREAD

**Issue by amarijano** [mdx-editor/editor#464]
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] I have read the documentation and cannot find an answer.

**Describe the bug**
If you try editing the link URL or Title after first adding it, it doesn't work. 

**Reproduction**
Can be reproduced in the demo

**To Reproduce**
1. Create a link by adding an URL and a Title
2. Click on the link and click on "Edit link URL" icon
4. Edit the URL and/or the Title
5. Save changes and click away

**Expected behavior**
It should update the previous URL and/or Title with the just saved ones

**Desktop (please complete the following information):**
 - OS:  Windows
 - Chrome, Edge

**Comment by xenokratos** [comment]
Hello

I had the same issue, so I bumped to version 3.3.5 of the editor.

The issue is still present, the link is updated in the markdown, but the `LinkDialog` component doesn't display the updated title.

It can be reproduced in the demo.
