### ISSUE TITLE
[BUG] Can't directly copy paste an image

### ISSUE THREAD

**Issue by amarijano** [mdx-editor/editor#465]
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] I have read the documentation and cannot find an answer.

**Describe the bug**
In the latest version you can't just copy paste an image. You have to go through the image plugin and enter a link there.
Not sure which was the latest version which had it working, but 3.0.7 works fine.

short videos below

 - OS: Windows
 - Browser Chrome

3.0.7

https://github.com/mdx-editor/editor/assets/95140098/2e0cb5b1-a9e1-4368-932d-be0170aea81b

3.3.5

https://github.com/mdx-editor/editor/assets/95140098/13bbcb83-f631-4074-b640-8ee2a670c7ac

**Comment by petyosi** [comment]
I can't seem to reproduce the problem in the site demo and in the examples, any further hints?

**Comment by amarijano** [comment]
I'll try getting more info/updating the issue in the next few days

**Comment by petyosi** [comment]
@amarijano did you discover anything? Let me know, closing in the meantime.
