### ISSUE TITLE
No way to disable "underline" entirely

### ISSUE THREAD

**Issue by deymundson** [mdx-editor/editor#467]
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] I have read the documentation and cannot find an answer.

**Describe the bug**
I am attempting to configure the editor to support only a sub-set of possible markdown. One of the features I would like to remove is the ability to underline text. I was able to use the toolbar primitives to create a custom formatting toggle that only includes Bold and Italic buttons, and was able to ensure HTML cannot be used by setting `suppressHtmlProcessing={true}`, however, it is still possible to underline text by selecting the text and hitting `Ctrl-U`. The markdown produced then includes `<u>text</u>`, even though `suppressHtmlProcessing` is `true`.

**Expected behavior**
I'm not entirely sure what the correct fix for this would be... a couple options I can think of would be:
1. Ensure `<u></u>` cannot be produced when `suppressHtmlProcessing` is `true`.
2. Add an `options` prop to the `BoldItalicUnderlineToggles`, much like the `ListsToggle`, and then only enable the keyboard shortcuts for those options selected.

**Comment by petyosi** [comment]
You can achieve this with your own plugin - you need to register two things, basically:
- An mdast visitor with a higher priority than the default one which "drops" the `u` tag when encountered
- A high priority Lexical command that handles ctrl/cmd+u and stops the underline formatting

Refer to the docs for more details on the matter. 

As a general note: the toolbar is an "accessory"; its contents are by no means hard-bound to the editor capabilities, nor they can enable or restrict certain behavior.

**Comment by wouterlemcke** [comment]
I need this as well. I've been struggling with it for a day now, but cannot really put the pieces together from the docs.
Could you provide me/us with an example?

**Comment by evadecker** [comment]
Bumping this, feels like a common use case! I don't want to allow users to set underlines since they're easily confused with links. Could you add an example to the docs, or provide an easy way to disable this natively?

**Comment by haruntuncay** [comment]
After playing with stuff for quite some time, I managed to get something working. 
Note: I haven't tested it deeply, but seems to work fine for basic markdown features.
Sharing it since it could be a good starting point for customizing based on your own needs.

```
 <MDXEditor
        plugins={[
           ...
           customDisableUnderlinePlugin()
        ]} 
          ...
/>

```

```
import { createRootEditorSubscription$, realmPlugin } from '@mdxeditor/editor';
import { COMMAND_PRIORITY_CRITICAL, FORMAT_TEXT_COMMAND, TextNode } from 'lexical';

const IS_UNDERLINE = 0b1000 as const;

export const customDisableUnderlinePlugin = realmPlugin({
  init(realm) {
    realm.pub(createRootEditorSubscription$, (lexicalEditor) => {
      return lexicalEditor.registerCommand(
        FORMAT_TEXT_COMMAND,
        (payload) => {
          if (payload === 'underline') {
            return true;
          }
          return false;
        },
        COMMAND_PRIORITY_CRITICAL,
      );
    });

    realm.pub(createRootEditorSubscription$, (lexicalEditor) => {
      return lexicalEditor.registerNodeTransform(TextNode, (textNode) => {
        if ((textNode.getFormat() & IS_UNDERLINE) !== 0) {
          textNode.setFormat(textNode.getFormat() & ~IS_UNDERLINE);
        }
      });
    });
  },
});

```
