### ISSUE TITLE
[BUG] when a content has '{}' chars，editor appears errors with jsxPlugin.

### ISSUE THREAD

**Issue by samuelhsin** [mdx-editor/editor#470]
If you want to ask for support or request features, [sponsor the project](https://github.com/sponsors/petyosi) and [contact me over email](mailto:petyo@mdxeditor.dev).

- [O] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [O] I have read the documentation and cannot find an answer.

**Describe the bug**
hen a content has '{}' chars，editor appears errors with jsxPlugin.

The source code is below:
| 1 | 2 | 3 | 4 |
| ----------------------------------------------------------------------------------------------------- | ----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- | ----------------------------------------- | --------- |
| {"a":"test"} | {"a":"test"} | 1234 | 1234 |

and rich mode appears parsing expression errors.

Error parsing markdown: Could not parse expression with acorn.
You can fix the errors in source mode and switch to rich text mode when you are ready.

**Screenshots**
![20240525143952](https://github.com/mdx-editor/editor/assets/359282/a8f037bd-4720-4817-a554-c60ad6f41d9d)

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: Chrome

**Comment by petyosi** [comment]
That's expected I believe. These are treated as JSX expressions.

**Comment by samuelhsin** [comment]
I comment the code:
```
 [addSyntaxExtension$]: mdxjs(),
```
 and works.
