### ISSUE TITLE
[BUG/INQUIRY] Ordered Lists always start with 1

### ISSUE THREAD

**Issue by codingpufferfish** [mdx-editor/editor#471]
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] I have read the documentation and cannot find an answer.

**Describe the bug**
When you initiate a numbered list in the editor with a number other than 1, it appears as if the numbering starts from that specified value. However, in the source mode, the list still begins with 1. Upon saving and reloading the entered content, the displayed list resets to start from 1, regardless of the initial number entered because the source content is saved.

I am aware that ordered lists starting with anything but 1 was not intended in the default markdown specifications developed by John Gruber. However other implementations like GitHub-Flavored Markdown added this functionality. See here: https://github.github.com/gfm/#lists

Depending on what is intended the bug is either showing the wrong value in the Rich text or starting the list in source mode with the intended value.

**Reproduction**
Found and reproduced in the [Live demo](https://mdxeditor.dev/editor/demo)

**To Reproduce**
1. Go to https://mdxeditor.dev/editor/demo
2. Delete everyting
3. Start a new ordered list by entering 3. and [space]
4. Change to source mode
5. Compare display value of rich text and value in source mode

**Expected behavior**
Either display the new list with the intended value and also save that in source mode, or start the list in the rich text editor with 1 aswell

**Screenshots**
![image](https://github.com/mdx-editor/editor/assets/166371080/db7be224-d75c-473a-bf51-e7bd86a21fd9)
List starting with 3 in rich text

![image](https://github.com/mdx-editor/editor/assets/166371080/a1f8c2ae-286b-49d4-abc6-0fce8f3c120b)
same list but in source mode

![image](https://github.com/mdx-editor/editor/assets/166371080/75e817e6-e65d-453b-b8f9-c466e1eb500f)
what happens to the list after copying the source, reloading and pasting into source again

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Tested on Chrome, Firefox, Opera and Edge

**Comment by petyosi** [comment]
I think that the mdast converter has an option on how to export numeric lists; you can find if this is so and pass it to the component options.

**Comment by xueerli** [comment]
@petyosi 
I configured it as follows, but it doesn't work. Can you tell me how to configure it?
```
toMarkdownOptions={{
    incrementListMarker: false
}}
```
