### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by OSokunbi** [mdx-editor/editor#478]
- [X ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [ X] I have read the documentation and cannot find an answer.

Description
When using the image plugin with the MDXEditor component, backslashes are being added to the Markdown syntax for images. This causes issues with image rendering and prevents proper functionality of the image plugin.

Reproduction
To reproduce the issue:

[Reproduce](https://codesandbox.io/p/sandbox/mdx-editor-base-q8s7zr?file=/src/App.tsx)

To reproduce you can:

Use the MDXEditor component with the image plugin enabled.
Attempt to insert an image using the Markdown syntax (![](<image_url>)).
Console log the output of the onChange event handler to observe the presence of backslashes in the Markdown syntax.

While the image appears normally inside of the contentEditable it really has backslashes, preventing it from being rendered properly
Desktop

OS: Windows
Browser: Chrome

**Comment by petyosi** [comment]
I feel like you're misunderstanding the purpose of the editor component. You're not supposed to write markdown formatting in the rich text area. However, the explanation you're giving is unclear to me, I'm afraid.
