### ISSUE TITLE
[HELP] How to set the language?

### ISSUE THREAD

**Issue by WatanabeThiago** [mdx-editor/editor#480]
Hi!

How can I set the language?

Like "pt-BR", etc

I need an example.

Thanks for attention.
![image](https://github.com/mdx-editor/editor/assets/50850299/c08041cb-6f68-40ec-b2a9-f39bf3f9e666)

**Comment by petyosi** [comment]
Check the [I18n section](https://mdxeditor.dev/editor/docs/i18n) of the docs.
