### ISSUE TITLE
May I disable mdx parser. In my application I don't need to parse mdx componet.

### ISSUE THREAD

**Issue by tfmukles** [mdx-editor/editor#482]
**Is your feature request related to a problem? Please describe.**
In my application, I do not need to parse MDX components. Having the MDX parser enabled increases the complexity and overhead, which is unnecessary for my use case.

**Describe the solution you'd like**
I would like an option to disable the MDX parser entirely. This could be a configuration option in the settings where users can choose to enable or disable MDX parsing based on their needs.

**Describe alternatives you've considered**
Currently, there is no straightforward way to disable the MDX parser, which forces the application to handle unnecessary MDX parsing.

**Additional context**
Disabling the MDX parser would improve performance and reduce complexity for applications that do not utilize MDX components. This feature would make the application more versatile and adaptable to different use cases.

Thank you for considering this feature request.

**Comment by petyosi** [comment]
Can you be more concrete when you refer to performance, overhead and complexity? What kind of problems do you experience?
