### ISSUE TITLE
[BUG] Using directivesPlugin({ directiveDescriptors: [AdmonitionDirectiveDescriptor] }) captures to wildly

### ISSUE THREAD

**Issue by pbjorklund** [mdx-editor/editor#486]
Using [admonitions plugin](https://mdxeditor.dev/editor/docs/Admonitions) seems to match markdown strings like "1:a" (which means the first of) in Swedish.

Shouldn't it only trigger on ::: or at least using ::: on newline?

**Comment by petyosi** [comment]
`:a` is still a directive and is still recognized as such, text directive to be more precise. One possible solution for the visitor would be to somehow compile unmatched directives to their plaintext equivalent and insert a text node. You can give this a try and submit a PR.

**Comment by pbjorklund** [comment]
Solved it by simply not using it. Left an issue as ref for anyone else encountering since it took me a while to figure out what was happening. But seems like working as intended so will close.
