### ISSUE TITLE
[BUG] plain text with colon causes parsing error

### ISSUE THREAD

**Issue by johnxu16** [mdx-editor/editor#509]
If you want to ask for support or request features, [sponsor the project](https://github.com/sponsors/petyosi) and [contact me over email](mailto:petyo@mdxeditor.dev).

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] I have read the documentation and cannot find an answer.

**Describe the bug**
colon has to be escaped

Ex. 
❌ "foo:bar"
✅ "foo\:bar"

**Reproduction**
Start from https://codesandbox.io/p/sandbox/mdx-editor-base-q8s7zr?file=/src/App.tsx to reproduce the problem so that I can observe the issue on my side and make sure that the fix reliably addresses it.

**To Reproduce**
1. Go to https://mdxeditor.dev/editor/demo
2. Click into source mode
3. Input text "foo:bar"
4. Toggle back to rich-text mode
6. See error

**Expected behavior**
foo:bar rendered as plain text

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. MacOS, Windows] - Windows can act funny sometimes.
 - Browser [e.g. Chrome, Safari]

**Additional context**

**Comment by petyosi** [comment]
That's treated as a markdown directive. If you're not going to use those, just disable the plugin.
