### ISSUE TITLE
[BUG] Bulletted list, Numbered list and check list are not working inside tables

### ISSUE THREAD

**Issue by sanuradhag** [mdx-editor/editor#511]
Can not insert a bulleted list, numbered list, or a checklist inside a table cell.

**Comment by petyosi** [comment]
How would that look in markdown? Not sure that the table syntax supports nesting block elements in the table cells.

**Comment by petyosi** [comment]
But is this a markdown that a vanilla markdown parser (e.g. the GitHub comment box) would understand?

**Comment by petyosi** [comment]
Closing this. I don't think that block content can be nested in table cells. https://stackoverflow.com/questions/19950648/how-to-write-lists-inside-a-markdown-table
