### ISSUE TITLE
Create Link and highlight functionality

### ISSUE THREAD

**Issue by jakkub21** [mdx-editor/editor#513]
Hey

im trying to use React Semantic UI component [Modal](https://react.semantic-ui.com/modules/modal/) to implement form with mdx editor.

As you can see on the screen below i got this situation where "highlight" box is out of his alignment and also dialog box for editing/creating links:
![image](https://github.com/mdx-editor/editor/assets/53193386/f47b31f0-3705-4e2d-8e98-c3f9aaee1778)

I was wondering if there is anyone that was using Semantic UI with this package. I tried mdx-editor outside of semantic ui modal component and its working properly... so i would say its something to do with positioning.

Is there any way to handle alignment with custom functionality? Or is there any workaround?

I had problem with z-index and those dialog boxes were not even rendered in Semantic UI modal... but i handled it by using css:
```
._popupContainer_yms4a_1220 {
    z-index: 1901 !important;
}

.modal .content ._linkDialogAnchor_yms4a_586 {
    z-index: 1900 !important;
}

**Comment by petyosi** [comment]
I have no idea. Given that it's Semantic UI breaking the editor (and not the other way around), I would recommend bringing this to the Semantic UI community.

**Comment by jakkub21** [comment]
I manage to fix it, if anyone has the same problem: 
https://github.com/Semantic-Org/Semantic-UI-React/issues/4486#issuecomment-2217777635
