### ISSUE TITLE
vim plugin?

### ISSUE THREAD

**Issue by ChristianChiarulli** [mdx-editor/editor#514]
Is there already or plans to create a plugin for vim support/emacs keybinds?

**Comment by petyosi** [comment]
I don't have such plans at the moment, but perhaps there's an ongoing effort for vim/emacs support for Lexical - if so, it should be easy to plug it in. Given the Lexical extensibility model, I would not be surprised if someone has done it. 

Cheers from a fellow (neo)vim user.
