### ISSUE TITLE
[BUG] onChange is not fired when inserting new white line

### ISSUE THREAD

**Issue by wouterlemcke** [mdx-editor/editor#518]
We do some comparison when the markdown is changed. We need to know what happend. For that we compare the old (state) value with the new one.

However we noticed then when you insert one or multiple white lines (hitting enter-key), the onChange is not fired.
When you then continue typing regular stuff, the whitelines are part of the markdown (as they should).

I would expect the onChange to fire for really every change you (can) make

**Comment by petyosi** [comment]
The component automatically trims its content when emitting the change - in general, this should not be a problem, because the markdown parsers would yield the same result, but I might be wrong here. How is that affecting you?

**Comment by wouterlemcke** [comment]
We're implementing tagging / mentioning (like https://github.com/signavio/react-mentions), but then also supporting a range of other mark down elements.

On change we compare the old state with the new text to see what you changed. If the new char is a `@`, we open the taggable user list. However because the onchange is not fired for the white lines, when you type any char after the white lines it still detects the white line as the new char.

Probably there are better ways of doing this, but after wrestling with plugins and lexical for more then 2 days I gave up and started implement it like this. It works perfectly for us, except for this white line issue

**Comment by wouterlemcke** [comment]
the `ref.getMarkDown()` also returns the text trimmed. I get the idea and in most situations it's probably fine, but for us it's an issue right now 😅

**Comment by petyosi** [comment]
You should be using the Lexical API for that purpose. I think they have a nice example of mentions in the playground that you can start with.

**Comment by itsanishjain** [comment]
Hey @wouterlemcke Did you find the answer to this "firing onChange when you hit enter" for newline

How this behaviour makes any changes because to me expected thing is I added a new line I want it so I can properly show my content
