### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by sadrakmorais** [mdx-editor/editor#523]
If you want to ask for support or request features, [sponsor the project](https://github.com/sponsors/petyosi) and [contact me over email](mailto:petyo@mdxeditor.dev).

- [x ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [ x] I have read the documentation and cannot find an answer.

**Describe the bug**
When creating a link in the MDX Editor, the link encompasses the entire line regardless of the selection. Even if only a part of the line is selected, the resulting link covers the whole line.

**To Reproduce**
1. Open the MDX Editor.
2. Type a line of text.
3. Select a part of the text on that line.
4. Use the functionality to create a link.

**Expected behavior**
The link should only be applied to the selected text, not the entire line.

**Screenshots or GIFs**
![screencast-from-2024-07-03-16-56-39_FkJOsB5l](https://github.com/mdx-editor/editor/assets/71346403/8f2e5b64-0527-422a-97b4-913928b556a1)

**Additional information**
- MDX Editor version: 3.0.1
- Operating system: Ubuntu 24.04
- Browser (if applicable): Chrome 

**Additional context**

**Comment by petyosi** [comment]
This should be solved in the latest version.
