### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by aks318** [mdx-editor/editor#530]
If you want to ask for support or request features, [sponsor the project](https://github.com/sponsors/petyosi) and [contact me over email](mailto:petyo@mdxeditor.dev).

- [ ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [ ] I have read the documentation and cannot find an answer.

**Describe the bug**
For <ListsToggle /> , when you press tab  you get (TypeError: Cannot read properties of undefined (reading 'children').

**Reproduction**
Start from https://codesandbox.io/p/sandbox/mdx-editor-base-q8s7zr?file=/src/App.tsx to reproduce the problem so that I can observe the issue on my side and make sure that the fix reliably addresses it.

**To Reproduce**
1. Choose any list type from ListsToggle.
2. Then click tab.
3. Check the console for the error

**Expected behavior**
Should not allow the extra tab for list items

**Screenshots**
![image](https://github.com/mdx-editor/editor/assets/41566374/32df04cd-6376-4983-bd3d-4955766b9e48)

**Desktop (please complete the following information):**
 - OS:  Ubuntu.
 - Browser: Chrome

**Comment by petyosi** [comment]
duplicate: https://github.com/mdx-editor/editor/issues/178.

**Comment by aks318** [comment]
@petyosi When are you going to plan. Any estimates?
