### ISSUE TITLE
[BUG] in read-only mode -> in table -> in first row -> only last cell doesn't have border styling

### ISSUE THREAD

**Issue by swanITworks** [mdx-editor/editor#532]
If you want to ask for support or request features, [sponsor the project](https://github.com/sponsors/petyosi) and [contact me over email](mailto:petyo@mdxeditor.dev).

- [x ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [ x] I have read the documentation and cannot find an answer.

**Describe the bug**
in read-only mode -> in table -> in first row -> only last cell doesn't have border styling

**Reproduction**

https://codesandbox.io/p/sandbox/mdx-editor-base-forked-gjtppm

<img width="714" alt="Screenshot 2024-07-10 at 10 28 06" src="https://github.com/mdx-editor/editor/assets/45924569/232c1a95-e34f-4251-9511-99ceaf1e6e78">

**Expected behavior**
Last cell in first row in read-only mode should have border styling

**Screenshots**
 readOnly={true}

<img width="1190" alt="Screenshot 2024-07-10 at 08 42 17" src="https://github.com/mdx-editor/editor/assets/45924569/4ffd79e0-5caf-40ee-9854-78223775b0a1">

 readOnly={false}
<img width="1065" alt="Screenshot 2024-07-10 at 08 42 50" src="https://github.com/mdx-editor/editor/assets/45924569/1bfd8927-3c74-4087-b0de-d9cfc926ebca">

**Comment by denisvely** [comment]
any update on this?

**Comment by petyosi** [comment]
@denisvely should be a simple fix - happy to accept a PR.

**Comment by swanITworks** [comment]
Thanks, guys it works now!
