### ISSUE TITLE
Suggestion: Arrow in link dialogue popover should be `var(--baseBg)` instead of `var(--basePageBg)`

### ISSUE THREAD

**Issue by tatounee** [mdx-editor/editor#539]
I think it's more readable and make theming easier if the little arrow of the link dialogue popover is `var(--baseBg)` instead of `var(--basePageBg)`.

![popover before after](https://github.com/user-attachments/assets/5cfefb4e-c4a8-432c-bca6-3b3676f5e9db)

**Comment by petyosi** [comment]
Thank you for sharing your opinion. Feel free to adjust this in your instance, should be fairly straightforward.
