### ISSUE TITLE
[BUG] Typing email address with three domain segments, auto-link leaves editor in broken state

### ISSUE THREAD

**Issue by mrcrowl** [mdx-editor/editor#542]
If you want to ask for support or request features, [sponsor the project](https://github.com/sponsors/petyosi) and [contact me over email](mailto:petyo@mdxeditor.dev).

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] I have read the documentation and cannot find an answer.

**Describe the bug**
Typing an email address with more than two domain levels leaves the editor in a broken state (e.g. `test@telstra.com.au`) due to auto-link plugin.

**To Reproduce**
1. Go to https://mdxeditor.dev/editor/demo
2. Insert a cursor on a new line.
3. Start typing an email address with more than three domain segments (e.g. `test@telstra.com.au`)
4. When the `.com` part is typed the email is "auto-linked".
5. After continuing to type `.au` the backspace key no longer works (it selects the text instead of removing).
6. Console shows errors (on a local build, the errors are similar to this):
```
    Error: Expected node 13 to have a parent.
    at _TextNode.getParentOrThrow (Lexical.dev.mjs:3460:15)
    at $shouldInsertTextAfterOrBeforeTextNode (Lexical.dev.mjs:1032:23)
    at $shouldPreventDefaultAndInsertText (Lexical.dev.mjs:2398:3)
    at Lexical.dev.mjs:2689:34
    at $beginUpdate (Lexical.dev.mjs:8093:5)
    at updateEditor (Lexical.dev.mjs:8169:5)
    at onBeforeInput (Lexical.dev.mjs:2607:3)
    at Lexical.dev.mjs:2344:61
    at HTMLDivElement.<anonymous> (Lexical.dev.mjs:3163:9)
```

**Expected behavior**
After typing `.au` the full email address should have been converted into a link, and the editor state should remain editable.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser: Chrome

**Comment by petyosi** [comment]
This is entirely a Lexical behavior, have you searched for a similar problem on their side?

**Comment by mrcrowl** [comment]
The same test works correctly on the lexical playground site: https://playground.lexical.dev/

**Comment by petyosi** [comment]
Searching for issues in their repo found this - https://github.com/facebook/lexical/issues/6430. 

Since this will be fixed once Lexical releases a new version, I will close this issue.

**Comment by mrcrowl** [comment]
facebook/lexical has now release [v0.17.0](https://github.com/facebook/lexical/releases/tag/v0.17.0). Is there a rough timeframe for when this update be included in mdx-editor?
