### ISSUE TITLE
[Suggestion] - A few suggestions to improve dev experience

### ISSUE THREAD

**Issue by ungureanustefan** [mdx-editor/editor#543]
- insertion at cursor position doesn’t follow the style. So if I want to insert a text inside bold markdown, my text will always be inserted in plain text with no styling
- No straightforward way to extract selection coordinates from the editor. So if I want to open a modal at text selection, I can't find a way to do it.
- While the online example styles the text, apparently the editor has to be styled for the headers (h1, h2, h3 etc.) as at the moment the plugin doesn’t change the shape of the text into a header when I try it, it just keeps it as normal text
- It doesn’t have a text-colour plugin

**Comment by petyosi** [comment]
Hey, thanks for your suggestions. I'm afraid that they are too broad or vague for me to understand what you mean. Feel free to fork and modify the project up to your needs. Also, browse the other issues, as I believe most of what you've described has already been discussed.

**Comment by ungureanustefan** [comment]
Hi @petyosi

Thank you for your prompt answer!

I'll leave more details below just in case they will be considered for a future release:

1. _insertion at cursor position doesn’t follow the style. So if I want to insert a text inside bold markdown, my text will always be inserted in plain text with no styling_

<img width="873" alt="image" src="https://github.com/user-attachments/assets/b2ca498a-7b99-49da-901c-da803381494f">

When I inserted the text, it didn't follow the styling of where I've inserted it.

2. _No straightforward way to extract selection coordinates from the editor. So if I want to open a modal at text selection, I can't find a way to do it.
_ . I want to select a text and open a modal where the text was selected, but I can't find any way of doing so. I would like to be able to do it as follows:

<img width="1237" alt="image" src="https://github.com/user-attachments/assets/78b12d1f-5da0-462e-ad07-43b1cce284b2">

I know that the link plugin is doing it, but no idea how.

3. _While the online example styles the text, apparently the editor has to be styled for the headers (h1, h2, h3 etc.) as at the moment the plugin doesn’t change the shape of the text into a header when I try it, it just keeps it as normal text_

On live example:
<img width="1530" alt="image" src="https://github.com/user-attachments/assets/864ca2fa-0b13-4253-8322-314d80806837">

On my project:
<img width="884" alt="image" src="https://github.com/user-attachments/assets/8ff27b20-67d5-42dd-bf86-bfdb41ef94aa">


4. _It doesn’t have a text-colour plugin_

I'd like to be able to change the colour to the text as in the image, but I'm not sure if there's an existent way (because I couldn't find it), or if a new plugin is needed:

<img width="1247" alt="image" src="https://github.com/user-attachments/assets/16be9db5-66d9-4ebf-95b6-ab6425aad506">
