### ISSUE TITLE
The "IconKey" type is not exported

### ISSUE THREAD

**Issue by basile-parent** [mdx-editor/editor#545]
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] I have read the documentation and cannot find an answer.

**Describe the bug**
The IconKey type is declared in the library but not accessible outside as it's not exported. Can you please export this type to properly use the "iconComponentFor" prop please ?

![image](https://github.com/user-attachments/assets/f39ac510-4321-4f92-b566-b067d4553118)

**Comment by petyosi** [comment]
You can open a PR for that.

**Comment by basile-parent** [comment]
@petyosi Can I also export either the "defaultSvgIcons" constant (from [defaultSvgIcons.tsx](https://github.com/mdx-editor/editor/blob/main/src/defaultSvgIcons.tsx)) or the "defaultIconComponentFor" (from [MDXEditor.tsx](https://github.com/mdx-editor/editor/blob/main/src/MDXEditor.tsx#L89)) ?

**Comment by basile-parent** [comment]
PR is open : #548
