### ISSUE TITLE
[BUG] disable scroll on select tag open

### ISSUE THREAD

**Issue by winkcor** [mdx-editor/editor#546]
If you want to ask for support or request features, [sponsor the project](https://github.com/sponsors/petyosi) and [contact me over email](mailto:petyo@mdxeditor.dev).

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] I have read the documentation and cannot find an answer.

**Describe the bug**
when select open for select heading or admonition, body get pointer-events:none and disable scroll. disabling scroll is not necessary and shouldn't happen.
in this case I use custom scrollbar and opening select tag change scroll state.
Is it necessary to add data-aria-hidden="true" and aria-hidden="true" to all element when a select tag open? it have lot overhead it even added to script tags. it's just select tag shouldn't be that complex.
**even link dialog not open properly, if all element be relative to parent it be great**

**Reproduction**
[codesandbox](https://codesandbox.io/p/devbox/mdx-mrzyzd)

**To Reproduce**
1. make page overflow and scroll
2. when click select and open it page scroll get disable 

**Expected behavior**
don't disable or change scroll state when open select

**Comment by petyosi** [comment]
This is the default behavior of the UI components used by the editor. If this does not fit your use case, you can build your own toolbar components.
