### ISSUE TITLE
[BUG] Disappearing image with using Rich Text copy-and-paste on a URL/markdown-styled image

### ISSUE THREAD

**Issue by rissois** [mdx-editor/editor#550]
This issue can be created easily on the [live demo](https://mdxeditor.dev/editor/demo)
1. Create a markdown-styled image in the document by either A) clicking on the image icon and adding the image from URL; or B) going into markdown mode and adding an image with `![]()`. (example image: `https://picsum.photos/200/300`)
2. On the rich text preview, copy the image
3. Paste the image elsewhere in the document

The image disappears, but you will see a new image toolbar. If you check the markdown, you will find `<img  src="..." width="0" height="0" />`

**Comment by petyosi** [comment]
This is fixed in the latest release.
