### ISSUE TITLE
[BUG] Root element not registered (Lexical Error #162)

### ISSUE THREAD

**Issue by mbreadmachine** [mdx-editor/editor#567]
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] I have read the documentation and cannot find an answer.

**Describe the bug**
When getting into a page containing an MDXEditor component, the client gives an Unhandled error with the title: **_Minified Lexical error #162; visit https://lexical.dev/docs/error?code=162 for the full message or use the non-minified dev environment for full errors and additional helpful warnings._**
This is only happening in the **minified** (npm run build) version of the project.

**To Reproduce**
1. `git clone https://github.com/mbreadmachine/arany-d-osztaly-weboldal.git`
2. Go into the project root.
3. Run `npm run build`
4. Then run the instructed commands. **If npm gives an error about folder creating, run the command with** `sudo`
5. Go to `localhost:3000`
6. Click on the plus button on the right-top corner.
7. Type in the password `MDXEditorIssuePassword` and click **Bejelentkezés**
8. Observe the error.

**Expected behavior**
The application would continue and go to the edit screen.

**Screenshots**
![iOS Safari tested on Vercel](https://github.com/user-attachments/assets/34e4bfa5-03c4-4af5-94be-f1b3f1a01514)
<img width="1920" alt="macOS Safari tested locally" src="https://github.com/user-attachments/assets/72ad2d4a-837b-49be-8609-f503f97fd314">
<img width="1920" alt="macOS Edge tested on Vercel" src="https://github.com/user-attachments/assets/55c8e898-0ef2-4923-a69c-a11d03e479ea">

**Desktop (please complete the following information):**
 - OS: macOS Sequoia Public Beta Build 24A5320a, iOS 18.0 Public Beta Build 22A5338b
 - Browser: Safari (Safari Version 18.0 (20619.1.26.31.3)) and Microsoft Edge (126.0.2592.68) on macOS, Safari on iOS

**Additional context**
Help would be appreciated.

**Comment by petyosi** [comment]
I'm afraid I don't have the capacity to troubleshoot and debug your project. Take a look at one of the framework specific quickstarts, they should work - if not, please fork from them and do a minimal reproduction of the problem.

**Comment by mbreadmachine** [comment]
Uh, I don't know if this would help, but I found this I-think-vital info about what could be the error:
The `mdxeditor-popup-container` classed div is outside of the root div. Here is a screenshot too:
<img width="643" alt="a screenshot of the mdxeditor-popup-container being outside of the react root" src="https://github.com/user-attachments/assets/4b79bde0-aba0-4989-b9dd-84d6e6428762">

**Comment by tobzy** [comment]
I'm having the same issue. Same error when I build. It works fine when I run on the dev server locally.

**Comment by mbreadmachine** [comment]
> I'm having the same issue. Same error when I build. It works fine when I run on the dev server locally.

I fixed the issue by running `npm audit fix --force` a bunch of times. I don't know if this helps, but try it.

**Comment by kocur4d** [comment]
> I'm having the same issue. Same error when I build. It works fine when I run on the dev server locally.

@tobzy I am experiencing the same error. Works locally but breaks on dev server. Did you get a chance to figure out what it is?

**Comment by mbreadmachine** [comment]
> > I'm having the same issue. Same error when I build. It works fine when I run on the dev server locally.
> 
> @tobzy I am experiencing the same error. Works locally but breaks on dev server. Did you get a chance to figure out what it is?

Well, it was a long time ago but I believe I fixed it by doing npm upgrade a bunch of times. And deleting node modules too. Try it, I don't know if it will work but try it.

**Comment by mbreadmachine** [comment]
> > I'm having the same issue. Same error when I build. It works fine when I run on the dev server locally.
> 
> I fixed the issue by running `npm audit fix --force` a bunch of times. I don't know if this helps, but try it.

Or try this maybe.

**Comment by kocur4d** [comment]
Running `npm audit fix --force` feels like to dangerous tbh. I need to look up a solution that is less of an equivalent of detonating a nuke - potentially.

**Comment by dboyd13** [comment]
@kocur4d - Did you find a solution? I've hit the same thing. Works fine in dev mode.

**Comment by mbreadmachine** [comment]
> @kocur4d - Did you find a solution? I've hit the same thing. Works fine in dev mode.

I think you should do what I said above and maybe upgrade all your packages. I am amazed that people are still flocking to this issue.
