### ISSUE TITLE
[BUG] Nested NestedLexicalEditor instances within table cell fail to update parentEditor MDX

### ISSUE THREAD

**Issue by mlequime** [mdx-editor/editor#570]
If you want to ask for support or request features, [sponsor the project](https://github.com/sponsors/petyosi) and [contact me over email](mailto:petyo@mdxeditor.dev).

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] I have read the documentation and cannot find an answer.

**Describe the bug**
A NestedLexicalEditor within a NestedLexicalEditor (to any depth) will fail to update with updateMdastNode when within a table cell.

This is due to the priority on the NESTED_EDITOR_UPDATED_COMMAND within TableEditor, it effectively captures the dispatched event before the change has been able to propagate, and sets state with the older value.

Lowering this state to match NestedLexicalEditor (COMMAND_PRIORITY_EDITOR) fixes the issue.

**Reproduction**
Working on adding an example

**To Reproduce**
1. Create a directive with a nested lexical editor and some action that sets its attributes with updateMdastNode
2. Include this within an instance of itself, within a table cell
3. Button will have no action, but button on the parent will work as it's a direct child of the TableCell

**Expected behavior**
Updating state within any depth should work

**Screenshots**

<img width="809" alt="Screenshot 2024-08-22 at 10 46 25" src="https://github.com/user-attachments/assets/1e3233ee-894c-4df3-8132-0d60c403d7d9">

**Desktop (please complete the following information):**
 - OS: [e.g. MacOS, Windows] - Windows can act funny sometimes.
 - Browser [e.g. Chrome, Safari]

**Additional context**
Will raise a merge request with the fix

**Comment by petyosi** [comment]
The diagram makes a lot of sense to me. Happy to accept a PR, I remember you were doing something in the space.
