### ISSUE TITLE
[BUG] Thematic Break Issues

### ISSUE THREAD

**Issue by SchrodingersGat** [mdx-editor/editor#572]
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] I have read the documentation and cannot find an answer.

**Describe the bug**

The [thematic break documentation](https://mdxeditor.dev/editor/docs/basic-formatting#thematic-break) indicates that three sequential hyphen / dash characters (`---`) will cause a thematic break to be rendered. 

However, with the plugin enabled, adding three dashes just renders three dashes:

![image](https://github.com/user-attachments/assets/faed93e3-2bd2-4327-81af-baa6e5b6478f)

Additionally, if you add a thematic break (via the "Add thematic break" button), it injects the following sequence: `***` - contrary to the example given in the documentation.

However, if you manually type `***` into the editor (expecting a thematic break), it injects `\*\*\*` - and so does not inject a thematic break at all.

**Expected behavior**

- User can manually input a "thematic break" using `---`
- Thematic break inserted using toolbar inserts `---` as per docs

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Firefox

**Comment by petyosi** [comment]
- The symbols used for the thematic break are determined by the configuration of the `toMarkdownOption`.

- The behavior you expect (typing markdown in the rich text editor) is supported through markdown shortcuts. A shortcut for a horizontal rule does not exist at the moment, but you add one, I see that the lexical playground has quite a few additional ones on top of the built-ins.

**Comment by SchrodingersGat** [comment]
Thanks @petyosi I was able to change the symbols using `toMarkdownOptions`. Struggling to work out where to start with a custom shortcut plugin. If you can point me in the right direction that would be appreciated!

**Comment by petyosi** [comment]
Adding additional is a bit convoluted. You can take a look at the source code of the markdown shortcuts plugin in the repository and see how Lexical implements them - they have some bulit-in ones and some additional "playground level" shortcuts. From there on, You can create your own version of the plugin or open a PR that adds the shortcut to the current built-in set, happy to accept it.
