### ISSUE TITLE
[BUG] Paste markdown doesn't format the code

### ISSUE THREAD

**Issue by jjanczur** [mdx-editor/editor#576]
**Describe the bug**
When I paste the markdown, MDX Editor escapes all the markdown characters

**Reproduction**
Copy some markdown and paste it to mds editor. 
In the source, I see that all markdown characters are escaped
![image](https://github.com/user-attachments/assets/660080a1-2b7f-4cc0-a362-061313076e6a)

**Expected behavior**
When I paste markdown it should be formatted like markdown and not escaped completely.

**Comment by tanishqkrk** [comment]
Why is this closed I need help 😭
