### ISSUE TITLE
[FEATURE] editor.getSelectedText()

### ISSUE THREAD

**Issue by mjp0** [mdx-editor/editor#577]
I would like to build a formatting menu that comes up when text is selected and I can do this with browser's `window.getSelection()` but with MDXEditor the problem is that I don't get any markdown formatting with `window.getSelection()`. This makes it hard to apply formatting with simple find/replace using `get/setMarkdown()`. Should the core have a function `getSelectedText()` that would return the raw markdown from selection?

I don't like to make things overly complicated, so this was the simplest way I could think how to do this sort of functionality. Lexical playground has this feature, so maybe there is something already in Lexical that MDXEditor could use?

**Comment by petyosi** [comment]
Doing find/replace is not the way to go. You should use the Lexical API for that purpose - it has everything you need to build it, and you can package it as an MDXEditor plugin. I would recommend that you go through the docs of the editor, especially the customization part.

**Comment by mjp0** [comment]
I did read the customization docs and to somebody with no previous experience with Lexical or Gurx, the plugin system looks so extremely complicated and time consuming to work with that I decided to brainstorm easier ways to get this done 🤷‍♂️

**Comment by huyhoang160593** [comment]
@mjp0 can you share the easier way that can be use for this particular case, I have been find a way to do this without any success :(

**Comment by petyosi** [comment]
@huyhoang160593 my response above is still valid. The idea of applying formatting (or, in fact, any kind of markdown update) through string manipulation is extremely flawed. 

MDXEditor is built on top of Lexical, the mdast utilities, and the Gurx stage management. Trying to customize and extend the editor without basic understanding of these concepts is not possible.
