### ISSUE TITLE
Adding docs to this repo

### ISSUE THREAD

**Issue by GentikSolm** [mdx-editor/editor#58]
This is more of a proposal. Could you add the source code for the docs into this repo? Firstly so we can contribute to the docs along with the package itself, but also for us to easily test changes in the package live.
Currently in order to test the package, I have to either spin up or clone the boilerplate for package usage, and manually link it in the `package.json`. We could kill two birds with one stone and have the docs double as a testing area for development on the package.

**Comment by petyosi** [comment]
100% agreed, that's in my todo list. Docs should be here. Contributing guides should also be here, since "npm run dev" gives you a nice playground, you don't have to clone the boilerplate.

**Comment by GentikSolm** [comment]
Found some nasty bugs that are wildly hard to debug with next. These are pretty avoidable, and would be avoidable with better documentation, especially on the getting started pages and such. Very eager for the docs to be open sourced, I'll be ready to make PRs into it immediately. If there is some sort of roadblock with merging the repo into this, I'd be more than happy to help, this library is a core part of my company's product so I'm more than willing to help out.

**Comment by petyosi** [comment]
Thank you for that. I added the docs in the repo, happy to accept contributions there. Will automate the release process next. https://github.com/mdx-editor/editor/commit/a4cb98ee6df74d076f6c003971dbcaf5137fb002
