### ISSUE TITLE
[BUG] toolbar popup are broken when mdx editor is rendered inside shadcn modal

### ISSUE THREAD

**Issue by MarcoColiaAtFiftyDeg** [mdx-editor/editor#581]
- [ x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [ x] I have read the documentation and cannot find an answer.

**Describe the bug**
Toolbar popup are broken when mdx editor is rendered inside shadcn modal, its impossible to open nor use any popup (link) bullet lists etc.

**Reproduction**
[LINK TO REPRODUCIBLE SANDBOX.](https://codesandbox.io/p/devbox/nszd4f?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522cm0xtr5ln00062v6lpmjnqze7%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522cm0xtr5lm00022v6lz7d9gh5g%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522cm0xtr5lm00042v6lcxp4ese9%2522%257D%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522cm0xtr5lm00052v6lns81bk3i%2522%257D%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522cm0xtr5lm00022v6lz7d9gh5g%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522cm0xtr5lm00012v6l9oixn6xa%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fpackage.json%2522%252C%2522state%2522%253A%2522IDLE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A21%252C%2522startColumn%2522%253A5%252C%2522endLineNumber%2522%253A21%252C%2522endColumn%2522%253A5%257D%255D%257D%252C%257B%2522id%2522%253A%2522cm0xv63gw00022v6l97a98vib%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A62%252C%2522startColumn%2522%253A34%252C%2522endLineNumber%2522%253A62%252C%2522endColumn%2522%253A34%257D%255D%252C%2522filepath%2522%253A%2522%252Fsrc%252Fstyles.css%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522id%2522%253A%2522cm0xtr5lm00022v6lz7d9gh5g%2522%252C%2522activeTabId%2522%253A%2522cm0xv63gw00022v6l97a98vib%2522%257D%252C%2522cm0xtr5lm00052v6lns81bk3i%2522%253A%257B%2522id%2522%253A%2522cm0xtr5lm00052v6lns81bk3i%2522%252C%2522activeTabId%2522%253A%2522cm0xtt59h00242v6l01n4hzun%2522%252C%2522tabs%2522%253A%255B%257B%2522type%2522%253A%2522SETUP_TASKS%2522%252C%2522id%2522%253A%2522cm0xtr7we000c2v6l4klmj4ao%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%252C%257B%2522type%2522%253A%2522TASK_PORT%2522%252C%2522port%2522%253A5173%252C%2522taskId%2522%253A%2522Development%2522%252C%2522id%2522%253A%2522cm0xtt59h00242v6l01n4hzun%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%255D%257D%252C%2522cm0xtr5lm00042v6lcxp4ese9%2522%253A%257B%2522id%2522%253A%2522cm0xtr5lm00042v6lcxp4ese9%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522cm0xtr5lm00032v6lbwvckc19%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522NEW_TERMINAL%2522%257D%252C%257B%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522Development%2522%252C%2522id%2522%253A%2522cm0xtrlik001b2v6lbpd18hs0%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%255D%252C%2522activeTabId%2522%253A%2522cm0xtr5lm00032v6lbwvckc19%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

**To Reproduce**
1. Go to the sandbox link'
2. Click on paragraph select or link
3. see the broken layout

**Expected behavior**
this editor must be ok inside dialogs

![image](https://github.com/user-attachments/assets/201a935b-0339-4885-8a16-bd0100a9a1c6)

**Comment by petyosi** [comment]
See https://github.com/mdx-editor/editor/issues/305
