### ISSUE TITLE
[BUG] Copy paste list from MacOS Pages app throw an error

### ISSUE THREAD

**Issue by dmowski** [mdx-editor/editor#583]
- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] I have read the documentation and cannot find an answer.

**Describe the bug**
When copy pasting List elements from docx file on MacOs, changes are not applied. 

**To Reproduce**
1. Go to [mdxeditor.dev demo](https://mdxeditor.dev/editor/demo)
2. Open provided document 
[listCopyPaste.docx](https://github.com/user-attachments/files/16965802/listCopyPaste.docx)
<img width="601" alt="image" src="https://github.com/user-attachments/assets/fd23f670-c000-4630-84ea-5b4983ed1b3d">

3. Copy/Paste content into Editor
3. Open browser console
4. See error:
<img width="1229" alt="image" src="https://github.com/user-attachments/assets/ef8c0fc8-de9e-4c2a-87af-723aa7fb4c80">

`TypeError: Cannot read properties of undefined (reading 'children')`

**Expected behavior**
No error in console, on change event triggered

**Desktop:**
 - OS: MacOS
 - Browser: Chrome 

**Additional context**
I found, that errors happened on module
[src/exportMarkdownFromLexical.ts:100](https://github.com/mdx-editor/editor/blob/main/src/exportMarkdownFromLexical.ts#L100)
Function: isParent

Additionally I checked that `mdastParent!` is undefined
<img width="868" alt="image" src="https://github.com/user-attachments/assets/94535967-96db-4bfa-91e7-0d11d617aaa0">

[src/exportMarkdownFromLexical.ts:100](https://github.com/mdx-editor/editor/blob/main/src/exportMarkdownFromLexical.ts#L175)

I've tried to update lexical libs to 0.17.1 - doesn't help

If someone would suggest what to do to fix it, or how to better research it I will be thankful.
For now, I am new at that code base, and it's little difficult to fix it fast for me

**Comment by petyosi** [comment]
@dmowski this is this issue: https://github.com/mdx-editor/editor/issues/178. Nested lists are very painful. I want to fix this, but it's not very simple, especially with copy paste. The AST is the culprit.

**Comment by petyosi** [comment]
@dmowski forgot to mention - thank you for the sponsorship. I will see if I can at least prevent the error, even if this means losing the indentation, which IMO is far more acceptable.
