### ISSUE TITLE
[BUG] Error while using JSX

### ISSUE THREAD

**Issue by emkademy** [mdx-editor/editor#585]
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] I have read the documentation and cannot find an answer.

**Describe the bug**
I am getting the following error:

```
Error: $cloneWithProperties: LexicalJsxNode.clone(node) (with type 'jsx') did not return a node with the same key, make sure to specify node.__key as the last argument to the constructor
```

**To Reproduce**
Follow the JSX guide from the documentation.

**Desktop (please complete the following information):**
 - Ubuntu 22.04
 - Chrome

**Comment by petyosi** [comment]
Can you give me a runnable sandbox?

**Comment by Tetragius** [comment]
the error is reproduced when - npm run dev

https://github.com/user-attachments/assets/cbc78199-a01e-44eb-b1d6-1d7b41cb77ee

can be fixed by a correction in the LexicalJsxNode.tsx file on line 35 by replacing

```ts
return new LexicalJsxNode(structuredClone(node.__mdastNode))
```

with

```ts
return new LexicalJsxNode(node.__mdastNode,  node.__key)
```

**Comment by adambarito** [comment]
> the error is reproduced when - npm run dev
> 
>  IMG_5320.MOV 
> can be fixed by a correction in the LexicalJsxNode.tsx file on line 35 by replacing
> 
> ```ts
> return new LexicalJsxNode(structuredClone(node.__mdastNode))
> ```
> 
> with
> 
> ```ts
> return new LexicalJsxNode(node.__mdastNode,  node.__key)
> ```

Agree with this. It appears to have happened with the bump in Lexical version. I'm currently running a patched version with the additional node.__key variable and everything works great.

**Comment by petyosi** [comment]
Can you open a PR? I will merge.
