### ISSUE TITLE
[BUG] Collapsing new lines during onChange

### ISSUE THREAD

**Issue by johnnyshankman** [mdx-editor/editor#589]
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] I have read the documentation and cannot find an answer.

**Describe the bug**

As `markdown` provide the following markdown

```
hello


world
```

The `onChange` will instantly trigger and return

```
hello

world
```

**Reproduction**
https://codesandbox.io/p/sandbox/mdx-editor-base-forked-nkwq82

**To Reproduce**
1. See that the output in the MDXEditor removes the extra line.
2. See that you can get the MDXEditor to OUTPUT the extra line when manually typed in, so you can create markdown that the editor itself cannot respect when fed back in.

**Expected behavior**
I should see multiple blank lines just like when I was originally typing it in the editor.

In goes a thing with two lines, out of onChange comes a thing with just one line:
![image](https://github.com/user-attachments/assets/3c6b3cdb-f994-4b79-b5fc-1b42b5af0401)

**Comment by johnnyshankman** [comment]
It seems as though anytime it sees `\n\n` it coalesces. Do I need a plugin or something to turn this behavior off?

**Comment by petyosi** [comment]
https://github.com/mdx-editor/editor/issues?q=is%3Aissue+multiple+new+lines

**Comment by johnnyshankman** [comment]
@petyosi thank you!

**Comment by johnnyshankman** [comment]
wow that's actually wild been coding and using rich text for years, never realized double new lines is not a thing. go figure!

**Comment by itsanishjain** [comment]
I stated to use @uiw/react-md-editor
and it's live saver it works more like how Github's Mdx editor works
