### ISSUE TITLE
How to properly use the Select primitive?

### ISSUE THREAD

**Issue by Fraank98** [mdx-editor/editor#590]
- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] I have read the documentation and cannot find an answer.

**Describe the bug**
Using the Select primitve, the formatting does not change.

**Reproduction**
https://codesandbox.io/p/sandbox/mdx-editor-base-forked-x9gkxw?file=%2Fsrc%2FApp.tsx%3A31%2C15&workspaceId=9dcd56a5-80ca-4682-b8ce-0df3a28d8f74

**To Reproduce**
Try to change block type from the dropdown

**Expected behavior**
Change of formatting

**Comment by petyosi** [comment]
Take a look at how the built-in block type select works: https://github.com/mdx-editor/editor/blob/main/src/plugins/toolbar/components/BlockTypeSelect.tsx. There are more details in the API reference.
