### ISSUE TITLE
[BUG] MDXEditor does not render content + onChange does not trigger if curly braces are present (only when jsxComponentDescriptors are used) 

### ISSUE THREAD

**Issue by AnujAgrawal30** [mdx-editor/editor#603]
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] I have read the documentation and cannot find an answer.

**Describe the bug**
Hi, I'm using "@mdxeditor/editor": "^3.11.5" and I had a use case where there would be curly braces in the markdown content. I'm also using my custom jsxComponentDescriptors, but was facing issues in the rendering and onChange stopped triggering on update

**Reproduction**
https://codesandbox.io/p/sandbox/mdx-editor-base-q8s7zr

**To Reproduce**
1. Go to the above codesandbox link
2. There I've three versions of MDXEditor (one default, one where I've used jsxComponentDescriptors and normal "Hello world" markdown and a third with "{Hello world}" as markdown
3. One renders and logs on console, while the other does not

**Expected behavior**
It should render as simple text and trigger the onChange as expected.

**Additional context**
I saw some MDX errors that could be responsible for the issue, but not sure
https://mdxjs.com/docs/troubleshooting-mdx/#unexpected-end-of-file-in-expression-expected-a-corresponding-closing-brace-for-

**Comment by petyosi** [comment]
That's expected, they are treated as had expressions

**Comment by AnujAgrawal30** [comment]
Hi,
Thanks for you feedback, apologies I was not aware about it. If you have any quick resolutions in mind on how I could make this work kindly let me know.
