### ISSUE TITLE
How can I enable RTL (right-to-left) mode?

### ISSUE THREAD

**Issue by Wojciech404** [mdx-editor/editor#609]
There is no information in documentation about RTL mode. Lexical library seems to be supporting it, but I don't know how to enable this in MDXEditor.
I've managed to do this with CSS overrides only, but Lexical keeps adding `dir="ltr"` to the text blocks. I think there should be an official correct way to do this.

**Comment by petyosi** [comment]
Feel free to sponsor the development of this feature or to submit a PR.
