### ISSUE TITLE
[BUG] It isn't possible to insert a new paragraph ( new line ) inside the table cell in rich mode.

### ISSUE THREAD

**Issue by swanITworks** [mdx-editor/editor#610]
- [ x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [ x] I have read the documentation and cannot find an answer.

**Describe the bug**
It isn't possible to insert a new paragraph ( new line ) inside the table cell in rich mode.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to 'Live demo'
2. Insert table
3. Click on any cell table
4. Type: Line1
5.  Press Enter -> It redirects you to the next cell, I tried shift + enter and it is the same

**Expected behaviour**
I would like to have possibility to add new line inside table cell in rich mode. For now, it's only available with using Markdown Mode.

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser Chrome

Thanks for solving in advance!

**Comment by parin-prog** [comment]
also can't indent text paragraph
