### ISSUE TITLE
[BUG] Safari: Wrong cursor placement

### ISSUE THREAD

**Issue by mnlkrs** [mdx-editor/editor#624]
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] I have read the documentation and cannot find an answer.

**Describe the bug**
On Safari, when the current editor content ends with an element with `contenteditable="false"` the caret will display at the very start of the editor. This also results in a user not being able to click next to the element to place.
![2024-11-05 23 57 47](https://github.com/user-attachments/assets/08e995f2-f8f5-4f6b-8e43-f43b66dfa887)

**To Reproduce**
On Safari:
1. Open [the demo](https://mdxeditor.dev/editor/demo)
2. Type something
3. Insert an image

**Expected behavior**
Like in other browsers, the caret should simply be put next to the element after inserting or when clicking:
![2024-11-06 00 01 59](https://github.com/user-attachments/assets/98ee81a8-abe7-454c-9cc5-7e65ebe9bc39)

**Desktop:**
 - OS: MacOS
 - Browser: Safari

**Additional context**
This is definitely a bug with Safari itself & not this library per se, however it still breaks the experience for Safari users.
Other libraries have faced the same problem:
* https://github.com/facebook/lexical/issues/4487
* https://github.com/ProseMirror/prosemirror/issues/1165#issuecomment-865678282

They have all seemed to fix it using an empty image tag:
* https://github.com/facebook/lexical/pull/6282/files
* https://github.com/ProseMirror/prosemirror-view/commit/68cab14b2a92417317735d50f45ee9583ed9140b

**Comment by petyosi** [comment]
MDXEditor uses Lexical. When https://github.com/facebook/lexical/pull/6282 gets merged, the fix will propagate. Feel free to track the problem with Lexical (perhaps there's some additional work to be done on the PR there?) and open a lexical version update for this repository.

**Comment by mnlkrs** [comment]
Great, could've taken a deeper look into this repo! Thanks for the swift response 👍

**Comment by mnlkrs** [comment]
The issue has been worked on in another PR, which has been merged. https://github.com/facebook/lexical/pull/6759
I'll have a close look at the releases!
