### ISSUE TITLE
[BUG] Extraneous newlines truncated on load

### ISSUE THREAD

**Issue by rbbydotdev** [mdx-editor/editor#639]
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] I have read the documentation and cannot find an answer.

**Describe the bug**
Initializing the editor with a markdown document with extraneous newlines, will automatically truncate the newline, thereby making a diff for the document /changing the document

**Reproduction**
The following will be truncated
```md
# Heading



```
becomes

```md
# Heading
```

**To Reproduce**
Initialized the editor with the first example with extraneous newlines, either check the document with the diff plugin, or monitor the gurx signals

**Expected behavior**
Expecting the newlines to remain.

**Screenshots**
None

**Desktop (please complete the following information):**
 - Macos
 - Firefox

**Comment by RokasAnisas** [comment]
Same issue. Input data:
<img width="493" alt="Screenshot 2024-11-24 at 18 54 11" src="https://github.com/user-attachments/assets/d9f7afb6-a4de-4fe9-973c-1ee74192005d">

Result:
<img width="1039" alt="Screenshot 2024-11-24 at 18 54 16" src="https://github.com/user-attachments/assets/5e5ae4a5-2545-41cb-9f31-0d6af0dac762">

**Comment by firminochangani** [comment]
I am facing the same issue.

**Comment by petyosi** [comment]
The trimming of the markdown is intentional, but I can see how this can cause problems. I might consider changing this in a future version or introducing a prop to control it.

@RokasAnisas this is not the same issue, markdown does this by design.

**Comment by woong97** [comment]
I faced same issue. How to fix?

**Comment by firminochangani** [comment]
> I faced same issue. How to fix?

At this point I am considering moving over to a different component.

**Comment by RokasAnisas** [comment]
> The trimming of the markdown is intentional, but I can see how this can cause problems. I might consider changing this in a future version or introducing a prop to control it.
> 
> @RokasAnisas this is not the same issue, markdown does this by design.

This is a bad representation of the problem, the other users that have commented on this issue with are more accurate
```
Hello\n\n\nWorld
```

Regardless, getting the same result, line breaks are removed, even thought the same `string` opened as a `markdown` document does indeed display those line breaks

**Comment by rbbydotdev** [comment]
@petyosi - Is there something happening within mdast? I haven't looked at the source but I am suspecting it's because mdx-editor is parsing to a tree and outputting again to markdown; am i correct in that assumption? If there were some way to reach into this and modify that process, could be more elegant than just adding an option.

**Comment by rbbydotdev** [comment]
> > I faced same issue. How to fix?
> 
> At this point I am considering moving over to a different component.

I understand your frustration, but this is open source, its as good and strong as the community who support it. I encourage you to stick around :)  -- I'm sure @petyosi would appreciate a PR

**Comment by mochetts** [comment]
Having the same issue, markdown renderers (such as [react-markdown](https://github.com/remarkjs/react-markdown)) are picking up the new lines but the editor isn't.

**Comment by ajboni** [comment]
I think I found a similar issue/workaround . 
This behavior was creating diff issues  with content generated in the editor itself.

Consider this example: 

1. Open a blank editor
2. Write `Line 1`
3. Press `Enter`
4. Press `Enter
5. Write `Line 2`

If getting the value with the `onChange(value)` callback the value is equal to: `Line 1\n\n\n\nLine 2` => this will trigger a diff issue when pasting back into the editor.

However, using `editorRef.current.getMarkdown() `returns the trimmed content `Line 1\n\nLine 2` => this will not trigger a diff issue.

So I'm using getMarkdown() to save the contents now, of course the file will look different when reopening but that's just how Markdown works.

**Comment by rubentlc** [comment]
I'm facing the same issue. This will not be fixed? Because if not, does not make any sense enable the users to do paragraphs.

**Comment by heruiwoniou** [comment]
Is there any update?

**Comment by petyosi** [comment]
I have already replied https://github.com/mdx-editor/editor/issues/639#issuecomment-2498064327. If someone wants to contribute an option that prevents the trimming of the whitespace in the beginning/end of the string, I'm happy to accept a PR. 

The other issue is by markdown design.

Locking this to avoid getting notifications from "any updates?".
