### ISSUE TITLE
'Command-A + backspace' doesn't delete all characters

### ISSUE THREAD

**Issue by jwbackhouse** [mdx-editor/editor#64]
When I use cmd+A to select all characters then hit the backspace key, it doesn't delete all characters. If I then repeat this, it deletes 3 characters at a time.

Interestingly, it works fine in the following scenarios:
- if I right click and choose 'select all' from the dropdown, then press backspace
- when starting from a blank input, typing in the text and then pressing cmd + A then backspace

This is only an issue in my setup, not the live demo on mdxeditor.dev. Interestingly, it also works

 I'm using v0.20.0 and am handling the markdown via a Redux state property (and passing a Redux action as the `onChange` handler). I've also tried only using `setMarkdown`/`getMarkdown` or only using the `value` and `onChange` props - the issue remains:

```js
<div
  onFocus={handleFocus}
  onBlur={handleBlur}
>
  <MDXEditor
    ref={ref}
    markdown={value}
    styleName='markdown-input'
    onChange={onChangeValue}
    placeholder={placeholder}
    plugins={[
      listsPlugin(),
      toolbarPlugin({
        toolbarContents: () => (
          <>
            <BoldItalicUnderlineToggles />
            <ListsToggle />
          </>
        ),
      }),
    ]}
  />
</div>
```

https://github.com/mdx-editor/editor/assets/42476198/9be350cd-f2cd-4136-9a99-c0eac4e20e1d

Thanks for the help (and for building such an awesome library 🎉 )

**Comment by petyosi** [comment]
I think (but I'm not sure) that the redux management plays some sort of a race condition with the internal Lexical engine. In general, I have not experimented with making the component support the classical "controlled" mode, due to its complexity and the cost of markdown processing. 

This being said, can you isolate the problem? I want to look into it further.

**Comment by jwbackhouse** [comment]
Thanks for the quick reply 🙏🏼 

I just added a timeout to the `onChangeValue` Redux action that I was passing to the `onChange` prop, and the problem remains - which makes me think it's internal to the editor?

```js
const MarkdownInput = ({
  value,  // Redux state
  onChangeValue // Redux action
}) => {
  const handleOnChangeValue = (markdown) => {
    setTimeout(() => {
      onChangeValue(markdown);
    }, 1000);
  };

  return (
    <MDXEditor
      markdown={value}
      onChange={onChangeValue}
      plugins={[
        listsPlugin(),
        toolbarPlugin({
          toolbarContents: () => (
            <>
              <BoldItalicUnderlineToggles />
              <ListsToggle />
            </>
          ),
        }),
      ]}
    />
  )
}

**Comment by petyosi** [comment]
[Reproduced the problem](https://codesandbox.io/s/markdown-repro-q8s7zr?file=/src/App.tsx). Seems to be a mess on the editor side, I'm doing some patches on top of Lexical in cmd+a.

**Comment by jwbackhouse** [comment]
Amazing, thank you
(obviously not important, but the sandbox link is broken btw)
