### ISSUE TITLE
[BUG] Pasting text from MS Word inserts as image in MDXEditor

### ISSUE THREAD

**Issue by MishaMgla** [mdx-editor/editor#641]
**Issue Description**

When copying content from MS Word for Mac OS and pasting it into MDXEditor, the content is inserted as an image instead of editable text.

**Steps to Reproduce**

1. Copy formatted text from MS Word for Mac OS.
2. Paste into MDXEditor. https://mdxeditor.dev/editor/demo
3. Observe that the content is inserted as an image.

 **Clipboard Data Formats**

After copying content from MS Word, I ran `osascript -e 'clipboard info'` and received the following output:
«class RTF », 43042 «class ut16», 814 «class HTML», 40872 Unicode text, 820 «class PDF », 46178 «class weba», 41178 «class rtfd», 1956 «class utf8», 410 string, 0

 **Analysis**

- The clipboard contains multiple text formats (**RTF**, **HTML**, **Unicode text**, **UTF-8**) and non-text formats (**PDF**, **RTFD**, **Web Archive**).
- **RTFD** and **PDF** formats may include images or render the content as a single non-editable object.
- It appears MDXEditor is prioritizing one of the non-text formats when pasting, resulting in the content being inserted as an image.

 **Expected Behavior**

MDXEditor should paste the text content with proper formatting, using one of the text-based formats like **RTF** or **HTML**.

 **Actual Behavior**

The editor inserts the content as an image, making the text non-editable.

 **Environment**

- **MS Word Version:** Microsoft Word for Mac Version 16.91
- **Mac OS Version:** macOS 15.1.1
- **Browser:** Chrome Version 131.0.6778.86
- **MDXEditor Version:** 3.19.0

 **Additional Information**

- I am willing to assist with further implementation and testing. I will be glad when someone suggests a starting point for researching the codebase.

**Comment by petyosi** [comment]
@maltesa it's great that your company relies on this project. If it brings value to your business, you can either 
contribute to it or sponsor its development and ongoing maintenance.

**Comment by maltesa** [comment]
@petyosi I was about to update my comment, because I was looking into the code to find a fix by myself. I will also consider the sponsorship.

This is the content of the clipboard item when text is pasted from office:
https://github.com/mdx-editor/editor/blob/da50ea9a90de6ccf4fd290f8f86296711807175b/src/plugins/image/index.ts#L257

**What is the expected behaviour?**
I think a clipboard item should *only* be pasted as image, if the item contains no text representation.

If you agree with this, I'm happy to open a pull-request for that.

**Comment by petyosi** [comment]
> I think a clipboard item should only be pasted as image, if the item contains no text representation.

That makes sense to me.

**Comment by maltesa** [comment]
#652 should fix this.
