### ISSUE TITLE
[BUG] Title is not getting updated after editing link

### ISSUE THREAD

**Issue by olgaplaga** [mdx-editor/editor#643]
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] I have read the documentation and cannot find an answer.

The closest bug is [#443](https://github.com/mdx-editor/editor/issues/443), but I am not sure if it is 100% the same issue. 

**Describe the bug**

The link title node (the link's anchor text in the editor after adding the link) is not updated after the link edit. 

**Reproduction**

1. The link is created by typing the URL and title into the link dialog text fields.
2. The link shows up in the editor.
3. Select the created link in the editor, and click again on the add link button in the toolbar.
4. Dialog opens again with two inputs prefilled correctly.
5. Change the URL and Title in the dialog. 
6. Save the changes.
7. The link node was correctly updated in the editor with a new URL.
8. The link node was **NOT** correctly updated with the new Title.

**Expected behavior**

The link node displayed in the editor should be updated in the new title. 

**Screenshots**

https://github.com/user-attachments/assets/5757bf77-5f01-4b5c-8a31-bf4d7ca4e2a2

The recording comes from the https://mdxeditor.dev/editor/demo.

MacOs on Chrome. 

**Additional context**
After investigating the code I came to the conclusion that the ` linkNode.setTitle(title)` in `updateLink$` method might not work correctly.
``` editor?.update(
          () => {
            const linkNode = getLinkNodeInSelection(selection)
            if (!linkNode) {
              const node = $createLinkNode(url, { title })
              node.append($createTextNode(linkContent))
              $insertNodes([node])
              node.select()
            } else {
              linkNode.setURL(url)
              linkNode.setTitle(title)
            }
          },
          { discrete: true }
        )
```

**Comment by petyosi** [comment]
@olgaplaga I can't really see the bug in the video you have recorded. You start with one, than change to two, and then two is displayed?

**Comment by olgaplaga** [comment]
@petyosi thank you for the answer. The video shows that the link node inside the editor (blue highlighted "One")  is not updated when I change the title in the dialog input. 
First I changed it to "Two", I closed the dialog, and the link node in the editor still shows "One". 
Then I changed to "three" - and the link note still shows "One".

Does it make it any clearer now?
