### ISSUE TITLE
[BUG] quotePlugin doesn't handle multi-line quotes correctly

### ISSUE THREAD

**Issue by zjullion** [mdx-editor/editor#646]
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] I have read the documentation and cannot find an answer.

**Describe the bug**
A blockquote can appear as a multi-line quote in rich text mode, but rendering it using a markdown renderer puts everything on a single line.

**To Reproduce**
With the quotePlugin enabled, either:
- In rich text mode: 
  1. Create a quote
  2. Use shift+enter to insert additional lines
- In source mode:
  1.  Write a quote in the format:
      ```
      > line one
      > line two
      ```

The quotes will appear on multiple lines in rich text mode - however, if the value is rendered in a markdown render, they will appear on a single line.

**Expected behavior**
I would expect quotes created in the manner described above to appear on a single line, as they would when rendering markdown.

**Screenshots**
Rich text mode:
![image](https://github.com/user-attachments/assets/73c9c9f5-b40e-4505-9e34-b31bb7296ed4)

Source mode:
![image](https://github.com/user-attachments/assets/8d66cceb-b3a6-40be-a5b2-20a1c810d38b)

Rendering using markedjs:
![image](https://github.com/user-attachments/assets/d7034e9f-53d5-4f8e-8be0-511e02fe454e)

**Desktop (please complete the following information):**
 - OS:  Windows
 - Browser: Chrome

**Comment by petyosi** [comment]
This seems to be a difference in the markdown engines. There are several discussions in the internet discussing this. For the record, Github renders the quotes with a multiple line:

> line one
> line two
