### ISSUE TITLE
[BUG] Cannot read properties of undefined (reading 'children')

### ISSUE THREAD

**Issue by murtazablt** [mdx-editor/editor#647]
**Describe the bug**
The error Cannot read properties of undefined (reading 'children') is reported intermittently on Sentry in the isParent function within exportMarkdownFromLexical.js. This indicates that node is undefined or does not have a children property during runtime in some user scenarios. This bug does not occur consistently and cannot be reproduced directly by visiting the affected users or following a specific set of steps.

**Reproduction**
Direct reproduction is not possible. The error occurs unpredictably in specific user scenarios. Observations via Sentry indicate that isParent is called with an invalid or undefined node object, causing a TypeError

**To Reproduce**
Since the issue is intermittent:
Monitor Sentry logs for instances of the error.
Analyze the context in which the function isParent is being called.
Add debugging logs or error tracing to capture the state of node during execution.

**Expected behavior**
The function isParent should validate the node parameter before accessing its properties. If the node is invalid, the function should return false or log a warning instead of throwing an error.

**Screenshots**
![image](https://github.com/user-attachments/assets/b7b4529f-8df1-42f3-93b0-4d7beed371ee)

**Desktop (please complete the following information):**
 - OS: Mac OS X >=10.15.7
 - Browser: Chrome 128.0.0

**Comment by petyosi** [comment]
if anyone has a concrete reproduction, please post the necessary steps.
