### ISSUE TITLE
[BUG] Attempted import error: 'INJECT_MESSAGE_TYPE' is not exported from '@codesandbox/nodebox'

### ISSUE THREAD

**Issue by Romain-Constant** [mdx-editor/editor#651]
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] I have read the documentation and cannot find an answer.

**Describe the bug**
Hi there !
First of all, thanks for this great and useful project.

I'm trying to use this package on my Next JS (without Typescript) project with npm but i'm facing a problem for import the package.
When i launch the project on my development server i have this error on my terminal:

 ⨯ ./node_modules/@codesandbox/sandpack-client/dist/clients/node/index.mjs
Attempted import error: 'INJECT_MESSAGE_TYPE' is not exported from '@codesandbox/nodebox' (imported as 'INJECT_MESSAGE_TYPE').

I have reproduced the EditorComponent and imported it dynamically like it's done in this repo (without Typescript): https://github.com/mdx-editor/mdx-editor-in-next

**Reproduction**
Pretty simple. Just launching my project with NexJS and npm.

**Screenshots**
![Image de code source](https://github.com/user-attachments/assets/f21030c9-839f-4a00-bd18-5d175839d4bb)
![Image de code source (1)](https://github.com/user-attachments/assets/ecc782cb-5b75-48c3-a0b4-d14db8caf9f3)

**Desktop (please complete the following information):**
 - OS: Mac OS - M1 - Sonoma 14.3
 - Browser: Arc, Chrome, Brave
 - "next": "^14.2.4",
 - "@mdxeditor/editor": "^3.19.3",

**Additional context**
I hope I've explained my problem properly.
I'm not a very experienced developer and it's my first issue ever on Github.
Thanks in advance

**Comment by petyosi** [comment]
> Pretty simple. Just launching my project with NexJS and npm.

This certainly makes easy for you to reproduce, but not for me, unfortunately. 

> I'm not a very experienced developer and it's my first issue ever on Github.

I'm sorry; I'm afraid that I don't have the capacity to assist you with your setup. Next.js is relatively complicated, and I guess something went wrong between that and the codesandbox dependency of the editor package.
