### ISSUE TITLE
[BUG] Multi line Quotes are not imported correctly

### ISSUE THREAD

**Issue by tautvilas** [mdx-editor/editor#659]
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] I have read the documentation and cannot find an answer.

**Describe the bug**
When writing quote content in markdown and pressing shift+enter a new quote paragraph is created. However when initializing editor with content such as

> *This is my multi-line quote*
>
> Remaining quote

All the strings are joined into one line

**Reproduction**
https://codesandbox.io/p/sandbox/mdx-editor-base-forked-3s8xpz

**Expected behavior**
Quote would not be concatenated

**Comment by petyosi** [comment]
https://github.com/mdx-editor/editor/issues/646.

**Comment by tautvilas** [comment]
I think if this is not planned to be fixed it should be made that editor would behave in a consistent manner (not allow to create newlines in quote with shift+enter)
