### ISSUE TITLE
Cannot assign to read only property 'key' of object '#

### ISSUE THREAD

**Issue by nsqnsq** [mdx-editor/editor#661]
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] I have read the documentation and cannot find an answer.

**Describe the bug**
When using your [example](https://github.com/mdx-editor/editor/blob/main/src/examples/html.tsx), an error message appears when selecting two lines of text consecutively：Cannot assign to read only property 'key' of object '#
**Reproduction**
 https://github.com/mdx-editor/editor/blob/main/src/examples/html.tsx

**To Reproduce**
1. Select two lines of text  （ar A paragra）
2. Click the button Make selection orange
![image](https://github.com/user-attachments/assets/8805f914-298f-4775-bb35-9c41b10ebe8b)

**Expected behavior**
This is almost certain to happen. I hope it works normally. Thank you.

**Screenshots**
![image](https://github.com/user-attachments/assets/8805f914-298f-4775-bb35-9c41b10ebe8b)

**Desktop (please complete the following information):**
 - OS: Windows  Must appear
 - Browser Chrome

**Additional context**
 "@mdxeditor/editor": "^3.20.0"
 "react": "^19.0.0",
 "react-dom": "^19.0.0"

**Comment by nsqnsq** [comment]
Hello author, I have some ideas about this bug: I think it should be that when two elements are selected and part of the text in them is partly selected, the error will be reported like this.

![image](https://github.com/user-attachments/assets/ddddc652-a7fc-48fb-9f89-35cf5f8877b3)

**Comment by petyosi** [comment]
The example you refer to be used as a starting point for your implementation and not a built-in feature. Feel free to adjust it to your needs.

**Comment by nsqnsq** [comment]
Hello, I still don't quite understand how to change this color. Can you tell me how to do it? Thank you
