### ISSUE TITLE
[BUG] I can't complete the form creation by typing in rich text mode

### ISSUE THREAD

**Issue by Wenrh2004** [mdx-editor/editor#666]
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] I have read the documentation and cannot find an answer.

**Describe the bug**
When in rich text mode and unable to create a table by typing in the appropriate text, I checked against source code mode and found that I was inserting escape characters before the `|` at the beginning of each line and spaces at the end of the line. Was I opening it the wrong way? I have certainly tried copying and pasting a form which was successfully rendered as an attempt.

**To Reproduce**
1. Add a table such as
    ```markdown
    | table | item  |
    | :---- | :---: |
    | 1     | 2     |
    ```
3. And turn to source mode the content is change

**Screenshots**
- The rich mode
<img width="495" alt="image" src="https://github.com/user-attachments/assets/75380e92-7acc-48c2-8bb3-1957c366d8ac" />

- The Source mode
<img width="495" alt="image" src="https://github.com/user-attachments/assets/319a02d3-ddc3-4262-9da5-c72341c37c27" />

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser Chrome, Safari

**Comment by petyosi** [comment]
I believe that you're looking for a different type of a markdown editor.
