### ISSUE TITLE
Getting "crypto is not defined" when trying to use headingsPlugin on Next.js

### ISSUE THREAD

**Issue by MagedMYoussef** [mdx-editor/editor#68]
I'm having some issues trying to set-up the editor on Next.js. Whenever I try to add headingsPlugin() as a parameter I get the following error:

`ReferenceError: crypto is not defined`

I followed the docs related to typescript/nextjs but with no luck.

Here's my sample component:

```'use client';

import React from 'react';

import dynamic from 'next/dynamic';
import '@mdxeditor/editor/style.css';
import {headingsPlugin} from '@mdxeditor/editor';

const MDXEditor = dynamic(
	() => import('@mdxeditor/editor').then((mod) => mod.MDXEditor),
	{ssr: false}
);

interface Props {}
export const MarkdownEditor = (props: Props) => {
	return <MDXEditor markdown=' Hello world' plugins={[headingsPlugin()]} />;
};
```

**Comment by petyosi** [comment]
My wild guess is that this is a node version related error. I just updated the [Next.js sample repository](https://github.com/mdx-editor/mdx-editor-in-next) with some additional conveniences. Can you clone it and see if it works for you?

**Comment by petyosi** [comment]
@MagedMYoussef I assume that fixed it for you, but let me know if this is not the case.
