### ISSUE TITLE
Bug: Trying to delete all text after selecting it with a keyboard shortcut does not delete everything

### ISSUE THREAD

**Issue by jpreis** [mdx-editor/editor#71]
When selecting all text in the editor using a keyboard shortcut (Ctrl / Cmd + A) and then trying to delete it using e.g. Backspace or Del does not delete all text.

### Steps to reproduce
- Open https://mdxeditor.dev/editor/demo
- delete all text (for some reason, it works initially)
- type in a some text (the issue is especially prominent in long lines of text without linebreaks/paragraphs)
- select all text using Ctrl / Cmd + A
- try deleting the text with Backspace / Del

### Current behaviour
Some text remains in the editor after trying to delete it

### Expected behaviour
All text is deleted

In my testing, this occurs in the latest versions of Chrome and Firefox (macOS), however not in Safari.
Also, when selecting all text using the cursor, deleting works properly.

**Comment by petyosi** [comment]
Solved in the latest version, updated the demo site, too. Thank you!
