### ISSUE TITLE
i18n Support

### ISSUE THREAD

**Issue by philipp985** [mdx-editor/editor#74]
Hello,
thanks for the great work!
Do you plan to support any type of translation for this editor?

**Comment by rex-iotum** [comment]
As a workaround I'm just going to make custom icons for the toolbar, i18n is a mandatory requirement for us.

https://github.com/mdx-editor/editor/issues/44

**Comment by petyosi** [comment]
It's necessary to do that at some point, but I don't have a concrete timeline for it. 

Happy to accept a PR.

**Comment by petyosi** [comment]
i18n is available in v2.10.0 through the translation prop: https://mdxeditor.dev/editor/docs/i18n.
