### ISSUE TITLE
Getting the ref of the internal Content Editable?

### ISSUE THREAD

**Issue by rex-iotum** [mdx-editor/editor#75]
Is there a way to get the ref of the internal Content Editable div?

I am trying to use this MDXEditor as the replacement chat field for our app, and I need to allow for inserting things (emoji/mentions/etc) into the current selection/caret, plus also listening for keydown events.

**Comment by petyosi** [comment]
Based on what you describe, you should be using the lexical API - accessing the editor from its context works as expected from the toolbar contents. They even have an [emoji plugin in their playground](https://playground.lexical.dev/).
