### ISSUE TITLE
Lack of trailing newline makes it difficult to write content under a JSX component

### ISSUE THREAD

**Issue by FinlayBP** [mdx-editor/editor#78]
Given the JSX example (http://localhost:61000/?story=jsx--example), you'll notice that it's impossible to click below the `BlockNode` in the rich text view to continue writing content underneath:

![Screenshot 2023-09-12 at 10 52 22](https://github.com/mdx-editor/editor/assets/98081005/e8b1b2ec-a0ae-4187-a095-0457c89cb920)

Using the `diffSourcePlugin`, you're able to click away to the raw markdown view to add a newline/write some text, but it would be great if the rich text editor was a little more flexible in this regard. Not exactly sure how to solve this, perhaps adding a trailing newline would work in most cases, or another way to insert the cursor after a component.

**Comment by petyosi** [comment]
Agreed, that's not perfect. One thing which I've taken into account is that, if you click in the JSX component and you press down arrow, a new paragraph is inserted below it. Another thing that can be done is to automatically insert a paragraph when a JSX node is inserted as the last child. However, the auto-trimming of the markdown will negate this. 

I will give this some more thought.

**Comment by petyosi** [comment]
I got this fixed at some point, if the last node is special, an empty paragraph is kept.
