### ISSUE TITLE
react-diff-view error

### ISSUE THREAD

**Issue by amberzaragoza** [mdx-editor/editor#79]
I get the following error when trying to use the MDXEditor in a Next.js app with the "pages" directory. Any ideas how to resolve this without having to modify the underlying code in my node_modules folder?

```
Uncaught Error: Cannot find package 'C:\...\node_modules\@mdxeditor\editor\dist\node_modules\react-diff-view\' imported from C:\...\node_modules\@mdxeditor\editor\dist\plugins\diff-source\DiffViewer.js
Did you mean to import react-diff-view/cjs/index.js?
```

Here is my MDXEditor setup for context:

```
<MDXEditor
    markdown={markdown}
    onChange={setMarkdown}
    contentEditableClassName="prose"
    plugins={[
        headingsPlugin(),
        listsPlugin(),
        linkPlugin(),
        linkDialogPlugin(),
        toolbarPlugin({
            toolbarContents: () => (
                <>
                    <UndoRedo />
                    <BoldItalicUnderlineToggles />
                    <ListsToggle />
                    <CreateLink />
                    <BlockTypeSelect />
                </>
            ),
        }),
    ]}
/>
```

**Comment by petyosi** [comment]
Did you [try the setup](https://github.com/mdx-editor/mdx-editor-in-next-pages/tree/master) I did here? Let me know if it needs some modification for me to reproduce the error.

**Comment by petyosi** [comment]
To be more precise, I think [you need this](https://github.com/mdx-editor/mdx-editor-in-next-pages/blob/c8d6b8be5c5ba2f2243ae62498bc274b22402fb8/next.config.js#L3).

**Comment by amberzaragoza** [comment]
This worked, thank you so much!

**Comment by drac94** [comment]
Sorry to comment on a closed issue but I am having this exact problem but when running tests using vitest, any hint on how to solve it? do you want me to create another issue? @petyosi

**Comment by petyosi** [comment]
@drac94 - I replaced the react-diff-view dependency in the latest version. Give it a try, and if you're still experiencing problems, open another issue.

**Comment by drac94** [comment]
Thanks @petyosi !! I upgraded to the latest version and now I am getting this 
```
SyntaxError: Named export '$isElementNode' not found. The requested module 'lexical' is a CommonJS module, which may not support all module.exports as named exports.
CommonJS modules can always be imported via the default export, for example using:

import pkg from 'lexical';
const { $isElementNode } = pkg;
```
