### ISSUE TITLE
How to define toolbar styles like in the live demo?

### ISSUE THREAD

**Issue by zhangmingemma** [mdx-editor/editor#80]
I would like to know how to define the styles for the toolbar similar to what is shown in the live demo. Is the code for the live demo available in the open source repository? I couldn't find it in the repository's codebase. Could you please provide guidance on how to achieve the same toolbar styling as demonstrated in the live demo?

**Comment by petyosi** [comment]
There's an export of the toolbar [called KitchenSinkToolbar](https://github.com/mdx-editor/editor/blob/8f0448648fbc706d37ad8137df0fffdb73a5a69f/src/plugins/toolbar/components/KitchenSinkToolbar.tsx#L38). However, I would strongly recommend that you take its contents and adjust them to your requirements.

**Comment by greenking19** [comment]
> There's an export of the toolbar [called KitchenSinkToolbar](https://github.com/mdx-editor/editor/blob/8f0448648fbc706d37ad8137df0fffdb73a5a69f/src/plugins/toolbar/components/KitchenSinkToolbar.tsx#L38). However, I would strongly recommend that you take its contents and adjust them to your requirements.

Can't KitchenSinkToolbar be used directly?
```tsx
function App() {
  return (
    <MDXEditor
      markdown='hello world'
      plugins={[
        codeBlockPlugin({ defaultCodeBlockLanguage: 'js' }),
        sandpackPlugin({ sandpackConfig: simpleSandpackConfig }),
        codeMirrorPlugin({
          codeBlockLanguages: { js: 'JavaScript', css: 'CSS' }
        }),
        toolbarPlugin({
          toolbarContents: () => (
            <KitchenSinkToolbar />
          )
        })
      ]}
    />
  );
}

```
Error prompted👇
<img width="673" alt="image" src="https://github.com/mdx-editor/editor/assets/43332372/f3db058f-2d13-49a9-959b-33bac407d292">

**Comment by petyosi** [comment]
@greenking19 You need to include all plugins, because the kitchen sink toolbar brings in all functionality - you're missing the diff source plugin in that kase.

**Comment by greenking19** [comment]
> @greenking19 You need to include all plugins, because the kitchen sink toolbar brings in all functionality - you're missing the diff source plugin in that case.
Thank you! I just realized this problem, and now I have solved it.
Thank you!

**Comment by greenking19** [comment]
> @greenking19 You need to include all plugins, because the kitchen sink toolbar brings in all functionality - you're missing the diff source plugin in that case.

Thank you! I just realized this problem, and now I have solved it.
Thank you!
🥳
