### ISSUE TITLE
How to customize rendering of img nodes

### ISSUE THREAD

**Issue by zhangmingemma** [mdx-editor/editor#86]
I would like to know how to customize the rendering of <img> nodes in my project. Specifically, I need to add a toolbar below the rendered images to enable actions such as image replacement. I am seeking guidance on how to achieve custom rendering of images in this manner.

Could you please provide instructions or examples on how to implement this custom rendering? I am particularly interested in understanding how to add the toolbar beneath the rendered images and how to handle image replacement functionality.

Thank you for your assistance in advance!

**Comment by petyosi** [comment]
To do so, you can create your own image plugin and lexical image node, based on the current one. Use the source code of the current image plugin as a starting point.
