### ISSUE TITLE
Request for an API similar to onFocus to track focus events within the editor

### ISSUE THREAD

**Issue by zhangmingemma** [mdx-editor/editor#87]
I wonder if there has an API that  can allow developers to listen for focus events that occur within the editor and provide information such as the focus position and surrounding context.

**Comment by petyosi** [comment]
You can build your own plugin for that purpose and tap into the Lexical API. The core plugin does something similar for the selection, you can [start tracing the logic from here](https://github.com/mdx-editor/editor/blob/main/src/plugins/core/index.ts#L157).
