### ISSUE TITLE
Unable to handle two-way binding with `markdown` prop.

### ISSUE THREAD

**Issue by gregorip02** [mdx-editor/editor#9]
It is not possible to re-render the component when an internal state property changes. E.g.

```tsx
import { MDXEditor } from '@mdxeditor/editor'
import { useState } from 'react'
import '@mdxeditor/editor/style.css'

export function Editor () {
  const [markdown, setMarkdown] = useState('...')
  return (
    <>
      <MDXEditor
        markdown={markdown}
        onChange={currentMarkdown => {
          if (currentMarkdown === ':emoji:') {
            setMarkdown('☺️')
          }
        }}
      />
    </>
  )
}
```

**Comment by petyosi** [comment]
That's a bug indeed, updating the prop should affect the component. Will look into it.

The example you've given is not exactly what I imagine as usage, though. There are certain options to do such kind of emoji substitution using the Lexical capabilities - these should be more performant.

**Comment by petyosi** [comment]
I looked at that from a few angles and decided to implement the capability through a method instead. It is a bit more involved, but covers scenarios like the following one:

1. The editor starts with a value `foo`
2. value gets updated to `bar`
3. The user types in `baz`
4. The developer wants to set the value back to `bar`, but the state available is still "bar", so this is not possible. 

I think the method should (`setMarkdown`) should work.

**Comment by mohammadreza490** [comment]
I'm trying to use the `setMarkdown` method to update the makrdown but I'm getting this error:
```
TypeError: _mdEditor_current.setMarkdown is not a function
```
This is how I'm doing it:
```
            <MDXEditor
              ref={mdEditor}
              onChange={(markdown) => {
                mdEditor.current?.setMarkdown(markdown);
              }}
              markdown={markdownContent}
              viewMode="editor"
              contentEditableClassName="content-text"
              // toolbarComponents={[ChartToolbarButton]}
            />
```

**Comment by mohammadreza490** [comment]
@petyosi yes I'm using version 0.7.0. might it happen because of importing the `MDXEditorMethods` statically to create the Ref object? because I've been having some issues with imports and had to do them dynamically

**Comment by petyosi** [comment]
No idea what could be the reason. Notice that the implementation you have might create an endless loop, though. maybe it accesses the ref before it is assigned. 

I don't know what you're trying to achieve; I mentioned earlier that doing some substitutions within the editor contents as the user inputs something is better handled through Lexical - you can inject plugins in the toolbar, for example.

To give you more information, here's how [Lexical handles markdown transformers](https://lexical.dev/docs/packages/lexical-markdown) like headings and lists.

**Comment by mohammadreza490** [comment]
@petyosi still facing the same issue. I'm following your example and setting the ref like this:
`const mdEditor = React.useRef<MDXEditorMethods>(null);`
and then using the ref like this:
```
<MDXEditor
  ref={mdEditor}
```
I'm trying to update the markdown value on change using the `setMarkdown` method you've implemented but keep getting the `is not a function error. the same happens for the `getMarkdown` method. 

I tried to see what the `current` ref is and the value is `{retry: ƒ}` and it doesn't have the functionalities for getting and setting the markdown

**Comment by petyosi** [comment]
`MDXEditorMethods` is a typescript type, so that you can get the right autocomplete in your IDE. You don't have to (nor you can) import it dynamically. 

I'm afraid that I can't guess what's going on with your implementation. You can fork the sandbox I linked above and reproduce the problem there. I will take a look.

**Comment by mohammadreza490** [comment]
I somehow made it work by ensuring the MDXEditor package gets fully loaded before rendering the editor. The good news is, it works as expected and both `setMarkdown` and `getMarkdown` are now available. Thanks for the help @petyosi

**Comment by mareksl** [comment]
@mohammadreza490 
Could you explain how you managed to do that?
I'm having the same issue and just can't access the correct `ref` on a dynamically imported editor.

**Comment by petyosi** [comment]
@mareksl Here's a workaround I added to the next.js example to solve that problem. https://github.com/mdx-editor/mdx-editor-in-next/commit/9f7905c44e9e61ec206f0a2832d9875b60be0593.

**Comment by mareksl** [comment]
Thanks, works perfectly!
So, basically just pass the `ref` as a normal prop, without using `forwardRef`.
