### ISSUE TITLE
Support h1/h2/h3 html tags

### ISSUE THREAD

**Issue by jwbackhouse** [mdx-editor/editor#90]
Hi. Similar issue to #67 , this time with HTML tags. 

I managed to trigger the error in the Live Demo by going to the `Source` view, wrapping a word in an `<h1>` tag then clicking on the `Live demo` link in the header (just clicking back to the `Rich text` view seemed to delete the tag altogether).

There may be a plugin that handles HTML but I couldn't figure out which one.

Thanks

**Comment by petyosi** [comment]
There isn't one at the moment, this being said, it's relatively easy to extend the respective plugins to handle such HTML tags - in the example you've provided, that would be the headings plugin. The code plugin does this for example. 

Happy to accept a PR on the matters. I might get to that, but realistically it's not going to be this month for sure.

**Comment by jwbackhouse** [comment]
Ok thanks, makes sense. Ideally as well as handling heading tags it would be good to have a fallback for any other HTML tag (where perhaps they just get rendered as strings). If I can find the time I'll have a look at a PR 👍🏼

**Comment by petyosi** [comment]
You can implement such a fallback easily, but I am kinda hesitant to do it, since it puts the editor in a less than perfect state, an HTML tag does not have a "proper" editor associated with it. 

Nevertheless, html tags like the headings should be safely converted into their markdown equivalent.

**Comment by petyosi** [comment]
Closing this, as the generic HTML handler solves the error.
