### ISSUE TITLE
Module Not found Error with Nextjs 13.4 App Directory

### ISSUE THREAD

**Issue by yousuf4you** [mdx-editor/editor#96]
# I am facing the error 

```shell
- error ./node_modules/@mdxeditor/editor/dist/plugins/diff-source/DiffViewer.js:4:0
Module not found: Can't resolve '../../node_modules/react-diff-view/style/index.css.js'

https://nextjs.org/docs/messages/module-not-found

Import trace for requested module:
./node_modules/@mdxeditor/editor/dist/plugins/diff-source/DiffSourceWrapper.js
./node_modules/@mdxeditor/editor/dist/plugins/diff-source/index.js
./node_modules/@mdxeditor/editor/dist/index.js
./components/PostEditor.tsx
./app/posts/new/page.tsx
- wait compiling /favicon.ico/route (client and server)...
- event compiled successfully in 199 ms (1423 modules)
```

```
# Iam using 
OS: Ubuntu@22.04.3
Runtime: Bun@1.0.1
NextJs@13.4
MDXEditor@1.0.0
```

![Screenshot from 2023-09-23 19-47-22](https://github.com/mdx-editor/editor/assets/60110696/b70954a3-bfc0-4d27-acae-cc7f6cf03cc6)

`Hope someone will solve the error.`

**Comment by KKUPGRADER** [comment]
make this change in changes  `next.config.js`  

```
/** @type {import('next').NextConfig} */
const nextConfig = {
  transpilePackages: ['@mdxeditor/editor', 'react-diff-view'],
  reactStrictMode: true,
  webpack: (config) => {
    // this will override the experiments
    config.experiments = { ...config.experiments, topLevelAwait: true };
    // this will just update topLevelAwait property of config.experiments
    // config.experiments.topLevelAwait = true 
    return config;
  },
}

module.exports = nextConfig
```

Checkout the documentation : [Docs](https://mdxeditor.dev/editor/docs/getting-started#nextjs-pages-router)

**Comment by yousuf4you** [comment]
But I am using App Route.

**Comment by KKUPGRADER** [comment]
I think Compliers works the same for both

**Comment by petyosi** [comment]
@yousuf4you [here's a working example of the editor in Next.js](https://github.com/mdx-editor/mdx-editor-in-next) app router setup. You can compare your implementation to what's there. Perhaps I am missing something, but I can't tell what's the problem based on the information you've provided. If you pinpoint the problem further, fork the example, modify it accordingly, and share your fork here.

P.S. As those issues often end up stale, I will close this one - but I will reopen it once there's something actionable.

**Comment by yousuf4you** [comment]
I fixed the error vie to install `"@codemirror/lang-markdown": "^6.2.0",`.
