### ISSUE TITLE
Prevent focus when in 'controlled mode'

### ISSUE THREAD

**Issue by jwbackhouse** [mdx-editor/editor#97]
Hi. When using the editor in 'controlled mode', the div with class `_contentEditable_xxx` is focused when you call `ref.current.setMarkdown()` - in the example below, this happens when the `value` prop changes and the component re-renders:

```js
const MarkdownInput = ({
  value,  // Redux state
  onChangeValue // Redux action
}) => {
  const ref = useRef(null);
  useEffect(() => {
    if (ref?.current?.getMarkdown() !== value) {
      ref?.current?.setMarkdown(value);
    }
  }, [value]);

  return (
    <MDXEditor
      ref={ref}
      markdown={value}
      onChange={onChangeValue}
      ...
    />
  )
}
```

In our use case, this change of focus breaks the user flow. I'm afraid I can't see what is triggering this in the source code so not sure exactly how this could be solved, but would it be possible to prevent the editor setting the focus programatically and instead just let it be done manually by the user?

**Comment by jwbackhouse** [comment]
Sure thing - [here you go](https://codesandbox.io/s/catch-all-plugin-forked-dnv76r)

**Comment by gotenxds** [comment]
@petyosi Sorry to bring this up from the dead but it seems this happens again in the latest version

**Comment by petyosi** [comment]
@gotenxds open a new issue with a proper reproduction.
