### ISSUE TITLE
Virtual File Path Issue with '@lexical/utils' in Yarn Berry

### ISSUE THREAD

**Issue by TypingOK** [mdx-editor/editor#98]
Hello!
I'm using a translation tool to help me with English because I'm not very good at it. I'm trying my best to have a natural conversation, but I'm facing difficulties. Thank you for understanding.

I'm using Yarn Berry with zero-install (pnp), and I'm also using Next.js version 13.4. When using this library, I encountered the following error:

```
.yarn/__virtual__/@lexical-html-virtual-9834d778c5/0/cache/@lexical-html-npm-0.12.2-e326b97b92-a3538d923f.zip/node_modules/@lexical/html/LexicalHtml.dev.js:10:0
Module not found: Can't resolve '@lexical/utils'
```

However, the '@lexical' module was properly installed in the .cache directory, so I manually corrected the virtual file path in the .pnp.cjs file to point to the correct location where the module exists.

```
["@lexical/html", [\
        ["npm:0.12.2", {\
          "packageLocation": "./.yarn/cache/@lexical-html-npm-0.12.2-e326b97b92-a3538d923f.zip/node_modules/@lexical/html/",\
          "packageDependencies": [\
            ["@lexical/html", "npm:0.12.2"]\
          ],\
          "linkType": "SOFT"\
        }],\
        ["virtual:cbaf542e901be987c542f237b09710763e2398640d4cfbc730eec593638e8c6b744a299924741322b282d7add82bce466fad4146f927fbdbf0929226c1088cec#npm:0.12.2", {\
          "packageLocation": "./.yarn/__virtual__/@lexical-html-virtual-9834d778c5/0/cache/@lexical-html-npm-0.12.2-e326b97b92-a3538d923f.zip/node_modules/@lexical/html/",\
          "packageDependencies": [\
            ["@lexical/html", "virtual:cbaf542e901be987c542f237b09710763e2398640d4cfbc730eec593638e8c6b744a299924741322b282d7add82bce466fad4146f927fbdbf0929226c1088cec#npm:0.12.2"],\
            ["@lexical/selection", "virtual:78d3b2cf9d66cea6f9dbf085723c1921637db8d2743e9c806a5b33b8e74fb7cef2eeb84493bbcb4137f40b12bf7e3fcef237c361db2eda90f632c5af4ce3bfb1#npm:0.12.2"],\
            ["@lexical/utils", "virtual:78d3b2cf9d66cea6f9dbf085723c1921637db8d2743e9c806a5b33b8e74fb7cef2eeb84493bbcb4137f40b12bf7e3fcef237c361db2eda90f632c5af4ce3bfb1#npm:0.12.2"],\
            ["@types/lexical", null],\
            ["lexical", "npm:0.12.2"]\
          ],\
          "packagePeers": [\
            "@types/lexical",\
            "lexical"\
          ],\
          "linkType": "HARD"\
        }]\
      ]],\
```

In the 'packageDependencies' section, the 'virtual' part was null in ["@lexical/utils", "virtual:78d3b2cf9d66cea6f9dbf085723c1921637db8d2743e9c806a5b33b8e74fb7cef2eeb84493bbcb4137f40b12bf7e3fcef237c361db2eda90f632c5af4ce3bfb1#npm:0.12.2"], and after changing that part, along with a few other changes, it started working correctly.

**Comment by petyosi** [comment]
I'm afraid that I have no experience with yarn berry and its setup specifics. The MDXEditor package works as expected with NPM, which I believe is the reference implementation. 

If anything, you may actually report this to the yarn berry issue tracker - perhaps they have encountered similar issue.
