### ISSUE TITLE
remove duplicate logic from code

### ISSUE THREAD

**Issue by yuzhouu** [mdx-editor/editor#99]
first, thanks for your effort.

I thought below code is same

https://github.com/mdx-editor/editor/blob/20420a80f9f7c836eebeb82bf4f46c6e6ce6a8e1/src/plugins/lists/index.ts#L44-L55

```js
 const element = anchorNode.getKey() === 'root' ? anchorNode : anchorNode.getTopLevelElementOrThrow()
```

**Comment by petyosi** [comment]
Can you explain further? Not sure what you mean.

**Comment by yuzhouu** [comment]
sure

below is define of `getTopLevelElementOrThrow`, do the same thing as `$findMatchingParent` in line 49

```js
/**
   * Returns the highest (in the EditorState tree)
   * non-root ancestor of this node, or null if none is found. See {@link lexical!$isRootOrShadowRoot}
   * for more information on which Elements comprise "roots".
   */
  getTopLevelElement(): ElementNode | this | null {
    let node: ElementNode | this | null = this;
    while (node !== null) {
      const parent: ElementNode | this | null = node.getParent();
      if ($isRootOrShadowRoot(parent)) {
        return node;
      }
      node = parent;
    }
    return null;
  }

  /**
   * Returns the highest (in the EditorState tree)
   * non-root ancestor of this node, or throws if none is found. See {@link lexical!$isRootOrShadowRoot}
   * for more information on which Elements comprise "roots".
   */
  getTopLevelElementOrThrow(): ElementNode | this {
    const parent = this.getTopLevelElement();
    if (parent === null) {
      invariant(
        false,
        'Expected node %s to have a top parent element.',
        this.__key,
      );
    }
    return parent;
  }
```

**Comment by petyosi** [comment]
I see. My Lexical knowledge is not so strong yet, the code looks similar, but I can't say for sure. For the record, this snippet comes from the Lexical implementation itself:

https://github.com/facebook/lexical/blob/f0933ba2772ed8041014aa6affd717ef0f72989f/packages/lexical-playground/src/plugins/ToolbarPlugin/index.tsx#L516-L526

Do you experience any concrete issues due to the current implementation? I can examine that further.

**Comment by yuzhouu** [comment]
I see, no issue, just read the source code and confuse about this.

**Comment by yuzhouu** [comment]
Got it, getTopLevelElementOrThrow is method of node, it maybe changed by user. 
Last, thanks for your patience.
